import type { Question } from "@/lib/types";

// Source: testlar_xulq14.xlsx
// The correct answer can be listed in any position; options are shuffled in the test.
export const questions: Question[] = [
  {
    id: 1,
    question: "A. Bandura va R. Walters tadqiqotlarida asotsial o‘smirlarning asosiy xususiyati nimada namoyon bo‘ladi?",
    options: [
      "Ular ijtimoiy jihatdan muvaffaqiyatli va tajovuzni ochiq ifodalaydi",
      "Ular passiv bo‘ladi",
      "Ular faqat nazariy bilimga ega",
      "Ular tajovuzsiz bo‘ladi",
    ],
    correctAnswer: "Ular ijtimoiy jihatdan muvaffaqiyatli va tajovuzni ochiq ifodalaydi",
  },
  {
    id: 2,
    question: "A. Bandura va R. Walterslar fikricha, o‘g‘il bolalarda antijamoatchilik yo‘nalishining shakllanishiga qaysi omil kuchli ta’sir qiladi?",
    options: [
      "Otasi bilan ijobiy munosabatning yo‘qligi",
      "Do‘stlar",
      "Ona bilan munosabat",
      "Maktab",
    ],
    correctAnswer: "Otasi bilan ijobiy munosabatning yo‘qligi",
  },
  {
    id: 3,
    question: "A. Ye. Lichko “delinkventlik” tushunchasiga nimani kiritgan?",
    options: [
      "Jinoiy javobgarlikka olib kelmaydigan mayda huquqbuzarliklar",
      "Faqat og‘ir jinoyatlar",
      "Faqat iqtisodiy jinoyatlar",
      "Faqat psixik kasalliklar",
    ],
    correctAnswer: "Jinoiy javobgarlikka olib kelmaydigan mayda huquqbuzarliklar",
  },
  {
    id: 4,
    question: "Quyidagilardan qaysi biri Lichko bo‘yicha delinkvent xulqqa misol bo‘ladi?",
    options: [
      "Maktabga bormaslik",
      "Ilmiy faoliyat",
      "Sport bilan shug‘ullanish",
      "Kitob o‘qish",
    ],
    correctAnswer: "Maktabga bormaslik",
  },
  {
    id: 5,
    question: "V.V. Kovalyov delinkvent xulqni qanday baholaydi?",
    options: [
      "Jinoiy xulq sifatida",
      "Oddiy xulq",
      "Ijobiy xulq sifatida",
      "Tasodifiy holat sifatida",
    ],
    correctAnswer: "Jinoiy xulq sifatida",
  },
  {
    id: 6,
    question: "Izchil-kriminogen tipning asosiy xususiyati nimada?",
    options: [
      "Jinoyat shaxs hayot tarzining bir qismi bo‘lishi",
      "Tasodifiy jinoyatlar",
      "Faqat bir martalik xulq",
      "Faqat guruh ta’siri",
    ],
    correctAnswer: "Jinoyat shaxs hayot tarzining bir qismi bo‘lishi",
  },
  {
    id: 7,
    question: "Vaziyatli-kriminogen tip qanday xulq bilan tavsiflanadi?",
    options: [
      "Jinoyatning vaziyat ta’sirida yuzaga kelishi",
      "Doimiy jinoyatchilik",
      "Faqat rejalashtirilgan jinoyat",
      "Faqat individual qaror",
    ],
    correctAnswer: "Jinoyatning vaziyat ta’sirida yuzaga kelishi",
  },
  {
    id: 8,
    question: "V.N. Kudryavtsev bo‘yicha professional jinoyatchilar kimlar?",
    options: [
      "Jinoyatdan daromad topib yashovchilar",
      "Tasodifiy jinoyatchilar",
      "Bir martalik jinoyatchilar",
      "O‘quvchilar",
    ],
    correctAnswer: "Jinoyatdan daromad topib yashovchilar",
  },
  {
    id: 9,
    question: "Yu.B. Mojginskiy ta’kidlashicha, o‘smirlarda qanday patologik tendensiyalar kuzatiladi?",
    options: [
      "Affekt buzilishi va shaxs krizisi",
      "Faqat jismoniy o‘zgarishlar",
      "Faqat bilim yetishmasligi",
      "Faqat ijtimoiy muammo",
    ],
    correctAnswer: "Affekt buzilishi va shaxs krizisi",
  },
  {
    id: 10,
    question: "Uzoq muddatli stress nimaga olib kelishi mumkin?",
    options: [
      "Delinkvent xulq shakllanishiga",
      "Faqat ijobiy xulq",
      "Faqat bilim oshishiga",
      "Faqat dam olishga",
    ],
    correctAnswer: "Delinkvent xulq shakllanishiga",
  },
  {
    id: 11,
    question: "X. Remshmidt delinkvent xulq etiologiyasida nimani ajratadi?",
    options: [
      "Yengil hissiy buzilishlarni",
      "Faqat biologik omillarni",
      "Faqat iqtisodiy omillarni",
      "Faqat ijtimoiy omillarni",
    ],
    correctAnswer: "Yengil hissiy buzilishlarni",
  },
  {
    id: 12,
    question: "Piromaniya qanday buzilish turiga kiradi?",
    options: [
      "Qiziqish patologiyasi",
      "Xotira buzilishi",
      "Tafakkur buzilishi",
      "Nutq buzilishi",
    ],
    correctAnswer: "Qiziqish patologiyasi",
  },
  {
    id: 13,
    question: "Kleptomaniya nimani anglatadi?",
    options: [
      "O‘g‘irlikka bo‘lgan patologik moyillik",
      "O‘qishga qiziqish",
      "Sportga qiziqish",
      "Muloqotga qiziqish",
    ],
    correctAnswer: "O‘g‘irlikka bo‘lgan patologik moyillik",
  },
  {
    id: 14,
    question: "Buzilgan qiziqishlar sindromining asosiy belgisi qaysi?",
    options: [
      "Impulsivlik va yengib bo‘lmaslik",
      "Barqarorlik",
      "Faqat bilimlilik",
      "Faqat ijtimoiylik",
    ],
    correctAnswer: "Impulsivlik va yengib bo‘lmaslik",
  },
  {
    id: 15,
    question: "“Addiction” atamasi ingliz tilidan tarjima qilinganda nimani anglatadi?",
    options: [
      "Moyillik, halokatli odat",
      "Faollik",
      "Mustaqillik",
      "Rivojlanish",
    ],
    correctAnswer: "Moyillik, halokatli odat",
  },
  {
    id: 16,
    question: "Lotincha “addictus” so‘zi nimani bildiradi?",
    options: [
      "Qarzi tufayli bog‘langan shaxs",
      "Erkin shaxs",
      "Bilimli shaxs",
      "Faol shaxs",
    ],
    correctAnswer: "Qarzi tufayli bog‘langan shaxs",
  },
  {
    id: 17,
    question: "Addiktiv xulq qanday xulq turiga kiradi?",
    options: [
      "Deviant xulq",
      "Normativ xulq",
      "Ijobiy xulq",
      "Ijtimoiy xulq",
    ],
    correctAnswer: "Deviant xulq",
  },
  {
    id: 18,
    question: "Addiktsiya obyekti nimalar bo‘lishi mumkin?",
    options: [
      "Har qanday faoliyat yoki obyekt",
      "Faqat moddalar",
      "Faqat pul",
      "Faqat o‘yin",
    ],
    correctAnswer: "Har qanday faoliyat yoki obyekt",
  },
  {
    id: 19,
    question: "Kimyoviy bog‘liqlikka qaysi misol kiradi?",
    options: [
      "Chekish",
      "Kompyuter o‘yinlari",
      "Sport",
      "Muloqot",
    ],
    correctAnswer: "Chekish",
  },
  {
    id: 20,
    question: "Gembling nimani anglatadi?",
    options: [
      "O‘yinga tobelik",
      "Ovqatlanish buzilishi",
      "Ishga tobelik",
      "Uyqu buzilishi",
    ],
    correctAnswer: "O‘yinga tobelik",
  },
  {
    id: 21,
    question: "Addiktiv xulq qanday jarayon sifatida rivojlanadi?",
    options: [
      "Uzluksiz shakllanish va rivojlanish jarayoni",
      "To‘satdan",
      "Bir martalik",
      "Tasodifiy",
    ],
    correctAnswer: "Uzluksiz shakllanish va rivojlanish jarayoni",
  },
  {
    id: 22,
    question: "Addiktiv ko‘rsatma nimani anglatadi?",
    options: [
      "Kognitiv, hissiy va axloqiy xususiyatlar yig‘indisini",
      "Faqat xulqni",
      "Faqat hissiyotni",
      "Faqat bilimni",
    ],
    correctAnswer: "Kognitiv, hissiy va axloqiy xususiyatlar yig‘indisini",
  },
  {
    id: 23,
    question: "Ratsionalizatsiya mexanizmi nimani anglatadi?",
    options: [
      "Addiktsiyani aqliy oqlash",
      "Xulqni inkor etish",
      "Xulqni yashirish",
      "Xulqni kuchaytirish",
    ],
    correctAnswer: "Addiktsiyani aqliy oqlash",
  },
  {
    id: 24,
    question: "“Magik tafakkur” qanday ko‘rinishda namoyon bo‘ladi?",
    options: [
      "Fantaziyalar va o‘zini buyuk his qilish",
      "Real fikrlash",
      "Mantiqiy fikrlash",
      "Passivlik",
    ],
    correctAnswer: "Fantaziyalar va o‘zini buyuk his qilish",
  },
  {
    id: 25,
    question: "Addiktiv shaxsda qanday psixologik o‘zgarish kuzatiladi?",
    options: [
      "Tanqidiylik pasayadi",
      "Tanqidiy fikrlash kuchayadi",
      "Faollik ortadi",
      "Mustaqillik oshadi",
    ],
    correctAnswer: "Tanqidiylik pasayadi",
  },
  {
    id: 26,
    question: "Aleksemitiya nimani bildiradi?",
    options: [
      "Hissiyotlarni ifoda eta olmaslik",
      "Fikrning kuchliligi",
      "Xotira kuchi",
      "Muloqot kuchi",
    ],
    correctAnswer: "Hissiyotlarni ifoda eta olmaslik",
  },
  {
    id: 27,
    question: "Addiktiv xulq shakllanishida oilaning roli qanday?",
    options: [
      "Muhim",
      "Ahamiyatsiz",
      "Faqat biologik",
      "Faqat iqtisodiy",
    ],
    correctAnswer: "Muhim",
  },
  {
    id: 28,
    question: "Gipyerstimulyatsiya nimani anglatadi?",
    options: [
      "Haddan tashqari ta’sir",
      "Faollikning pasayishi",
      "Faqat ijobiy holat",
      "Faqat dam olish",
    ],
    correctAnswer: "Haddan tashqari ta’sir",
  },
  {
    id: 29,
    question: "Addiktiv oilalarda rollar qanday bo‘ladi?",
    options: [
      "Buzilgan",
      "To‘g‘ri taqsimlangan",
      "Mustaqil",
      "Teng",
    ],
    correctAnswer: "Buzilgan",
  },
  {
    id: 30,
    question: "“Qurbon” roli nimani anglatadi?",
    options: [
      "O‘zini aybdor va azob chekayotgan deb his qilish",
      "Faollik",
      "Rahbarlik",
      "Mustaqillik",
    ],
    correctAnswer: "O‘zini aybdor va azob chekayotgan deb his qilish",
  },
  {
    id: 31,
    question: "Addiktiv oilada qanday hissiy holatlar ustun bo‘ladi?",
    options: [
      "Aybdorlik, umidsizlik",
      "Xursandchilik",
      "Faollik",
      "Motivatsiya",
    ],
    correctAnswer: "Aybdorlik, umidsizlik",
  },
  {
    id: 32,
    question: "Surunkali stress qanday oqibatga olib keladi?",
    options: [
      "Somatik va ruhiy kasalliklarning kuchayishiga",
      "Faqat dam olishga",
      "Faqat o‘qishga",
      "Faqat ijobiy natijaga",
    ],
    correctAnswer: "Somatik va ruhiy kasalliklarning kuchayishiga",
  },
  {
    id: 33,
    question: "Addiktiv xulqning eng xavfli oqibatlaridan biri qaysi?",
    options: [
      "Suitsidal xulq",
      "Faollik ortishi",
      "Qiziqish ortishi",
      "Mustaqillik oshishi",
    ],
    correctAnswer: "Suitsidal xulq",
  },
  {
    id: 34,
    question: "Suitsid tushunchasi nimani anglatadi?",
    options: [
      "Ongli ravishda o‘zini hayotdan mahrum etish",
      "Tasodifiy o‘lim",
      "Tabiiy o‘lim",
      "Kasallik natijasidagi o‘lim",
    ],
    correctAnswer: "Ongli ravishda o‘zini hayotdan mahrum etish",
  },
  {
    id: 35,
    question: "Quyidagilardan qaysi biri suitsidga kirmaydi?",
    options: [
      "Ehtiyotsizlik tufayli sodir bo‘lgan o‘lim",
      "Ongli ravishda o‘zini o‘ldirish",
      "O‘z joniga qasd qilish",
      "O‘zini hayotdan mahrum etish",
    ],
    correctAnswer: "Ehtiyotsizlik tufayli sodir bo‘lgan o‘lim",
  },
  {
    id: 36,
    question: "Suitsidal axloq qanday ta’riflanadi?",
    options: [
      "O‘zini hayotdan mahrum qilishga yo‘naltirilgan anglangan harakat",
      "Faqat hissiy holat",
      "Faqat tasodifiy xatti-harakat",
      "Faqat ijtimoiy muammo",
    ],
    correctAnswer: "O‘zini hayotdan mahrum qilishga yo‘naltirilgan anglangan harakat",
  },
  {
    id: 37,
    question: "Suitsidal harakat qaysi shakllardan iborat?",
    options: [
      "Suitsidal urinish va tugallangan suitsid",
      "Faqat fikrlar",
      "Faqat maqsadlar",
      "Faqat hissiyotlar",
    ],
    correctAnswer: "Suitsidal urinish va tugallangan suitsid",
  },
  {
    id: 38,
    question: "Suitsidal urinish nimani anglatadi?",
    options: [
      "O‘lim bilan tugamaydigan o‘z joniga qasd qilish harakati",
      "O‘lim bilan tugagan harakat",
      "Faqat tasavvur",
      "Faqat reja",
    ],
    correctAnswer: "O‘lim bilan tugamaydigan o‘z joniga qasd qilish harakati",
  },
  {
    id: 39,
    question: "Passiv suitsidal fikrlar qanday xarakterlanadi?",
    options: [
      "O‘z o‘limi haqida fantaziyalar va tasavvurlar bilan",
      "Aniq reja bilan",
      "Faqat tashqi harakat bilan",
      "Qaror qabul qilish bilan",
    ],
    correctAnswer: "O‘z o‘limi haqida fantaziyalar va tasavvurlar bilan",
  },
  {
    id: 40,
    question: "Suitsidal g‘oyalar qachon shakllanadi?",
    options: [
      "O‘z joniga qasd qilish rejasi ishlab chiqilganda",
      "Faqat hissiyot paytida",
      "Faqat tasodifiy fikrda",
      "Faqat tush ko‘rishda",
    ],
    correctAnswer: "O‘z joniga qasd qilish rejasi ishlab chiqilganda",
  },
  {
    id: 41,
    question: "E. Shneydman bo‘yicha “suitsidallik” nimani anglatadi?",
    options: [
      "O‘z-o‘zini o‘ldirishning individual xavfi",
      "Jamiyat xavfi",
      "Faqat ijtimoiy omil",
      "Faqat hissiy holat",
    ],
    correctAnswer: "O‘z-o‘zini o‘ldirishning individual xavfi",
  },
  {
    id: 42,
    question: "“Letallik” tushunchasi nimani bildiradi?",
    options: [
      "Shaxsning o‘z destruktivligi uchun xavf darajasi",
      "Faqat tashqi xavf",
      "Faqat biologik holat",
      "Faqat ruhiy holat",
    ],
    correctAnswer: "Shaxsning o‘z destruktivligi uchun xavf darajasi",
  },
  {
    id: 43,
    question: "A.G. Ambrumova bo‘yicha o‘z-o‘zini o‘ldirish qanday tasniflanadi?",
    options: [
      "Haqiqiy suitsid",
      "Tasodifiy harakat",
      "Faqat urinish",
      "Faqat fikr",
    ],
    correctAnswer: "Haqiqiy suitsid",
  },
  {
    id: 44,
    question: "Parasuitsid tushunchasi nimani anglatadi?",
    options: [
      "O‘limsiz o‘ziga zarar yetkazish",
      "O‘lim bilan tugagan harakat",
      "Faqat fikr",
      "Faqat reja",
    ],
    correctAnswer: "O‘limsiz o‘ziga zarar yetkazish",
  },
  {
    id: 45,
    question: "A.Ye. Lichko o‘smirlardagi suitsidal xulqni qanday turlarga ajratadi?",
    options: [
      "Namoyishkorona, affektiv va haqiqiy",
      "Ijobiy va salbiy",
      "Passiv va aktiv",
      "Ijtimoiy va biologik",
    ],
    correctAnswer: "Namoyishkorona, affektiv va haqiqiy",
  },
  {
    id: 46,
    question: "E. Dyurkgeym bo‘yicha “anomik suitsid” qachon yuzaga keladi?",
    options: [
      "Shaxs va muhit o‘rtasidagi keskin nomuvofiqlikda",
      "Baxtli hayotda",
      "Faqat kasallikda",
      "Faqat oilada",
    ],
    correctAnswer: "Shaxs va muhit o‘rtasidagi keskin nomuvofiqlikda",
  },
  {
    id: 47,
    question: "“Altruistik suitsid” nimani anglatadi?",
    options: [
      "Boshqalar yoki yuqori maqsad uchun o‘zini qurbon qilish",
      "Faqat o‘z manfaatini ko‘zlash",
      "Tasodifiy harakat",
      "Faqat stress",
    ],
    correctAnswer: "Boshqalar yoki yuqori maqsad uchun o‘zini qurbon qilish",
  },
  {
    id: 48,
    question: "V.A. Tixonenko bo‘yicha namoyishkorona-shantajli xulq nimani bildiradi?",
    options: [
      "O‘lim maqsadini ko‘rsatish orqali ta’sir o‘tkazish",
      "O‘limni istamaslik",
      "Tasodifiy harakat",
      "Faqat hissiy holat",
    ],
    correctAnswer: "O‘lim maqsadini ko‘rsatish orqali ta’sir o‘tkazish",
  },
  {
    id: 49,
    question: "A.G. Ambrumova tadqiqotiga ko‘ra suitsidal xulq qaysi jinsda ko‘proq uchraydi?",
    options: [
      "Qizlarda",
      "O‘g‘il bolalarda",
      "Teng darajada",
      "Keksalarda",
    ],
    correctAnswer: "Qizlarda",
  },
  {
    id: 50,
    question: "Amoralizm tushunchasi nimani anglatadi?",
    options: [
      "Axloqiy me’yorlarni buzish va inkor etish",
      "Axloqiy me’yorlarga qat’iy rioya qilish",
      "Faqat ijtimoiy faoliyat",
      "Faqat diniy qarash",
    ],
    correctAnswer: "Axloqiy me’yorlarni buzish va inkor etish",
  },
  {
    id: 51,
    question: "“Amoralizm” atamasidagi “a” qo‘shimchasi nimani bildiradi?",
    options: [
      "Inkori (yo‘qlik)",
      "Kuchaytirish",
      "Ko‘paytirish",
      "Ijobiylik",
    ],
    correctAnswer: "Inkori (yo‘qlik)",
  },
  {
    id: 52,
    question: "F. Fukuyama fikricha amoralizmning asosiy belgilaridan biri qaysi?",
    options: [
      "Jinoyatchilikning oshishi",
      "Ta’lim rivoji",
      "Texnologiyaning rivoji",
      "Sportning rivoji",
    ],
    correctAnswer: "Jinoyatchilikning oshishi",
  },
  {
    id: 53,
    question: "Oila inqirozining asosiy belgilaridan biri qaysi?",
    options: [
      "Nikohsiz tug‘ilishlarning ko‘payishi",
      "Nikohlarning ko‘payishi",
      "Ajralishlarning kamayishi",
      "Oilalarning mustahkamlanishi",
    ],
    correctAnswer: "Nikohsiz tug‘ilishlarning ko‘payishi",
  },
  {
    id: 54,
    question: "Depopulyatsiya nimani anglatadi?",
    options: [
      "Aholi sonining kamayishi",
      "Aholining tez o‘sishi",
      "Migratsiya",
      "Urbanizatsiya",
    ],
    correctAnswer: "Aholi sonining kamayishi",
  },
  {
    id: 55,
    question: "Ijtimoiy tarqoqlik qanday holatni ifodalaydi?",
    options: [
      "Yolg‘izlik va ajralishning ortishi",
      "Jamoaviylik kuchayishi",
      "Ijtimoiy integratsiya",
      "Hamkorlik",
    ],
    correctAnswer: "Yolg‘izlik va ajralishning ortishi",
  },
  {
    id: 56,
    question: "Fukuyama fikricha G‘arb jamiyatidagi muammolarning asosiy sababi nima?",
    options: [
      "Oila institutining inqirozi",
      "Texnologiya",
      "Iqtisodiyot",
      "Ta’lim tizimi",
    ],
    correctAnswer: "Oila institutining inqirozi",
  },
  {
    id: 57,
    question: "D. Vilkerson fikricha axloqiy buzuqlik nimada namoyon bo‘ladi?",
    options: [
      "Behayo kontentlarning keng tarqalishida",
      "Ta’lim rivojida",
      "Sport faoliyatida",
      "Iqtisodiy o‘sishda",
    ],
    correctAnswer: "Behayo kontentlarning keng tarqalishida",
  },
  {
    id: 58,
    question: "Amoralizmning yoshlar tarbiyasiga ta’siri qanday?",
    options: [
      "Salbiy ta’sir ko‘rsatadi",
      "Ijobiy ta’sir qiladi",
      "Hech qanday ta’sir qilmaydi",
      "Faqat bilimni oshiradi",
    ],
    correctAnswer: "Salbiy ta’sir ko‘rsatadi",
  },
  {
    id: 59,
    question: "Psixologik yordamning yetakchi yo‘nalishlari qaysilar?",
    options: [
      "Psixoprofilaktika va psixologik intervensiya",
      "Diagnostika va tahlil",
      "Ta’lim va nazorat",
      "Faqat terapiya",
    ],
    correctAnswer: "Psixoprofilaktika va psixologik intervensiya",
  },
  {
    id: 60,
    question: "Psixoprofilaktika nimaga qaratilgan?",
    options: [
      "Oldini olishga",
      "Davolashga",
      "Jazolashga",
      "Nazoratga",
    ],
    correctAnswer: "Oldini olishga",
  },
  {
    id: 61,
    question: "Psixologik intervensiya nimani anglatadi?",
    options: [
      "Muammoni bartaraf etish va korreksiya",
      "Diagnostika",
      "Faqat kuzatish",
      "Baholash",
    ],
    correctAnswer: "Muammoni bartaraf etish va korreksiya",
  },
  {
    id: 62,
    question: "Psixoprofilaktikaning ikkilamchi shakli nima?",
    options: [
      "Xabardor qilish",
      "Terapiya",
      "Jazolash",
      "Diagnostika",
    ],
    correctAnswer: "Xabardor qilish",
  },
  {
    id: 63,
    question: "Qo‘rqitishga asoslangan axborot qanday ta’sir ko‘rsatadi?",
    options: [
      "Xulqni o‘zgartirishga sust ta’sir qiladi",
      "Har doim ijobiy",
      "Juda samarali",
      "Har doim foydali",
    ],
    correctAnswer: "Xulqni o‘zgartirishga sust ta’sir qiladi",
  },
  {
    id: 64,
    question: "Psixoprofilaktikaning uchinchi shakli nima?",
    options: [
      "Ijtimoiy malakalarni o‘rgatish",
      "Jazolash",
      "Diagnostika",
      "Nazorat",
    ],
    correctAnswer: "Ijtimoiy malakalarni o‘rgatish",
  },
  {
    id: 65,
    question: "“Rezistentlik treningi” nimaga qaratilgan?",
    options: [
      "Salbiy ijtimoiy ta’sirlarga qarshi turishga",
      "Faollikni kamaytirishga",
      "Faqat bilim berishga",
      "Faqat dam olishga",
    ],
    correctAnswer: "Salbiy ijtimoiy ta’sirlarga qarshi turishga",
  },
  {
    id: 66,
    question: "Assertivlik treningi nimani rivojlantiradi?",
    options: [
      "Hissiyotlarni boshqarish va ifodalashni",
      "Passivlikni",
      "Faqat bilimni",
      "Faqat jismoniy kuchni",
    ],
    correctAnswer: "Hissiyotlarni boshqarish va ifodalashni",
  },
  {
    id: 67,
    question: "Hayotiy malakalar deganda nima tushuniladi?",
    options: [
      "Ijtimoiy va kommunikativ ko‘nikmalar",
      "Faqat nazariy bilimlar",
      "Faqat jismoniy faoliyat",
      "Faqat dam olish",
    ],
    correctAnswer: "Ijtimoiy va kommunikativ ko‘nikmalar",
  },
  {
    id: 68,
    question: "Deviant xulqni oldini olishda alternativ faoliyat nimani anglatadi?",
    options: [
      "Salbiy xulq o‘rniga ijobiy faoliyatni taklif qilish",
      "Jazolash",
      "Izolyatsiya",
      "Nazorat",
    ],
    correctAnswer: "Salbiy xulq o‘rniga ijobiy faoliyatni taklif qilish",
  },
  {
    id: 69,
    question: "Qaysi faoliyat alternativ sifatida ko‘rsatilgan?",
    options: [
      "Sport va ijodkorlik",
      "Jinoyat",
      "Passivlik",
      "Izolyatsiya",
    ],
    correctAnswer: "Sport va ijodkorlik",
  },
  {
    id: 70,
    question: "Sog‘lom turmush tarzining asosiy elementi qaysi?",
    options: [
      "Jismoniy faollik",
      "Noto‘g‘ri ovqatlanish",
      "Uyqusizlik",
      "Stress",
    ],
    correctAnswer: "Jismoniy faollik",
  },
  {
    id: 71,
    question: "Shaxsiy resurslarni faollashtirish nimani anglatadi?",
    options: [
      "Shaxs imkoniyatlarini rivojlantirish",
      "Passivlik",
      "Izolyatsiya",
      "Jazolash",
    ],
    correctAnswer: "Shaxs imkoniyatlarini rivojlantirish",
  },
  {
    id: 72,
    question: "Deviant xulq oqibatlarini minimallashtirish nimaga qaratilgan?",
    options: [
      "Salbiy oqibatlarni kamaytirishga",
      "Jazolashga",
      "Faqat nazoratga",
      "Faqat diagnostikaga",
    ],
    correctAnswer: "Salbiy oqibatlarni kamaytirishga",
  },
  {
    id: 73,
    question: "Psixoprofilaktika qanday shakllarda amalga oshiriladi?",
    options: [
      "Individual, oilaviy, guruhli",
      "Faqat individual",
      "Faqat guruhli",
      "Faqat oilaviy",
    ],
    correctAnswer: "Individual, oilaviy, guruhli",
  },
  {
    id: 74,
    question: "Psixoprofilaktikaning asosiy usullaridan biri qaysi?",
    options: [
      "Rolli o‘yinlar",
      "Jazolash",
      "Izolyatsiya",
      "Nazorat",
    ],
    correctAnswer: "Rolli o‘yinlar",
  },
  {
    id: 75,
    question: "Psixologik intervensiya nimaga qaratilgan?",
    options: [
      "Ijobiy o‘zgarishlarni rag‘batlantirish",
      "Diagnostika",
      "Jazolash",
      "Nazorat",
    ],
    correctAnswer: "Ijobiy o‘zgarishlarni rag‘batlantirish",
  },
  {
    id: 76,
    question: "Intervensiyaning asosiy qiyinchiligi nimada?",
    options: [
      "Shaxsning o‘zgarishga qarshiligi",
      "Bilim yetishmasligi",
      "Resurslarning ko‘pligi",
      "Faollikning ortishi",
    ],
    correctAnswer: "Shaxsning o‘zgarishga qarshiligi",
  },
  {
    id: 77,
    question: "Psixologik intervensiyaning asosiy vazifasi qaysi?",
    options: [
      "Moslashuvni rivojlantirish",
      "Jazolash",
      "Nazorat",
      "Izolyatsiya",
    ],
    correctAnswer: "Moslashuvni rivojlantirish",
  },
  {
    id: 78,
    question: "Psixoterapiyaning asosiy yo‘nalishlari qaysilar?",
    options: [
      "Psixoanalitik, kognitiv-axloqiy, gumanistik",
      "Biologik",
      "Faqat ijtimoiy",
      "Faqat pedagogik",
    ],
    correctAnswer: "Psixoanalitik, kognitiv-axloqiy, gumanistik",
  },
  {
    id: 79,
    question: "Psixologik yordam samaradorligi nimaga qarab baholanadi?",
    options: [
      "Xulqdagi va subyektiv o‘zgarishlarga",
      "Faqat nazariy bilimga",
      "Faqat testga",
      "Faqat vaqtga",
    ],
    correctAnswer: "Xulqdagi va subyektiv o‘zgarishlarga",
  },
  {
    id: 80,
    question: "Ijtimoiy moslashuvning oshishi nimani bildiradi?",
    options: [
      "Shaxs rivojlanishi va moslashuvi",
      "Izolyatsiya",
      "Faollikning pasayishi",
      "Stressning ortishi",
    ],
    correctAnswer: "Shaxs rivojlanishi va moslashuvi",
  },
  {
    id: 81,
    question: "Psixoprofilaktikaning asosiy tamoyillaridan biri qaysi?",
    options: [
      "Majmuaviylik",
      "Izolyatsiya",
      "Jazolash",
      "Passivlik",
    ],
    correctAnswer: "Majmuaviylik",
  },
  {
    id: 82,
    question: "Majmuaviylik tamoyili nimani anglatadi?",
    options: [
      "Shaxs va muhitga kompleks ta’sir ko‘rsatish",
      "Faqat individual ish",
      "Faqat nazorat",
      "Faqat terapiya",
    ],
    correctAnswer: "Shaxs va muhitga kompleks ta’sir ko‘rsatish",
  },
  {
    id: 83,
    question: "Manzillilik tamoyili nimani hisobga oladi?",
    options: [
      "Yosh, jins va ijtimoiy xususiyatlarni",
      "Faqat yoshni",
      "Faqat iqtisodiy holatni",
      "Faqat muhitni",
    ],
    correctAnswer: "Yosh, jins va ijtimoiy xususiyatlarni",
  },
  {
    id: 84,
    question: "Axborotning ijobiyligi tamoyili nimani anglatadi?",
    options: [
      "Ijobiy va konstruktiv ma’lumot berishni",
      "Qo‘rqitishga asoslanadi",
      "Faqat jazolashni",
      "Faqat statistikani",
    ],
    correctAnswer: "Ijobiy va konstruktiv ma’lumot berishni",
  },
  {
    id: 85,
    question: "Shaxsiy manfaatdorlik tamoyili nimaga xizmat qiladi?",
    options: [
      "Ishtirokchilarning faol ishtirokiga",
      "Passivlikka",
      "Nazoratga",
      "Izolyatsiyaga",
    ],
    correctAnswer: "Ishtirokchilarning faol ishtirokiga",
  },
  {
    id: 86,
    question: "“Kelajakka yo‘naltirilganlik” tamoyili nimani bildiradi?",
    options: [
      "Xulq oqibatlarini oldindan baholash",
      "O‘tmishni o‘rganish",
      "Faqat hozirgi holat",
      "Nazorat",
    ],
    correctAnswer: "Xulq oqibatlarini oldindan baholash",
  },
  {
    id: 87,
    question: "Psixologik intervensiyada motivatsiya nima uchun muhim?",
    options: [
      "O‘zgarishlarni boshlash uchun",
      "Nazorat uchun",
      "Jazolash uchun",
      "Diagnostika uchun",
    ],
    correctAnswer: "O‘zgarishlarni boshlash uchun",
  },
  {
    id: 88,
    question: "Deviant xulqli shaxs yordamga qachon murojaat qiladi?",
    options: [
      "Muammo kuchayganda yoki zarar sezilganda",
      "Har doim",
      "Faqat majburan",
      "Faqat boshqalarga",
    ],
    correctAnswer: "Muammo kuchayganda yoki zarar sezilganda",
  },
  {
    id: 89,
    question: "Psixologik intervensiyaning asosiy mezoni nima?",
    options: [
      "Ijtimoiy moslashuv darajasi",
      "Nazorat",
      "Jazolash",
      "Statistik natija",
    ],
    correctAnswer: "Ijtimoiy moslashuv darajasi",
  },
  {
    id: 90,
    question: "Psixologik yordamda maslahat va terapiya o‘rtasidagi munosabat qanday?",
    options: [
      "Bir-birini to‘ldiradi",
      "Bir-biriga zid",
      "Mustaqil",
      "Faqat terapiya muhim",
    ],
    correctAnswer: "Bir-birini to‘ldiradi",
  },
  {
    id: 91,
    question: "Psixokorreksion ishlarning asosiy maqsadi nima?",
    options: [
      "Xulqni tuzatish va moslashtirish",
      "Jazolash",
      "Nazorat qilish",
      "Izolyatsiya",
    ],
    correctAnswer: "Xulqni tuzatish va moslashtirish",
  },
  {
    id: 92,
    question: "Eydemiller va Yustiskiy nechta asosiy maqsadni ajratgan?",
    options: [
      "3 ta",
      "2 ta",
      "4 ta",
      "5 ta",
    ],
    correctAnswer: "3 ta",
  },
  {
    id: 93,
    question: "Birinchi maqsad nimaga qaratilgan?",
    options: [
      "Qiyin vaziyatlarni tanishga o‘rgatishga",
      "Jazolashga",
      "Nazoratga",
      "Izolyatsiyaga",
    ],
    correctAnswer: "Qiyin vaziyatlarni tanishga o‘rgatishga",
  },
  {
    id: 94,
    question: "Ikkinchi maqsad nimani anglatadi?",
    options: [
      "Vaziyatni obyektiv baholash",
      "Vaziyatni inkor etish",
      "Jazolash",
      "Passivlik",
    ],
    correctAnswer: "Vaziyatni obyektiv baholash",
  },
  {
    id: 95,
    question: "Uchinchi maqsad nimaga qaratilgan?",
    options: [
      "Xulq variantlarini kengaytirishga",
      "Xulqni cheklashga",
      "Nazoratga",
      "Jazolashga",
    ],
    correctAnswer: "Xulq variantlarini kengaytirishga",
  },
  {
    id: 96,
    question: "Psixokorreksiya qaysi darajada amalga oshirilishi kerak?",
    options: [
      "Real xulq-atvor darajasida",
      "Faqat nazariy",
      "Faqat suhbat orqali",
      "Faqat test orqali",
    ],
    correctAnswer: "Real xulq-atvor darajasida",
  },
  {
    id: 97,
    question: "Guruhiy o‘yinlarning maqsadi nima?",
    options: [
      "Xulqni o‘zgartirish va tahlil qilish",
      "O‘yin uchun",
      "Dam olish",
      "Jazolash",
    ],
    correctAnswer: "Xulqni o‘zgartirish va tahlil qilish",
  },
  {
    id: 98,
    question: "Psixokorreksiya samaradorligi nimaga bog‘liq?",
    options: [
      "O‘smirning o‘zgarishga tayyorligiga",
      "O‘qituvchiga",
      "Nazoratga",
      "Jazoga",
    ],
    correctAnswer: "O‘smirning o‘zgarishga tayyorligiga",
  },
  {
    id: 99,
    question: "Aksentuatsiyali o‘smirlar bilan ishlashda nima muhim?",
    options: [
      "Individual yondashuv",
      "Jazolash",
      "Nazorat",
      "Izolyatsiya",
    ],
    correctAnswer: "Individual yondashuv",
  },
  {
    id: 100,
    question: "Profilaktikaning asosiy maqsadi nima?",
    options: [
      "Nerv tizimi chidamliligini oshirish",
      "Jazolash",
      "Nazorat",
      "Izolyatsiya",
    ],
    correctAnswer: "Nerv tizimi chidamliligini oshirish",
  },
  {
    id: 101,
    question: "Profilaktika kimlar tomonidan amalga oshiriladi?",
    options: [
      "Psixolog, o‘qituvchi va ota-ona",
      "Faqat psixolog",
      "Faqat ota-ona",
      "Faqat o‘qituvchi",
    ],
    correctAnswer: "Psixolog, o‘qituvchi va ota-ona",
  },
  {
    id: 102,
    question: "Psixoprofilaktikada qaysi omil muhim?",
    options: [
      "To‘g‘ri dam olish va mehnat",
      "Passivlik",
      "Jazolash",
      "Izolyatsiya",
    ],
    correctAnswer: "To‘g‘ri dam olish va mehnat",
  },
  {
    id: 103,
    question: "O‘smir bilan ishlashda qaysi prinsip muhim?",
    options: [
      "Psixik himoya",
      "Jazolash",
      "Nazorat",
      "Izolyatsiya",
    ],
    correctAnswer: "Psixik himoya",
  },
  {
    id: 104,
    question: "Xulqni o‘zgartirish nimani talab qiladi?",
    options: [
      "Munosabatlar tizimini qayta ko‘rishni",
      "Faqat suhbatni",
      "Jazoni",
      "Izolyatsiyani",
    ],
    correctAnswer: "Munosabatlar tizimini qayta ko‘rishni",
  },
  {
    id: 105,
    question: "Egoistik xususiyatlar nimadan kelib chiqadi?",
    options: [
      "Haddan tashqari erkalashdan",
      "Qattiq tarbiyadan",
      "Jazodan",
      "Nazoratdan",
    ],
    correctAnswer: "Haddan tashqari erkalashdan",
  },
  {
    id: 106,
    question: "Pubertat davrida qanday o‘zgarishlar yuz beradi?",
    options: [
      "Jismoniy va psixik o‘zgarishlar",
      "Faqat jismoniy",
      "Faqat ruhiy",
      "Faqat ijtimoiy",
    ],
    correctAnswer: "Jismoniy va psixik o‘zgarishlar",
  },
  {
    id: 107,
    question: "O‘smirning rivojlanishida asosiy jarayon nima?",
    options: [
      "Ijtimoiylashuv",
      "Jazolash",
      "Nazorat",
      "Izolyatsiya",
    ],
    correctAnswer: "Ijtimoiylashuv",
  },
  {
    id: 108,
    question: "Psixokorreksiya qanday bosqichda boshlanishi kerak?",
    options: [
      "Oddiy vazifalardan",
      "Murakkab vazifalardan",
      "Jazodan",
      "Nazoratdan",
    ],
    correctAnswer: "Oddiy vazifalardan",
  },
  {
    id: 109,
    question: "O‘smir xulqiga ta’sir qiluvchi asosiy omil qaysi?",
    options: [
      "Ijtimoiy muhit va psixik rivojlanish",
      "Faqat biologik",
      "Faqat iqtisodiy",
      "Faqat jismoniy",
    ],
    correctAnswer: "Ijtimoiy muhit va psixik rivojlanish",
  },
  {
    id: 110,
    question: "Jamiyatda qabul qilingan axloq va me’yorlardan chetga chiqadigan xulq qanday ataladi?",
    options: [
      "Deviant xulq",
      "Adaptiv xulq",
      "Motivatsion xulq",
      "Kognitiv xulq",
    ],
    correctAnswer: "Deviant xulq",
  },
  {
    id: 111,
    question: "Huquqiy me’yorlarni buzish bilan bog‘liq deviant xulq turi qanday ataladi?",
    options: [
      "Delinkvent xulq",
      "Addiktiv xulq",
      "Suitsidal xulq",
      "Konform xulq",
    ],
    correctAnswer: "Delinkvent xulq",
  },
  {
    id: 112,
    question: "Spirtli ichimlik, giyohvandlik yoki internetga qaramlik bilan bog‘liq xulq turi:",
    options: [
      "Addiktiv xulq",
      "Prosotsial xulq",
      "Altruistik xulq",
      "Normativ xulq",
    ],
    correctAnswer: "Addiktiv xulq",
  },
  {
    id: 113,
    question: "Biologik omillarga nimalar kiradi?",
    options: [
      "Irsiyat, tug‘ma nuqsonlar.",
      "Tarbiya, ta’lim",
      "Ijtimoiy muhit",
      "Oilaviy munosabatlar",
    ],
    correctAnswer: "Irsiyat, tug‘ma nuqsonlar.",
  },
  {
    id: 114,
    question: "Psixologik omillarga nimalar kiradi?",
    options: [
      "Shaxsiy xususiyatlar, ruhiy travmalar",
      "Irsiyat, tug‘ma nuqsonlar",
      "Ijtimoiy muhit",
      "Do‘stlar davrasi",
    ],
    correctAnswer: "Shaxsiy xususiyatlar, ruhiy travmalar",
  },
  {
    id: 115,
    question: "Oilaviy omillarga nimalar kiradi?",
    options: [
      "Tarbiya usullari, ota-onalar, atrofdagilar munosabati",
      "Irsiyat, tug‘ma nuqsonlar",
      "Shaxsiy xususiyatlar, ruhiy travmalar",
      "Do‘stlar davrasi",
    ],
    correctAnswer: "Tarbiya usullari, ota-onalar, atrofdagilar munosabati",
  },
  {
    id: 116,
    question: "Agressiya nima?",
    options: [
      "Boshqalarga zarar yetkazish",
      "Ijtimoiy faollik",
      "Ruhiy sog‘lomlik",
      "Faol hayot tarzi.",
    ],
    correctAnswer: "Boshqalarga zarar yetkazish",
  },
  {
    id: 117,
    question: "Zo‘ravonlik nima?",
    options: [
      "imdir ustidan hokimiyat o'rnatish, zarar yetkazish",
      "Ijodiy faollik",
      "Himoya reaksiyasi",
      "O‘z-o‘zini tarbiyalash",
    ],
    correctAnswer: "imdir ustidan hokimiyat o'rnatish, zarar yetkazish",
  },
  {
    id: 118,
    question: "Agressiyaning sabablari nima?",
    options: [
      "Frustratsiya, o‘rganish, ijtimoiy ta’sir",
      "Shaxsiy xususiyatlar, ruhiy travmalar",
      "Tarbiya, ta’lim.",
      "Oilaviy munosabatlar",
    ],
    correctAnswer: "Frustratsiya, o‘rganish, ijtimoiy ta’sir",
  },
  {
    id: 119,
    question: "Zo‘ravonlikning shakllari",
    options: [
      "Jismoniy, ruhiy, iqtisodiy, jinsiy",
      "Irsiyat, tug‘ma nuqsonlar",
      "Shaxsiy xususiyatlar, ruhiy travmalar",
      "Tarbiya, ta’lim",
    ],
    correctAnswer: "Jismoniy, ruhiy, iqtisodiy, jinsiy",
  },
  {
    id: 120,
    question: "Agressiya va zo‘ravonlik profilaktikasi nimalarni o‘z ichiga oladi?",
    options: [
      "Ta’lim, tarbiya, psixologik yordam, xuquqiy, ijtimoiy ko‘mak.",
      "Faqat jazolash",
      "Faqat nazorat",
      "faqat davolash.",
    ],
    correctAnswer: "Ta’lim, tarbiya, psixologik yordam, xuquqiy, ijtimoiy ko‘mak.",
  },
  {
    id: 121,
    question: "Giyohvandlik nima?",
    options: [
      "psixoaktiv moddalarga qaramlik.",
      "Ijtimoiy faollik",
      "Ruhiy nosog‘lomlik",
      "sust hayot tarzi",
    ],
    correctAnswer: "psixoaktiv moddalarga qaramlik.",
  },
  {
    id: 122,
    question: "Alkogolizm nima?",
    options: [
      "spirtli ichimliklarga qaramlik",
      "Faqat dam olishga",
      "Salbiy ijtimoiy ta’sirlarga qarshi turishga",
      "ruhiy nosog‘lomlik",
    ],
    correctAnswer: "spirtli ichimliklarga qaramlik",
  },
  {
    id: 123,
    question: "Giyohvandlik va alkogolizmning sabablari nimada?",
    options: [
      "Biologik, psixologik, ijtimoiy omillar",
      "Faqat irsiyat.",
      "Faqat tarbiya",
      "faqat ijtimoiy muhit",
    ],
    correctAnswer: "Biologik, psixologik, ijtimoiy omillar",
  },
  {
    id: 124,
    question: "Giyohvandlik va alkogolizmning oqibatlari ?",
    options: [
      "Sog‘liqning yomonlashuvi, ijtimoiy muammolar, jinoyatchilik",
      "Sog‘lom turmush tarzi",
      "Ruhiy nosog‘lomlik",
      "sust hayot tarzi",
    ],
    correctAnswer: "Sog‘liqning yomonlashuvi, ijtimoiy muammolar, jinoyatchilik",
  },
  {
    id: 125,
    question: "Suisidning sabablari nima?",
    options: [
      "Ruhiy kasalliklar, stress, ijtimoiy izolyasiya",
      "Faqat irsiyat",
      "Faqat tarbiya",
      "faqat ijtimoiy muhit",
    ],
    correctAnswer: "Ruhiy kasalliklar, stress, ijtimoiy izolyasiya",
  },
  {
    id: 126,
    question: "Delinkvent xulqning sabablari nima?",
    options: [
      "Ijtimoiy tengsizlik, oilaviy muammolar, ta’limning yetishmasligi.",
      "Faqat irsiyat",
      "Faqat tarbiya",
      "Faqat ijtimoiy muhit",
    ],
    correctAnswer: "Ijtimoiy tengsizlik, oilaviy muammolar, ta’limning yetishmasligi.",
  },
  {
    id: 127,
    question: "Delinkvent xulqning shakllari nima?",
    options: [
      "O‘g‘rilik, bezorilik, vandalizm, talonchilik",
      "Sog‘lom turmush tarzi",
      "Ruhiy nosog‘lomlik",
      "ijtimoiy ziddiyatlar",
    ],
    correctAnswer: "O‘g‘rilik, bezorilik, vandalizm, talonchilik",
  },
  {
    id: 128,
    question: "Delinkvent xulq profilaktikasi nimalarni o‘z ichiga oladi?",
    options: [
      "Huquqiy ta’lim, ijtimoiy ko‘mak",
      "Faqat jazolash",
      "Faqat tarbiyalash",
      "Faqat davolash",
    ],
    correctAnswer: "Huquqiy ta’lim, ijtimoiy ko‘mak",
  },
  {
    id: 129,
    question: "Virtual qaramlik nima?",
    options: [
      "Internet, o‘yinlar, ijtimoiy tarmoqlarga qaramlik",
      "TV ga qaramlik",
      "Ruhiy nosog‘lomlik",
      "Faol hayot tarzi",
    ],
    correctAnswer: "Internet, o‘yinlar, ijtimoiy tarmoqlarga qaramlik",
  },
  {
    id: 130,
    question: "Virtual qaramlikning sabablari nima?",
    options: [
      "Zerikish, ijtimoiy muammolar, o‘ziga ishonchning pastligi.",
      "Faqat irsiyat",
      "oilaviy ziddiyatlar",
      "Faqat ijtimoiy muhit",
    ],
    correctAnswer: "Zerikish, ijtimoiy muammolar, o‘ziga ishonchning pastligi.",
  },
  {
    id: 131,
    question: "Submadaniyat nima?",
    options: [
      "Umumiy madaniyatning bir qismi.",
      "Sog'lom turmush tarzi",
      "Ijtimoiy faollik",
      "Ruhiy sog'lomlik",
    ],
    correctAnswer: "Umumiy madaniyatning bir qismi.",
  },
  {
    id: 132,
    question: "O'smirlar submadaniyatining sabablari nima?",
    options: [
      "O'ziga xoslikni izlash, tengdoshlar bilan muloqot qilish, hayotga qiziqish",
      "boshqa madaniyatga qiziqish",
      "boshqa dinlarga qiziqish",
      "berqarorlik, oilasidan qochish",
    ],
    correctAnswer: "O'ziga xoslikni izlash, tengdoshlar bilan muloqot qilish, hayotga qiziqish",
  },
  {
    id: 133,
    question: "Qaysi submadaniyatlar jamiyatga salbiy ta'sir ko'rsatishi mumkin?",
    options: [
      "poyezdda sayohat qilish, \"Columbiners\" (ommaviy qotillik izdoshlari), futbol janglari",
      "Ijtimoiy harakatlar",
      "Ko'ngillilik",
      "Madaniy tadbirlar",
    ],
    correctAnswer: "poyezdda sayohat qilish, \"Columbiners\" (ommaviy qotillik izdoshlari), futbol janglari",
  },
  {
    id: 134,
    question: "Salbiy submadaniyatlarning oldini olish nimalarni o'z ichiga oladi",
    options: [
      "Ta'lim, ma'rifat, ijtimoiy faollik, sog'lom turmush tarziga targ'ib",
      "Faqat jazolash.",
      "Faqat nazorat qilish.",
      "Faqat tarbiyalash",
    ],
    correctAnswer: "Ta'lim, ma'rifat, ijtimoiy faollik, sog'lom turmush tarziga targ'ib",
  },
  {
    id: 135,
    question: "Ruhiy salomatlik nima?",
    options: [
      "Insonning his-tuyg‘ulari, fikrlari va xatti-harakatlari bilan bog‘liq bo‘lgan umumiy farovonlik holati",
      "Faqat jismoniy salomatlik",
      "Faqat moddiy farovonlik.",
      "Faqat ijtimoiy munosabatlar",
    ],
    correctAnswer: "Insonning his-tuyg‘ulari, fikrlari va xatti-harakatlari bilan bog‘liq bo‘lgan umumiy farovonlik holati",
  },
  {
    id: 136,
    question: "Stressni boshqarishning eng samarali usullaridan biri nima?",
    options: [
      "Regulyar jismoniy mashqlar",
      "Faqat ishlash va dam olmaslik",
      "Ko‘p miqdorda kofein iste’mol qilish.",
      "Muammolarni e’tiborsiz qoldirish.",
    ],
    correctAnswer: "Regulyar jismoniy mashqlar",
  },
  {
    id: 137,
    question: "Ruhiy jarohat nima?",
    options: [
      "Insonning ruhiy holatiga ta’sir qiluvchi chuqur iz qoldiruvchi voqea",
      "Hech qanday ta’sir ko‘rsatmaydigan oddiy voqea.",
      "Faqat yomon tushlar.",
      "Faqat qo‘rquv",
    ],
    correctAnswer: "Insonning ruhiy holatiga ta’sir qiluvchi chuqur iz qoldiruvchi voqea",
  },
  {
    id: 138,
    question: "Jinoyatchilik xulq-atvorining biologik determinatsiyasiga asoslangan yondashuvning vakili bo‘lgan shifokor-psixiatr va antropolog",
    options: [
      "Ch. Lombrozo",
      "K.Yung",
      "E.Fromm",
      "Ch.Chaplin",
    ],
    correctAnswer: "Ch. Lombrozo",
  },
  {
    id: 139,
    question: "Bixeviorizm yo‘nalishida deviant xulqning asosiy sababi nima deb hisoblanadi?",
    options: [
      "Noto‘g‘ri o‘rganilgan va mustahkamlangan xulq-atvor shakllari",
      "Irsiy moyillik",
      "Jamiyatdagi iqtisodiy tengsizlik",
      "Ekzistensial bo‘shliq",
    ],
    correctAnswer: "Noto‘g‘ri o‘rganilgan va mustahkamlangan xulq-atvor shakllari",
  },
  {
    id: 140,
    question: "Kognitiv terapiyada deviant xulqni tuzatish uchun nimaga e’tibor qaratiladi?",
    options: [
      "Salbiy fikrlash va noto‘g‘ri e’tiqodlarni o‘zgartirishga",
      "Gipnoz holatiga tushirishga",
      "Dori-darmonlar bilan davolashga",
      "Mushaklarni bo‘shashtirishga",
    ],
    correctAnswer: "Salbiy fikrlash va noto‘g‘ri e’tiqodlarni o‘zgartirishga",
  },
  {
    id: 141,
    question: "Psixoanalitik yondashuvda (Z. Freyd) deviant xulqning ildizi qayerda deb ko‘riladi?",
    options: [
      "Ong ostidagi ichki nizolar va bostirilgan mayllarda",
      "Vitaminlar yetishmovchiligida",
      "Tashqi muhit ta’sirida",
      "Odamning kelajakdagi rejalarida",
    ],
    correctAnswer: "Ong ostidagi ichki nizolar va bostirilgan mayllarda",
  },
  {
    id: 142,
    question: "Gumanistik psixoterapiyaning (K. Rojers)deviant xulq bilan ishkashda asosiy maqsadi nima?",
    options: [
      "Shaxsni o‘zini-o‘zi anglashi va qabul qilishiga ko‘maklashish",
      "Jazolash orqali tarbiyalash",
      "Shartli reflekslar hosil qilish",
      "Eski xotiralarni o‘chirib tashlash",
    ],
    correctAnswer: "Shaxsni o‘zini-o‘zi anglashi va qabul qilishiga ko‘maklashish",
  },
  {
    id: 143,
    question: "Geshtalt-terapiyada deviant xulqli mijoz bilan ishlashda qaysi tamoyil muhim?",
    options: [
      "\"Shu yerda va hozir\" (Here and Now)",
      "\"Kelajakni bashorat qilish\"",
      "\"Boshqalarni ayblash\"",
      "\"Faqat dori ichish\"",
    ],
    correctAnswer: "\"Shu yerda va hozir\" (Here and Now)",
  },
  {
    id: 144,
    question: "Art-terapiya deviant xulqli bolalarda qanday maqsadda qo‘llaniladi",
    options: [
      "Ichki agressiya va hissiyotlarni san’at orqali ifodalash (sublimatsiya) uchun",
      "Majburiy mehnat sifatida",
      "Maktab baholarini tuzatish uchun",
      "Ko‘z nurini yaxshilash uchun",
    ],
    correctAnswer: "Ichki agressiya va hissiyotlarni san’at orqali ifodalash (sublimatsiya) uchun",
  },
  {
    id: 145,
    question: "Erik Bernning \"Transakt tahlil\" nazariyasiga ko‘ra, shaxsning qaysi holati deviant xulqda ko‘proq namoyon bo‘ladi?",
    options: [
      "Moslashgan Bola (Adapted Child) yoki Is’yonkor Bola",
      "Ehtiyotkor Ota-ona",
      "Sog‘lom Katta (Adult)",
      "Ijodkor shaxs",
    ],
    correctAnswer: "Moslashgan Bola (Adapted Child) yoki Is’yonkor Bola",
  },
  {
    id: 146,
    question: "Autodestruktiv xulq-atvorga nima kiradi?",
    options: [
      "Suisidal moyillik va o‘z-o‘ziga shikast yetkazish",
      "Sport bilan shug‘ullanish",
      "Ko‘p uxlash",
      "Rahbarlik qilish",
    ],
    correctAnswer: "Suisidal moyillik va o‘z-o‘ziga shikast yetkazish",
  },
  {
    id: 147,
    question: "Oiladagi qaysi omil deviant xulq shakllanishiga sabab bo‘ladi?",
    options: [
      "Giperproteksiya (haddan tashqari g‘amxo‘rlik) yoki gipoproteksiya (e’tiborsizlik)",
      "Irsiyat",
      "Birgalikda ovqatlanish va sayohat",
      "Kitobxonlik an’anasi",
    ],
    correctAnswer: "Giperproteksiya (haddan tashqari g‘amxo‘rlik) yoki gipoproteksiya (e’tiborsizlik)",
  },
  {
    id: 148,
    question: "Resosializatsiya nima?",
    options: [
      "Ijtimoiy me’yorlarni qayta o‘rganish va jamiyatga moslashish jarayoni",
      "Insonni qamoqqa olish",
      "Xotirani yo‘qotish",
      "Chet tilini o‘rganish",
    ],
    correctAnswer: "Ijtimoiy me’yorlarni qayta o‘rganish va jamiyatga moslashish jarayoni",
  },
  {
    id: 149,
    question: "Psixologik yordamning yetakchi yo‘nalishlari qaysilar?",
    options: [
      "Psixoprofilaktika va psixologik intervensiya",
      "Diagnostika va tahlil",
      "Ta’lim va nazorat",
      "Faqat terapiya",
    ],
    correctAnswer: "Psixoprofilaktika va psixologik intervensiya",
  },
  {
    id: 150,
    question: "Psixoprofilaktika nimaga qaratilgan?",
    options: [
      "Oldini olishga",
      "Davolashga",
      "Jazolashga",
      "Nazoratga",
    ],
    correctAnswer: "Oldini olishga",
  },
];
