import type { Question } from "@/lib/types";

// Source: Proyektiv_Psixologiya_150_Test_Word_jadval.docx
// The correct answer can be listed in any position; options are shuffled in the test.
export const questions: Question[] = [
  {
    id: 1,
    question: "Proyektiv psixologiyada 'proyeksiya' atamasini psixologik diagnostika kontekstida dastlab kim ilmiy muomalaga kiritgan?",
    options: [
      "L. Frank",
      "Z. Freyd",
      "G. Rorshax",
      "G. Myurrey",
    ],
    correctAnswer: "L. Frank",
  },
  {
    id: 2,
    question: "Z. Freyd ta'limotida proyeksiyaning asosiy mohiyati nimadan iborat?",
    options: [
      "Idrok qilinayotgan obyektlarning fazoviy munosabatlarini xotirada tiklash jarayoni",
      "Shaxsning o'ziga yoqmagan xislat va mayllarini ongsiz ravishda boshqalarga ko'chirish himoya mexanizmi",
      "Mantiqiy tafakkur vositasida muammoli vaziyatlarni tahlil qilish usuli",
      "Ijtimoiy rollarni ongli ravishda o'zlashtirish va ularni namoyon etish mexanizmi",
    ],
    correctAnswer: "Shaxsning o'ziga yoqmagan xislat va mayllarini ongsiz ravishda boshqalarga ko'chirish himoya mexanizmi",
  },
  {
    id: 3,
    question: "Proyektiv metodlarning psixometrik metodlardan (so'rovnomalardan) tub farqi nimada?",
    options: [
      "Test topshiruvchining o'zini o'zi ongli baholashiga to'liq tayanishi",
      "Faqat miqdoriy ko'rsatkichlarga asoslanishi va tezkor o'tkazilishi",
      "Rag'batlantiruvchi materialning noaniqligi (zaif tuzilganligi) va javoblarning erkinligi",
      "Natijalarni talqin qilishda mutaxassis malakasi talab etilmasligi",
    ],
    correctAnswer: "Rag'batlantiruvchi materialning noaniqligi (zaif tuzilganligi) va javoblarning erkinligi",
  },
  {
    id: 4,
    question: "Proyektiv metodologiyada rag'bat (stimul) materialining qaysi xususiyati shaxsning ichki dunyosini ochishga yordam beradi?",
    options: [
      "To'g'ridan-to'g'ri to'g'ri yoki noto'g'ri javoblarni talab qilishi",
      "Yuqori darajada standartlashtirilganligi va qat'iyligi",
      "Faqat verbal (matnli) xarakterga ega ekanligi",
      "Strukturallashmaganligi (noaniqligi va ko'p ma'noliligi)",
    ],
    correctAnswer: "Strukturallashmaganligi (noaniqligi va ko'p ma'noliligi)",
  },
  {
    id: 5,
    question: "L. Frank tasnifiga ko'ra, proyektiv metodlarning qaysi guruhiga Rorshax testi kiritiladi?",
    options: [
      "Konstitutiv metodlar",
      "Konstruktiv metodlar",
      "Interpretativ metodlar",
      "Katartik metodlar",
    ],
    correctAnswer: "Konstitutiv metodlar",
  },
  {
    id: 6,
    question: "Proyektiv metodlarda 'proyektiv gipoteza'ning mazmuni nimani anglatadi?",
    options: [
      "Inson doimo o'z xatti-harakatlarini ongli rejalashtirishga intiladi",
      "Har qanday noaniq stimulga berilgan javob shaxsning ichki ehtiyojlari va individual xususiyatlarini aks ettiradi",
      "Diagnostika natijalari faqat tashqi muhit omillariga bog'liq bo'ladi",
      "Sinovchi o'z taxminlarini sinovdan o'tuvchiga singdirishi lozim",
    ],
    correctAnswer: "Har qanday noaniq stimulga berilgan javob shaxsning ichki ehtiyojlari va individual xususiyatlarini aks ettiradi",
  },
  {
    id: 7,
    question: "Proyektiv metodlarning asosiy afzalligi qaysi javobda to'g'ri ko'rsatilgan?",
    options: [
      "Javoblarning qat'iy to'g'ri yoki noto'g'riligi bilan baholanishi",
      "Matematik-statistik ishlov berishning mutlaq osonligi",
      "Ijtimoiy mabullik (namoyishkorona yaxshi ko'rinish) tendensiyasini va ongli himoyani chetlab o'tishi",
      "Mutaxassisning subyektiv fikridan butunlay xoli ekanligi",
    ],
    correctAnswer: "Ijtimoiy mabullik (namoyishkorona yaxshi ko'rinish) tendensiyasini va ongli himoyani chetlab o'tishi",
  },
  {
    id: 8,
    question: "Proyektiv metodlarning asosiy kamchiligi va cheklovi nimada namoyon bo'ladi?",
    options: [
      "Bolalar va o'smirlar bilan ishlashda mutlaqo samarasizligi",
      "Sinovdan o'tuvchining vaqtini haddan tashqari kam egallashi",
      "Klinik amaliyotda chuqur holatlarni aniqlashga yaroqsizligi",
      "Natijalarni talqin qilishda interpretator subyektivizmining yuqoriligi va standartlashtirishning qiyinligi",
    ],
    correctAnswer: "Natijalarni talqin qilishda interpretator subyektivizmining yuqoriligi va standartlashtirishning qiyinligi",
  },
  {
    id: 9,
    question: "Proyektiv testlarda interpretatsiyaning subyektivligini minimallashtirishning eng samarali usuli qaysi?",
    options: [
      "Standartlashtirilgan baholash mezonlari (masalan, Eksner tizimi) va ekspertlararo kelishuvdan foydalanish",
      "Sinovdan o'tuvchining barcha javoblarini cheklash va savollarni yopiq qilish",
      "Faqat bitta yagona javob variantini to'g'ri deb qabul qilish",
      "Talqin qilish jarayonida shaxsning tarjimai holini hisobga olmaslik",
    ],
    correctAnswer: "Standartlashtirilgan baholash mezonlari (masalan, Eksner tizimi) va ekspertlararo kelishuvdan foydalanish",
  },
  {
    id: 10,
    question: "Proyektiv metodlarning retest (qayta testlash) ishonchliligini baholashdagi qiyinchilik nimaga bog'liq?",
    options: [
      "Rag'batlantiruvchi materiallarning tez eskirib qolishiga",
      "Shaxsning emotsional holati va dinamik kechinmalarining o'zgaruvchanligiga",
      "Sinovdan o'tuvchilarning test materialini to'liq yodlab olishiga",
      "Psixologning sinov jarayonida qatnasha olmasligiga",
    ],
    correctAnswer: "Shaxsning emotsional holati va dinamik kechinmalarining o'zgaruvchanligiga",
  },
  {
    id: 11,
    question: "Proyektiv psixodiagnostikada eksperimentatorlararo (baholovchilararo) ishonchlilik qanday aniqlanadi?",
    options: [
      "Sinovdan o'tuvchining o'z natijasiga bergan subyektiv bahosi bilan",
      "Bitta ekspertning testni vaqt o'tishi bilan qayta tekshirishi bilan",
      "Bir nechta mustaqil ekspertlar tomonidan bitta protokolga berilgan baholarning moslik darajasi bilan",
      "Savollar sonining ko'pligi va murakkabligi bilan",
    ],
    correctAnswer: "Bir nechta mustaqil ekspertlar tomonidan bitta protokolga berilgan baholarning moslik darajasi bilan",
  },
  {
    id: 12,
    question: "Proyektiv metodlarning validligi (asosliligi) asosan qaysi mezon orqali tekshiriladi?",
    options: [
      "Testdagi rasmlarning estetik go'zalligi orqali",
      "Faqat yuzaki (tashqi) ko'rinishining jozibadorligi orqali",
      "Javoblarni kompyuterda tezkor hisoblash imkoniyati orqali",
      "Klinik mezonlar, tashqi xulq-atvor ko'rsatkichlari va boshqa valid metodikalar bilan konvergentligi orqali",
    ],
    correctAnswer: "Klinik mezonlar, tashqi xulq-atvor ko'rsatkichlari va boshqa valid metodikalar bilan konvergentligi orqali",
  },
  {
    id: 13,
    question: "L. Frank tasnifiga ko'ra, tayyor materiallardan (kubiklar, plastilin, rasmlar) yaxlit kompozitsiya yaratish qaysi metodlarga kiradi?",
    options: [
      "Konstruktiv proyektiv metodlar",
      "Konstitutiv metodlar",
      "Interpretativ metodlar",
      "Ekspressiv metodlar",
    ],
    correctAnswer: "Konstruktiv proyektiv metodlar",
  },
  {
    id: 14,
    question: "Tugallanmagan jumlalar va ertaklarni yakunlash qaysi proyektiv metodlar guruhiga kiradi?",
    options: [
      "Impressiv metodlar",
      "Additiv (yakunlovchi) metodlar",
      "Refleksiv metodlar",
      "Konstitutiv metodlar",
    ],
    correctAnswer: "Additiv (yakunlovchi) metodlar",
  },
  {
    id: 15,
    question: "Rasm chizish (masalan, 'Mavjud bo'lmagan hayvon', 'Daraxt') qaysi proyektiv guruhga mansub?",
    options: [
      "Interpretativ metodlar",
      "Impressiv metodlar",
      "Ekspressiv (motor-grafik) metodlar",
      "Katartik metodlar",
    ],
    correctAnswer: "Ekspressiv (motor-grafik) metodlar",
  },
  {
    id: 16,
    question: "Proyektiv testlar natijalarini talqin qilishda qaysi tamoyil eng muhim hisoblanadi?",
    options: [
      "Ijtimoiy kelib chiqishiga qarab qat'iy cheklovlar qo'yish tamoyili",
      "Har bir alomatni alohida va mutlaq deb hisoblash tamoyili",
      "Faqat patologik belgilarga e'tibor qaratish tamoyili",
      "Xolistik (butunlik, shaxsni yaxlit tizim sifatida ko'rish) tamoyili",
    ],
    correctAnswer: "Xolistik (butunlik, shaxsni yaxlit tizim sifatida ko'rish) tamoyili",
  },
  {
    id: 17,
    question: "Psixoanalitik yondashuvda proyektiv javoblarning shakllanishida qaysi aqliy instansiya asosiy rolni o'ynaydi?",
    options: [
      "Ongsizlik (Id) va uning ramziy ifodalanishi",
      "Ongli iroda va ratsional boshqaruv",
      "Super-Egoning to'liq g'alabasi",
      "Sensomotor reaksiyalar tezligi",
    ],
    correctAnswer: "Ongsizlik (Id) va uning ramziy ifodalanishi",
  },
  {
    id: 18,
    question: "Zamonaviy psixodiagnostikada proyektiv metodlar ko'pincha qanday maqsadda qo'llaniladi?",
    options: [
      "Aqliy zaiflik darajasini raqamlarda aniq o'lchash uchun",
      "Shaxsning chuqur motivlari, ichki ziddiyatlari va himoya mexanizmlarini o'rganish uchun",
      "Kasbiy bilimlarni test sinovidan o'tkazish uchun",
      "Insonning xotira hajmi va e'tiborini tekshirish uchun",
    ],
    correctAnswer: "Shaxsning chuqur motivlari, ichki ziddiyatlari va himoya mexanizmlarini o'rganish uchun",
  },
  {
    id: 19,
    question: "Proyektiv metodlarni o'tkazishda psixologning o'zini tutishi qanday bo'lishi lozim?",
    options: [
      "Har bir javobni ma'qullab, sinovchiga to'g'ri javoblarni aytib turuvchi",
      "Qat'iy, ko'rsatmaga to'liq rioya qilishni talab qiluvchi va xatolarni tuzatuvchi",
      "Neytral, xayrixoh, yo'naltiruvchi baholardan xoli va sinovchiga erkin muhit yaratuvchi",
      "Faoliyatga mutlaqo aralashmay, xonani tark etuvchi",
    ],
    correctAnswer: "Neytral, xayrixoh, yo'naltiruvchi baholardan xoli va sinovchiga erkin muhit yaratuvchi",
  },
  {
    id: 20,
    question: "Proyektiv usullarning ekologik validligi deganda nima tushuniladi?",
    options: [
      "Faqat laboratoriya sharoitida to'g'ri chiqishi",
      "Test materiallarining tabiat muhitida qo'llanishi",
      "Metodikaning qog'ozsiz va kompyuterlashtirilgan bo'lishi",
      "Olingan natijalarning insonning real hayotiy xulq-atvori va kechinmalariga mos kelishi",
    ],
    correctAnswer: "Olingan natijalarning insonning real hayotiy xulq-atvori va kechinmalariga mos kelishi",
  },
  {
    id: 21,
    question: "Proyektiv javoblarning shakllanishida 'idrokning selektivligi' nimani anglatadi?",
    options: [
      "Inson o'z ehtiyoji, xavotiri va tajribasiga mos keladigan detallarni birinchi navbatda payqashi",
      "Barcha insonlar har qanday stimulni aynan bir xilda idrok etishi",
      "Idrok jarayonining faqat ko'rish o'tkirligiga bog'liqligi",
      "Tashqi ogohlantiruvchilarni butunlay inkor etish",
    ],
    correctAnswer: "Inson o'z ehtiyoji, xavotiri va tajribasiga mos keladigan detallarni birinchi navbatda payqashi",
  },
  {
    id: 22,
    question: "Proyektiv metodlar yordamida shaxsni o'rganishda xatolikka yo'l qo'ymaslik uchun nima talab etiladi?",
    options: [
      "Bitta proyektiv test natijasiga asoslanib qat'iy klinik tashxis qo'yish",
      "Natijalarni biografik ma'lumotlar, suhbat va obyektiv testlar bilan birgalikda kompleks tahlil qilish",
      "Talqinni faqat standart kitobiy ma'nolar orqali so'zma-so'z ko'chirish",
      "Bemorning yoshi va madaniy muhitini tahlildan chiqarib tashlash",
    ],
    correctAnswer: "Natijalarni biografik ma'lumotlar, suhbat va obyektiv testlar bilan birgalikda kompleks tahlil qilish",
  },
  {
    id: 23,
    question: "L. Frank taklif etgan 'katartik' proyektiv metodlarning mohiyati nima?",
    options: [
      "Rasmlarni guruhlarga ajratish orqali mantiqni tekshirish",
      "Qat'iy matematik masalalarni yechish orqali xotirani charxlash",
      "Maxsus uyushtirilgan o'yin yoki drama sharoitida emotsional bo'shashish va kechinmalarni ifodalash",
      "Faqat ranglarning afzalligini aniqlash",
    ],
    correctAnswer: "Maxsus uyushtirilgan o'yin yoki drama sharoitida emotsional bo'shashish va kechinmalarni ifodalash",
  },
  {
    id: 24,
    question: "Proyektiv metodlarda shaxsning 'himoya mexanizmlari' qanday namoyon bo'ladi?",
    options: [
      "Rasm chizishda faqat chiroyli ranglardan foydalanishda",
      "Javoblarni juda tez va xatosiz aytishda",
      "Psixolog bilan do'stona munosabat o'rnatishga intilishda",
      "Vazifadan bosh tortish, haddan tashqari rasmiy javoblar berish yoki agressiv reaksiyalarda",
    ],
    correctAnswer: "Vazifadan bosh tortish, haddan tashqari rasmiy javoblar berish yoki agressiv reaksiyalarda",
  },
  {
    id: 25,
    question: "Quyidagilardan qaysi biri proyektiv yondashuvning metodologik asosi hisoblanmaydi?",
    options: [
      "Bixeviorizmning 'S - R' (qobiliyatni mexanik mustahkamlash) qat'iy reaksion modeli",
      "Xolistik (butunlik) shaxs konsepsiyasi",
      "Psixodinamik va ongsizlik nazariyalari",
      "Fenomenologik tajriba tushunchasi",
    ],
    correctAnswer: "Bixeviorizmning 'S - R' (qobiliyatni mexanik mustahkamlash) qat'iy reaksion modeli",
  },
  {
    id: 26,
    question: "Proyektiv usullarda 'Apperseptiv buzilish' (distortion) nima?",
    options: [
      "Ko'rish nervining zararlanishi oqibatida tasvirni ko'ra olmaslik",
      "Insonning o'z ichki ziddiyatlari ta'sirida obyektiv stimulni o'zgartirib idrok qilishi",
      "Eshitish qobiliyatining pasayishi tufayli savolni tushunmaslik",
      "Ataylab yolg'on ma'lumot berishga intilish",
    ],
    correctAnswer: "Insonning o'z ichki ziddiyatlari ta'sirida obyektiv stimulni o'zgartirib idrok qilishi",
  },
  {
    id: 27,
    question: "Proyektiv javoblarni tahlil qilishda 'Formal mezonlar'ga nimalar kiradi?",
    options: [
      "Hikoyaning adabiy tili va badiiy bezaklari",
      "Qahramonning aytgan so'zlari va uning axloqiy bahosi",
      "Javob berish vaqti, tasvirning joylashuvi, chiziqlar bosimi va javoblar soni",
      "Sinovchining kiyinish madaniyati va tashqi qiyofasi",
    ],
    correctAnswer: "Javob berish vaqti, tasvirning joylashuvi, chiziqlar bosimi va javoblar soni",
  },
  {
    id: 28,
    question: "Proyektiv javoblarni tahlil qilishda 'Mazmuniy mezonlar' nimani ifodalaydi?",
    options: [
      "Test o'tkazilgan xonaning yoritilganlik darajasi",
      "Chizilgan chiziqlarning qalinligi va qalamning qattiqligi",
      "Kartochkaning qaysi burchagiga ko'proq qaralganligi",
      "Sujet yo'nalishi, qahramonlarning xarakteri, mavzular va asosiy ramzlar",
    ],
    correctAnswer: "Sujet yo'nalishi, qahramonlarning xarakteri, mavzular va asosiy ramzlar",
  },
  {
    id: 29,
    question: "Proyektiv metodlarning 'standardlashtirilgan testlar'dan ustunligi nimada?",
    options: [
      "Shaxsning noyob, takrorlanmas individual kechinmalarini chuqur yoritib bera olishida",
      "Katta guruhlarni bir vaqtning o'zida tezkor saralash imkoniyatida",
      "Hisoblash formulalarining soddaligi va hammabopligida",
      "Psixologik tayyorgarligi yo'q odamlar ham qo'llay olishida",
    ],
    correctAnswer: "Shaxsning noyob, takrorlanmas individual kechinmalarini chuqur yoritib bera olishida",
  },
  {
    id: 30,
    question: "Proyektiv psixologiyada interpretatsiyaning to'g'riligini ta'minlovchi asosiy omil nima?",
    options: [
      "Faqat yangi chiqqan kompyuter dasturidan foydalanish",
      "Psixologning chuqur nazariy bilimi, klinik tajribasi va psixometrik etikaga rioya qilishi",
      "Sinovdan o'tuvchining barcha talqinlarga darhol rozi bo'lishi",
      "Sinov jarayonining iloji boricha tez yakunlanishi",
    ],
    correctAnswer: "Psixologning chuqur nazariy bilimi, klinik tajribasi va psixometrik etikaga rioya qilishi",
  },
  {
    id: 31,
    question: "Proyektiv yondashuvning falsafiy asoslarida qaysi konsepsiya muhim o'rin tutadi?",
    options: [
      "Pozitivizmning faqat bevosita kuzatiladigan xatti-harakatlarni o'rganish talabi",
      "Ob'yektiv olamning inson ongidan mutlaq mustaqil ekanligi va uni mexanik aks ettirish",
      "Tajribaning subyektivligi va inson tomonidan voqelikning faol 'qurilishi' (konstruktivizm)",
      "Ratsionalizmning inson xulq-atvorini faqat mantiq bilan tushuntirishi",
    ],
    correctAnswer: "Tajribaning subyektivligi va inson tomonidan voqelikning faol 'qurilishi' (konstruktivizm)",
  },
  {
    id: 32,
    question: "Fenomenologik yondashuv proyektiv usullar rivojlanishiga qanday ta'sir ko'rsatdi?",
    options: [
      "Barcha odamlarning ruhiy holatini standart qoliplarga solishni talab qildi",
      "Faqat fiziologik reflekslarni o'lchash zarurligini ilgari surdi",
      "Inson ruhiyatini to'liq rad etib, biologik omillarni birinchi o'ringa qo'ydi",
      "Shaxsning subyektiv ichki kechinmalari va dunyoni o'ziga xos idrok etishining birlamchiligini asosladi",
    ],
    correctAnswer: "Shaxsning subyektiv ichki kechinmalari va dunyoni o'ziga xos idrok etishining birlamchiligini asosladi",
  },
  {
    id: 33,
    question: "Ongsizlik va simvolizatsiya (ramziylik) g'oyasi qaysi oqim tomonidan proyektiv diagnostika asosiga qo'yildi?",
    options: [
      "Z. Freydning psixoanalitik nazariyasi",
      "J. Uotsonning bixeviorizmi",
      "V. Vundtning strukturalizmi",
      "K. Levinning maydon nazariyasi",
    ],
    correctAnswer: "Z. Freydning psixoanalitik nazariyasi",
  },
  {
    id: 34,
    question: "Alfred Adlerning proyektiv yondashuvga qo'shgan asosiy hissasi qaysi tushuncha bilan bog'liq?",
    options: [
      "Psixoseksual rivojlanish bosqichlari",
      "'Turmush tarzi' (Life style) va erta bolalik xotiralarini tahlil qilish",
      "Kollektiv ongsizlik va arxetiplar",
      "Klassik shartli reflekslar",
    ],
    correctAnswer: "'Turmush tarzi' (Life style) va erta bolalik xotiralarini tahlil qilish",
  },
  {
    id: 35,
    question: "K.G. Yungning analitik psixologiyasi proyektiv diagnostikani qanday boyitdi?",
    options: [
      "IQ koeffitsiyentini o'lchash shkalasini yaratish bilan",
      "Faqat tashqi xulq-atvorni modellashtirish orqali",
      "Arxetiplar, ramzlar nazariyasi va Assotsiativ eksperiment orqali affektiv komplekslarni ochish bilan",
      "Operant shartlanish qonunlarini kiritish bilan",
    ],
    correctAnswer: "Arxetiplar, ramzlar nazariyasi va Assotsiativ eksperiment orqali affektiv komplekslarni ochish bilan",
  },
  {
    id: 36,
    question: "K.G. Yung tomonidan ishlab chiqilgan va proyektiv metodlarning debochasi hisoblangan metodika qaysi?",
    options: [
      "Qo'l testi (Hand test)",
      "Tematik apperseptiv test",
      "Ranglar tanlash testi",
      "So'zlar assotsiatsiyasi testi (Verbal assotsiativ test)",
    ],
    correctAnswer: "So'zlar assotsiatsiyasi testi (Verbal assotsiativ test)",
  },
  {
    id: 37,
    question: "19-asr oxiri va 20-asr boshlaridagi qaysi soha proyektiv yondashuvning asosiy klinik manbai bo'ldi?",
    options: [
      "Klinik psixiatriya va nevrologiya (isteriya va travmalarni o'rganish)",
      "Sanoat psixologiyasi va mehnatni tashkil etish",
      "Pedagogik testologiya va maktab baholash tizimi",
      "Etnografik antropologiya",
    ],
    correctAnswer: "Klinik psixiatriya va nevrologiya (isteriya va travmalarni o'rganish)",
  },
  {
    id: 38,
    question: "J.M. Sharko va P. Janetning qaysi g'oyalari proyektiv metodlarning paydo bo'lishiga zamin yaratdi?",
    options: [
      "Xotiraning mexanik assotsiatsiyalari va uning egri chizig'i",
      "Ruhiy travmalar, ongning parchalanishi (dissotsiatsiya) va yashirin aqliy jarayonlar",
      "Irsiyatning shaxs xarakteridagi mutlaq yetakchiligi",
      "Miya to'qimalarining faqat anatomik tuzilishi",
    ],
    correctAnswer: "Ruhiy travmalar, ongning parchalanishi (dissotsiatsiya) va yashirin aqliy jarayonlar",
  },
  {
    id: 39,
    question: "Hermann Rorshax o'zining mashhur siyoh dog'lari testini dastlab qaysi asarida bayon qilgan?",
    options: [
      "'Shaxsning dinamik nazariyasi' (1935 y.)",
      "'Ongsizlik psixologiyasi' (1915 y.)",
      "'Psixodiagnostika' (1921 y.)",
      "'Tushlar ta'biri' (1900 y.)",
    ],
    correctAnswer: "'Psixodiagnostika' (1921 y.)",
  },
  {
    id: 40,
    question: "H. Rorshax o'z metodikasini yaratishda dastlab qanday asosiy klinik vazifani qo'ygan edi?",
    options: [
      "Harbiy xizmatchilarning jismoniy chidamliligini baholash",
      "Bolalarning aqliy qobiliyati (IQ) darajasini o'lchash",
      "Kasbga yo'naltirish bo'yicha qobiliyatlarni saralash",
      "Shizofreniya bilan og'rigan bemorlarni differensial diagnostika qilish va idrok xususiyatlarini aniqlash",
    ],
    correctAnswer: "Shizofreniya bilan og'rigan bemorlarni differensial diagnostika qilish va idrok xususiyatlarini aniqlash",
  },
  {
    id: 41,
    question: "Rorshax testini tizimlashtirish va AQSHda uning interpretatsiya maktabini rivojlantirishda kimlar ulkan hissa qo'shgan?",
    options: [
      "B. Klopfer va S. Bek",
      "K. Xorni va E. Fromm",
      "B. Skinner va E. Torndayk",
      "A. Maslou va K. Rojers",
    ],
    correctAnswer: "B. Klopfer va S. Bek",
  },
  {
    id: 42,
    question: "G. Rorshax testidagi javoblarni kodlashtirishni birlashtirgan 'Kompleks tizim' (Comprehensive System) muallifi kim?",
    options: [
      "L. Frank",
      "J. Eksner",
      "G. Myurrey",
      "S. Rozentsveyg",
    ],
    correctAnswer: "J. Eksner",
  },
  {
    id: 43,
    question: "Ilk proyektiv metodlarning ommalashuviga sabab bo'lgan asosiy tarixiy omil nima edi?",
    options: [
      "Faqat tinchlik davridagi iqtisodiy inqirozlarni bartaraf etish",
      "Maktablarda o'quvchilar sonining keskin kamayib ketishi",
      "Ikkinchi jahon urushi davrida askarlarning jangovar travmalari va nevrozlarini tezkor chuqur o'rganish zaruriyati",
      "Universitetlarda psixologiya kafedralarining yopilishi",
    ],
    correctAnswer: "Ikkinchi jahon urushi davrida askarlarning jangovar travmalari va nevrozlarini tezkor chuqur o'rganish zaruriyati",
  },
  {
    id: 44,
    question: "Bolalar va o'smirlar psixologiyasida proyektiv metodlar nima sababdan juda tez ommalashdi?",
    options: [
      "Bolalar ruhiyatida ongsizlik jarayonlarining umuman mavjud emasligi",
      "Bolalarda mantiqiy tafakkurning kattalardan ancha ustun ekanligi",
      "Bolalarga standart so'rovnomalarni to'ldirish qulayligi",
      "Bolalarning o'z his-tuyg'ularini so'z bilan to'liq ifodalay olmasligi va o'yin/rasm vositasida ochilishi",
    ],
    correctAnswer: "Bolalarning o'z his-tuyg'ularini so'z bilan to'liq ifodalay olmasligi va o'yin/rasm vositasida ochilishi",
  },
  {
    id: 45,
    question: "Anna Freyd va Melani Klyayn bolalar bilan ishlashda qaysi proyektiv vositani keng qo'llaganlar?",
    options: [
      "O'yin terapiyasi va erkin rasm chizish faoliyatini",
      "Matnli 500 savolli so'rovnomalarni",
      "Laboratoriya reaksiyometrini",
      "Qat'iy matematik mantiq testlarini",
    ],
    correctAnswer: "O'yin terapiyasi va erkin rasm chizish faoliyatini",
  },
  {
    id: 46,
    question: "20-asrning ikkinchi yarmida proyektiv metodlarga nisbatan bildirilgan asosiy tanqid nimalardan iborat bo'ldi?",
    options: [
      "Metodikalarning haddan tashqari arzon va ommabop ekanligi",
      "Psixometrik ishonchlilik va validlik ko'rsatkichlarining pastligi, natijalarning tekshiruvchiga bog'liqligi",
      "Barcha odamlar uchun bir xil tushunarli bo'lib qolganligi",
      "Faqat iqtidorli insonlarni aniqlash bilan cheklanganligi",
    ],
    correctAnswer: "Psixometrik ishonchlilik va validlik ko'rsatkichlarining pastligi, natijalarning tekshiruvchiga bog'liqligi",
  },
  {
    id: 47,
    question: "Proyektiv usullarning institutsionalizatsiyasi deganda nima tushuniladi?",
    options: [
      "Metodikalarning qat'iy ravishda yo'q qilinishi",
      "Ularni faqat davlat organlari tomonidan taqiqlanishi",
      "Ularning universitet ta'lim dasturlariga, klinik standartlarga kiritilishi va maxsus jurnallar/jamiyatlar tuzilishi",
      "Proyektiv metodlarning barcha psixologlar tomonidan rad etilishi",
    ],
    correctAnswer: "Ularning universitet ta'lim dasturlariga, klinik standartlarga kiritilishi va maxsus jurnallar/jamiyatlar tuzilishi",
  },
  {
    id: 48,
    question: "Tanqidlarga javoban zamonaviy diagnostikada proyektiv metodlarga qanday yondashuv qaror topdi?",
    options: [
      "Psixolog malakasiga qo'yiladigan talablarni bekor qilish",
      "Proyektiv metodlardan butunlay voz kechish va ularni taqiqlash",
      "Faqat bitta proyektiv usulga tayanib uzil-kesil xulosa chiqarish",
      "Kompleks (batareya) yondashuv: proyektiv metodlarni obyektiv testlar va klinik suhbat bilan birgalikda qo'llash",
    ],
    correctAnswer: "Kompleks (batareya) yondashuv: proyektiv metodlarni obyektiv testlar va klinik suhbat bilan birgalikda qo'llash",
  },
  {
    id: 49,
    question: "Zamonaviy amaliyotda proyektiv metodlarni qo'llashda mutaxassisning qaysi jihati birinchi o'ringa chiqadi?",
    options: [
      "Professional mas'uliyat, klinik kompetensiya va etik me'yorlarga qat'iy rioya qilish",
      "Faqat test materiallarini chiroyli ko'rinishda saqlash",
      "Har qanday holatda ham mijozga yoqadigan tashxis qo'yish",
      "Bemorning maxfiy ma'lumotlarini ommaviy muhokama qilish",
    ],
    correctAnswer: "Professional mas'uliyat, klinik kompetensiya va etik me'yorlarga qat'iy rioya qilish",
  },
  {
    id: 50,
    question: "Proyektiv yondashuvda 'voqelikni qurish' (konstruktivizm) g'oyasi nimani anglatadi?",
    options: [
      "Hamma odamlar obyektiv reallikni fototasvirdek bir xil qabul qiladi",
      "Inson tashqi dunyoni passiv aks ettirmaydi, balki o'z ichki tajribasi orqali unga ma'no yuklaydi",
      "Haqiqat faqat jismoniy o'lchov asboblari orqali mavjud bo'ladi",
      "Ong osti jarayonlari tashqi olamga hech qanday ta'sir o'tkazmaydi",
    ],
    correctAnswer: "Inson tashqi dunyoni passiv aks ettirmaydi, balki o'z ichki tajribasi orqali unga ma'no yuklaydi",
  },
  {
    id: 51,
    question: "Psixoanalitik nazariyada simvolizatsiya (ramziylashtirish) qanday vazifani bajaradi?",
    options: [
      "Insonning matematik qobiliyatlarini rivojlantirish",
      "Miyadagi qon aylanishini yaxshilash",
      "Ongsizlikdagi taqiqlangan istak va travmalarni ong senzurasidan o'tkazib, ramzlar orqali ifodalash",
      "Tashqi ogohlantiruvchilarni butunlay yo'q qilish",
    ],
    correctAnswer: "Ongsizlikdagi taqiqlangan istak va travmalarni ong senzurasidan o'tkazib, ramzlar orqali ifodalash",
  },
  {
    id: 52,
    question: "Ilk proyektiv metodlardan biri hisoblangan 'Goodenough - Harris' testi nima bilan bog'liq?",
    options: [
      "Labyrintlardan chiqish yo'lini topish",
      "Rangli kartochkalarni saralash",
      "Musiqa asboblarini chala olishni tekshirish",
      "Odam rasmini chizish orqali bolaning aqliy rivojlanishini o'rganish",
    ],
    correctAnswer: "Odam rasmini chizish orqali bolaning aqliy rivojlanishini o'rganish",
  },
  {
    id: 53,
    question: "Proyektiv usullarning rivojlanishida Geshtalt psixologiyasining hissasi nimada?",
    options: [
      "Idrokning yaxlitligi, 'figura va fon' munosabatlari hamda maydon ta'siri qonunlarini asoslab berganligida",
      "Shaxsni faqat alohida reflekslar to'plami deb e'lon qilganligida",
      "Ongsizlik tushunchasini butunlay inkor etganligida",
      "Faqat biologik instinktlarni birinchi o'ringa qo'yganligida",
    ],
    correctAnswer: "Idrokning yaxlitligi, 'figura va fon' munosabatlari hamda maydon ta'siri qonunlarini asoslab berganligida",
  },
  {
    id: 54,
    question: "XX asr o'rtalarida nima sababdan proyektiv metodlar 'Oltin davr'ni boshdan kechirdi?",
    options: [
      "Boshqa barcha psixologik metodikalarning eskirib yo'q bo'lib ketgani uchun",
      "Shaxsni chuqur va unikal o'rganishga bo'lgan talabning ortishi va psixoanalizning g'alabasi tufayli",
      "Kompyuter texnologiyalarining barcha testlarni avtomatlashtirgani uchun",
      "Tibbiyot fanining proyektiv testlardan to'liq voz kechgani uchun",
    ],
    correctAnswer: "Shaxsni chuqur va unikal o'rganishga bo'lgan talabning ortishi va psixoanalizning g'alabasi tufayli",
  },
  {
    id: 55,
    question: "Proyektiv metodologiya tarixida 'klinik intuitsiya' qanday baholangan?",
    options: [
      "Ilmiy tadqiqotlarda boshidanoq qat'iyan man etilgan",
      "Har doim yagona va mutlaq to'g'ri mezon deb hisoblangan",
      "Dastlab yetakchi vosita bo'lgan, keyinchalik esa uni obyektiv mezonlar bilan cheklash zarurligi e'tirof etilgan",
      "Hech qachon amaliyotda qo'llanilmagan",
    ],
    correctAnswer: "Dastlab yetakchi vosita bo'lgan, keyinchalik esa uni obyektiv mezonlar bilan cheklash zarurligi e'tirof etilgan",
  },
  {
    id: 56,
    question: "Zamonaviy diagnostikada proyektiv usullarning qo'llanilish chegarasi nimada ifodalanadi?",
    options: [
      "Ularni faqat guruhli shaklda o'tkazish majburiyligida",
      "Ularni faqat 18 yoshdan oshgan shaxslarda qo'llash mumkinligida",
      "Ulardan faqat maktablarda foydalanishga ruxsat berilganligida",
      "Ularni yolg'iz o'zini qonuniy ekspertiza xulosasi yoki yakuniy klinik diagnoz sifatida qo'llab bo'lmasligida",
    ],
    correctAnswer: "Ularni yolg'iz o'zini qonuniy ekspertiza xulosasi yoki yakuniy klinik diagnoz sifatida qo'llab bo'lmasligida",
  },
  {
    id: 57,
    question: "Proyektiv testlarning kross-madaniy (madaniyatlararo) tadqiqotlardagi xususiyati nimada?",
    options: [
      "Ramzlar va timsollarning ma'nosi turli madaniyatlarda turlicha talqin qilinishi mumkinligini hisobga olish",
      "Barcha madaniyatlar uchun ramzlarning mutlaq universalligi",
      "Boshqa tillarga tarjima qilishning mutlaqo imkonsizligi",
      "Madaniy omillarning idrokka hech qanday ta'sir ko'rsatmasligi",
    ],
    correctAnswer: "Ramzlar va timsollarning ma'nosi turli madaniyatlarda turlicha talqin qilinishi mumkinligini hisobga olish",
  },
  {
    id: 58,
    question: "Proyektiv metodlarning qat'iy standart testlardan asosiy farqi qaysi epistemologik yondashuvga asoslanadi?",
    options: [
      "Faqat nomotetik (umumlashtiruvchi) statistik qoliplarga tayanish",
      "Idiotetik (har bir shaxsning o'ziga xosligi) yondashuvga, nomotetik (umumiy qonuniyatlar) yondashuvdan ko'ra ko'proq tayanish",
      "Pozitivistik qat'iy o'lchovlar tizimiga tayanish",
      "Materialistik qat'iy determinizmga tayanish",
    ],
    correctAnswer: "Idiotetik (har bir shaxsning o'ziga xosligi) yondashuvga, nomotetik (umumiy qonuniyatlar) yondashuvdan ko'ra ko'proq tayanish",
  },
  {
    id: 59,
    question: "Proyektiv metodlarni rivojlantirishda klinik psixologlarning axloqiy kodeksi nima uchun zarur bo'ldi?",
    options: [
      "Barcha mijozlarni davolanishga majburlash uchun",
      "Test blankalarini qimmat narxlarda sotishni yo'lga qo'yish uchun",
      "Talqinlarning asossiz bo'lishi va mijozga noto'g'ri tashxis tamg'asi bosilishining oldini olish uchun",
      "Diagnostika jarayonini jamoatchilikka ochiq ko'rsatish uchun",
    ],
    correctAnswer: "Talqinlarning asossiz bo'lishi va mijozga noto'g'ri tashxis tamg'asi bosilishining oldini olish uchun",
  },
  {
    id: 60,
    question: "Proyektiv diagnostika tarixida 'Barkamol shaxs' tushunchasini baholashda proyektiv testlar qanday rol o'ynagan?",
    options: [
      "Shaxsning faqat nutqiy savodxonligini tekshirishda",
      "Faqat odamning jismoniy baquvvatligini aniqlashda",
      "Insonning faqat boylik to'plashga bo'lgan moyilligini ko'rsatishda",
      "Ichki ziddiyatlar, adaptatsiya darajasi va shaxsiy o'sish resurslarini kompleks baholashda",
    ],
    correctAnswer: "Ichki ziddiyatlar, adaptatsiya darajasi va shaxsiy o'sish resurslarini kompleks baholashda",
  },
  {
    id: 61,
    question: "Impressiv proyektiv metodlarning boshqa proyektiv metodlardan farq qiluvchi asosiy xususiyati nimada?",
    options: [
      "Rag'batlantiruvchi materiallarni afzal ko'rish, tanlash yoki yoqtirmaslik asosida baholanishida",
      "Sinovchidan rasm chizish yoki ertak to'qish talab etilishida",
      "Faqat harakatli o'yinlar orqali amalga oshirilishida",
      "Javoblarning yozma insho tarzida taqdim etilishida",
    ],
    correctAnswer: "Rag'batlantiruvchi materiallarni afzal ko'rish, tanlash yoki yoqtirmaslik asosida baholanishida",
  },
  {
    id: 62,
    question: "Maks Lyusher o'zining mashhur ranglar testini nechanchi yilda ilk bor taqdim etgan?",
    options: [
      "1921 yilda",
      "1947 yilda (Lozannadagi Butunjahon psixologiya kongressida)",
      "1905 yilda",
      "1975 yilda",
    ],
    correctAnswer: "1947 yilda (Lozannadagi Butunjahon psixologiya kongressida)",
  },
  {
    id: 63,
    question: "M. Lyusher testining fundamental nazariy asosi qanday qoidaga tayanadi?",
    options: [
      "Ranglarni tanlash faqat insonning estetik didi va modaga qiziqishiga bog'liq",
      "Ranglar barcha odamlarda bir xil ixtiyoriy reaktsiyani yuzaga keltiradi",
      "Ranglarni idrok etish universal va obyektivdir, ammo ranglarga munosabat subyektiv holatni aks ettiradi",
      "Ranglar faqat ko'z gavharining optik charchoq darajasini ko'rsatadi",
    ],
    correctAnswer: "Ranglarni idrok etish universal va obyektivdir, ammo ranglarga munosabat subyektiv holatni aks ettiradi",
  },
  {
    id: 64,
    question: "M. Lyusherning qisqartirilgan (klinik) testida nechta rangli kartochkadan foydalaniladi?",
    options: [
      "4 ta rang",
      "12 ta rang",
      "16 ta rang",
      "8 ta rang (4 ta asosiy va 4 ta qo'shimcha rang)",
    ],
    correctAnswer: "8 ta rang (4 ta asosiy va 4 ta qo'shimcha rang)",
  },
  {
    id: 65,
    question: "M. Lyusher testidagi 4 ta asosiy (bazaviy) ranglar qatoriga qaysilar kiradi?",
    options: [
      "Ko'k, yashil, qizil, sariq",
      "Qora, oq, kulrang, jigarrang",
      "Binafsharang, havorang, to'q sariq, qizil",
      "Yashil, binafsharang, jigarrang, qora",
    ],
    correctAnswer: "Ko'k, yashil, qizil, sariq",
  },
  {
    id: 66,
    question: "M. Lyusher testidagi 4 ta qo'shimcha (yordamchi) ranglar qaysilar?",
    options: [
      "Ko'k, yashil, qizil, sariq",
      "Binafsharang, jigarrang, qora, kulrang (0-raqamli)",
      "Pushti, och ko'k, sabzirang, oq",
      "Zangori, feruza, zumrad, tillarang",
    ],
    correctAnswer: "Binafsharang, jigarrang, qora, kulrang (0-raqamli)",
  },
  {
    id: 67,
    question: "M. Lyusher testini o'tkazish tartibida kartochkalar qanday ko'rsatiladi?",
    options: [
      "Sinovchining kiyimiga moslashtirilgan fonda",
      "Ketma-ket bittalab, qorong'i xonada",
      "Bir tekisda yoyilgan holda, yaxshi tabiiy yorug'likda va neytral fonda",
      "Faqat ko'zgudagi aksi orqali",
    ],
    correctAnswer: "Bir tekisda yoyilgan holda, yaxshi tabiiy yorug'likda va neytral fonda",
  },
  {
    id: 68,
    question: "Lyusher testida sinovdan o'tuvchiga qanday ko'rsatma beriladi?",
    options: [
      "Sizga bolaligingizni eslatuvchi ranglarni ajrating",
      "Eng qimmat va chiroyli ko'ringan rangni toping",
      "Ranglarning nomini tezda yoddan aytib bering",
      "Ranglarni kiyimingizga yoki modaga qarab emas, ayni paytdagi eng yoqimliligiga qarab tanlang",
    ],
    correctAnswer: "Ranglarni kiyimingizga yoki modaga qarab emas, ayni paytdagi eng yoqimliligiga qarab tanlang",
  },
  {
    id: 69,
    question: "Lyusher testi metodikasiga ko'ra ranglar tanlovi necha marta amalga oshiriladi?",
    options: [
      "2 marta (birinchi tanlovdan 2-3 daqiqa o'tgach, kartochkalar aralashtirilib qayta tanlanadi)",
      "Faqat 1 marta",
      "Ketma-ket 5 marta",
      "Bir oy davomida har kuni",
    ],
    correctAnswer: "2 marta (birinchi tanlovdan 2-3 daqiqa o'tgach, kartochkalar aralashtirilib qayta tanlanadi)",
  },
  {
    id: 70,
    question: "Lyusher testida ikkinchi tanlovning o'tkazilishidan asosiy maqsad nima?",
    options: [
      "Sinovchining xotirasini tekshirish",
      "Birinchi tanlovdagi xohish-istakdan ko'ra barqarorroq va haqiqiyroq psixologik holatni aniqlash",
      "Ranglarning joyini o'zgartirmasdan qoldirish",
      "Test vaqtini cho'zish",
    ],
    correctAnswer: "Birinchi tanlovdagi xohish-istakdan ko'ra barqarorroq va haqiqiyroq psixologik holatni aniqlash",
  },
  {
    id: 71,
    question: "Lyusher testida 1-o'rindagi rang belgisi (simvoli) qanday belgilanadi?",
    options: [
      "x (dolzarblik)",
      "+ (ortiqcha / afzallik berish)",
      "- (rad etish)",
    ],
    correctAnswer: "+ (ortiqcha / afzallik berish)",
  },
  {
    id: 72,
    question: "Lyusher testida oxirgi (7 va 8) o'rinlarga qo'yilgan ranglar qanday simvol bilan belgilanadi?",
    options: [
      "+ (ustunlik)",
      "x (simpatiya)",
      "- (rad etish / qoniqtirilmagan ehtiyoj)",
    ],
    correctAnswer: "- (rad etish / qoniqtirilmagan ehtiyoj)",
  },
  {
    id: 73,
    question: "Lyusher testida KO'K rang (1-raqam) qanday psixologik ehtiyojni ifodalaydi?",
    options: [
      "Tinchlik, xotirjamlik, dam olish, bog'liqlik va uyg'unlikka bo'lgan ehtiyoj",
      "Yetakchilik, kurash va agressiya ehtiyojini",
      "Qochish va o'zini butunlay yakkalash istagini",
      "Kelajakka intilish va cheksiz o'zgarishlar ehtiyojini",
    ],
    correctAnswer: "Tinchlik, xotirjamlik, dam olish, bog'liqlik va uyg'unlikka bo'lgan ehtiyoj",
  },
  {
    id: 74,
    question: "Lyusher testida YASHIL rang (2-raqam) nimani anglatadi?",
    options: [
      "To'liq taslim bo'lish va passivlik",
      "O'z qadr-qimmatini saqlash, qat'iyatlilik, iroda va o'zini namoyon qilish istagi",
      "Boshqalar fikriga so'zsiz bo'ysunish",
      "Depressiya va ruhiy inqiroz",
    ],
    correctAnswer: "O'z qadr-qimmatini saqlash, qat'iyatlilik, iroda va o'zini namoyon qilish istagi",
  },
  {
    id: 75,
    question: "Lyusher testida QIZIL rang (3-raqam) qanday holatni ifodalaydi?",
    options: [
      "Yolg'izlikka chekinish istagi",
      "Mutlaq tushkunlik va holsizlik",
      "Harakatga intilish, irodaviy faollik, g'alabaga intilish, ehtiros va qo'zg'aluvchanlik",
      "Befarqlik va emotsional sovuqlik",
    ],
    correctAnswer: "Harakatga intilish, irodaviy faollik, g'alabaga intilish, ehtiros va qo'zg'aluvchanlik",
  },
  {
    id: 76,
    question: "Lyusher testida SARIQ rang (4-raqam) qanday ma'noni bildiradi?",
    options: [
      "Agressiyani ichga yutish",
      "O'tmishdagi xatolardan qo'rqish",
      "Konservatizm va qat'iy cheklovlar",
      "Optimizm, umid, muloqotga ochiqlik, yengillik va ozodlikka intilish",
    ],
    correctAnswer: "Optimizm, umid, muloqotga ochiqlik, yengillik va ozodlikka intilish",
  },
  {
    id: 77,
    question: "Qo'shimcha ranglardan BINAFSHARANG (5-raqam) tanlovda nimani aks ettiradi?",
    options: [
      "Sehrgarlik, intuitivlik, emotsional noziklik, o'ziga rom etish va infantilizm",
      "Yuqori ratsionallik va qat'iy mantiq",
      "Jismoniy charchoqning yo'qligi",
      "O'ta sovuqqon pragmatizm",
    ],
    correctAnswer: "Sehrgarlik, intuitivlik, emotsional noziklik, o'ziga rom etish va infantilizm",
  },
  {
    id: 78,
    question: "JIGARRANG (6-raqam) dastlabki o'rinlarga chiqqanda bu nimadan dalolat beradi?",
    options: [
      "Katta energiya oqimi va bayramona kayfiyat",
      "Jismoniy noqulaylik, kasallik, charchoq va tana xavfsizligiga kuchli ehtiyoj",
      "Yuqori ijodiy ilhom va yetakchilik salohiyati",
      "Hamma narsani mukammal nazorat qilish",
    ],
    correctAnswer: "Jismoniy noqulaylik, kasallik, charchoq va tana xavfsizligiga kuchli ehtiyoj",
  },
  {
    id: 79,
    question: "QORA rang (7-raqam) birinchi o'ringa qo'yilsa, bu qanday holatni bildiradi?",
    options: [
      "Ijtimoiy munosabatlarning gullab-yashnashi",
      "To'liq xotirjamlik va hayotdan mamnunlik",
      "Ekstremal rad etish, norozilik, isyon, inqiroz yoki chuqur depressiv radikallik",
      "Sog'lom optimizm",
    ],
    correctAnswer: "Ekstremal rad etish, norozilik, isyon, inqiroz yoki chuqur depressiv radikallik",
  },
  {
    id: 80,
    question: "KULRANG rang (0-raqam) dastlabki o'rinlarda joylashsa, bu nimanikursatadi?",
    options: [
      "Sportdagi g'alabalarga intilish",
      "Muloqotga haddan tashqari chanqoqlik",
      "Qizg'in jamoat ishlariga kirishish",
      "Vaziyatdan chetlanish, izolyatsiya, o'zini himoya qilish va aralashmaslik istagi",
    ],
    correctAnswer: "Vaziyatdan chetlanish, izolyatsiya, o'zini himoya qilish va aralashmaslik istagi",
  },
  {
    id: 81,
    question: "Lyusher testida 'xavotirlik' (trevojnost) belgisi qanday aniqlanadi?",
    options: [
      "Asosiy ranglarning (1, 2, 3, 4) oxirgi o'rinlarga surilishi va '-' belgisi olishi orqali",
      "Qizil rangning 1-o'ringa qo'yilishi orqali",
      "Sariq rangning 2-o'rinda turishi orqali",
      "Testning 1 daqiqadan kam vaqtda bajarilishi orqali",
    ],
    correctAnswer: "Asosiy ranglarning (1, 2, 3, 4) oxirgi o'rinlarga surilishi va '-' belgisi olishi orqali",
  },
  {
    id: 82,
    question: "Lyusher testida 'Kompensatsiya' mexanizmi nimada ko'rinadi?",
    options: [
      "Ko'k rangning doimo birinchi bo'lishida",
      "Rad etilgan ehtiyoj o'rniga qo'shimcha ranglarning (kulrang, qora, jigarrang) 1-o'ringa chiqishida",
      "Ranglarning hammasi bir vaqtda yoqishida",
      "Sinovchining savollarga javob bermasligida",
    ],
    correctAnswer: "Rad etilgan ehtiyoj o'rniga qo'shimcha ranglarning (kulrang, qora, jigarrang) 1-o'ringa chiqishida",
  },
  {
    id: 83,
    question: "Lyusher testida 'Autovegetativ ko'rsatkich' (K. Shiposh bo'yicha) nimani baholashga xizmat qiladi?",
    options: [
      "Shaxsning so'z boyligini",
      "Faqat ko'rish qobiliyatini",
      "Organizmdagi vegetativ muvozanatni: ergotrop (faoliyat) yoki trofotrop (dam olish) ustunligini",
      "Xotira hajmini",
    ],
    correctAnswer: "Organizmdagi vegetativ muvozanatni: ergotrop (faoliyat) yoki trofotrop (dam olish) ustunligini",
  },
  {
    id: 84,
    question: "Lyusher testida funksional guruhlar nechta juftlikdan iborat?",
    options: [
      "6 ta uchlik",
      "2 ta juftlik",
      "8 ta alohida raqam",
      "4 ta juftlik (+ +, x x, = =, - -)",
    ],
    correctAnswer: "4 ta juftlik (+ +, x x, = =, - -)",
  },
  {
    id: 85,
    question: "Lyusher testidagi 'Ruhiy tanglik' (stress) koeffitsiyenti nimaga asoslanadi?",
    options: [
      "Asosiy ranglarning orqa o'rinlarga tushishi va qo'shimcha ranglarning oldinga siljish darajasiga",
      "Rang kartochkalarining eskirganligiga",
      "Sinovchining qaysi qo'li bilan kartochkani ushlashiga",
      "Test o'tkazilgan xonaning haroratiga",
    ],
    correctAnswer: "Asosiy ranglarning orqa o'rinlarga tushishi va qo'shimcha ranglarning oldinga siljish darajasiga",
  },
  {
    id: 86,
    question: "Lyusher ranglar metodikasining asosiy psixodiagnostik ustunligi nimada?",
    options: [
      "Faqat yuqori intellektli shaxslarda qo'llanilishida",
      "Tezkorligi, til to'siqlariga bog'liq emasligi va ongli soxtalashtirish juda qiyinligi",
      "Natijalarni faqat bemorning o'zi o'qib tushunishida",
      "Hech qanday maxsus kartochkalar talab etilmasligida",
    ],
    correctAnswer: "Tezkorligi, til to'siqlariga bog'liq emasligi va ongli soxtalashtirish juda qiyinligi",
  },
  {
    id: 87,
    question: "Agar sinovdan o'tuvchi ko'k rangni 8-o'ringa (oxiriga) qo'ysa, bu nimani anglatadi?",
    options: [
      "Depressiyadan to'liq forig' bo'lganlik",
      "Haddan tashqari ko'p uxlash istagi",
      "Xotirjamlik va bog'liqlikdan qochish, ichki osoyishtalikning buzilishi va norozilik",
      "O'ziga bo'lgan ishonchning haddan ziyod balandligi",
    ],
    correctAnswer: "Xotirjamlik va bog'liqlikdan qochish, ichki osoyishtalikning buzilishi va norozilik",
  },
  {
    id: 88,
    question: "Lyusher bo'yicha 'Geteronom' ranglar guruhiga qaysilar kiradi?",
    options: [
      "Binafsharang va oq",
      "Qizil va sariq",
      "Qora va kulrang",
      "Ko'k va yashil (tashqi ta'sirga javob beruvchi va muvozanatlovchi)",
    ],
    correctAnswer: "Ko'k va yashil (tashqi ta'sirga javob beruvchi va muvozanatlovchi)",
  },
  {
    id: 89,
    question: "Lyusher bo'yicha 'Avtonom' ranglar qaysilar hisoblanadi?",
    options: [
      "Qizil va sariq (faol, tashabbuskor va harakatga undovchi)",
      "Ko'k va kulrang",
      "Qora va jigarrang",
      "Binafsharang va ko'k",
    ],
    correctAnswer: "Qizil va sariq (faol, tashabbuskor va harakatga undovchi)",
  },
  {
    id: 90,
    question: "M. Lyusher testini talqin qilishda qaysi xatoga yo'l qo'ymaslik kerak?",
    options: [
      "Ko'rsatmalarni to'liq tushuntirish",
      "Rang tanlovini insonning turg'un fe'l-atvor xarakteri deb mutlaqlashtirish (u ko'proq ayni paytdagi holatni aks ettiradi)",
      "Kartochkalarni toza saqlash",
      "Ikkinchi tanlovni o'tkazish",
    ],
    correctAnswer: "Rang tanlovini insonning turg'un fe'l-atvor xarakteri deb mutlaqlashtirish (u ko'proq ayni paytdagi holatni aks ettiradi)",
  },
  {
    id: 91,
    question: "Interpretativ proyektiv metodlarning asosiy mohiyati nimada?",
    options: [
      "Ranglarni o'zining kayfiyatiga qarab ajratish",
      "Faqat berilgan variantlardan birini mexanik tanlash",
      "Sinovchiga taqdim etilgan stimul yoki vaziyatni ma'lum bir ma'no orqali talqin qilish va izohlash",
      "Mavhum chiziqlarni qog'ozga tushirish",
    ],
    correctAnswer: "Sinovchiga taqdim etilgan stimul yoki vaziyatni ma'lum bir ma'no orqali talqin qilish va izohlash",
  },
  {
    id: 92,
    question: "Lipot Zondi (Szondi) o'z testining nazariy poydevori sifatida qaysi konsepsiyani yaratdi?",
    options: [
      "Gumanistik psixoterapiya",
      "Klassik bixeviorizm",
      "Operant reflektor nazariya",
      "'Taqdir tahlili' (Schicksalsanalyse) va oilaviy (nasliy) ongsizlik nazariyasi",
    ],
    correctAnswer: "'Taqdir tahlili' (Schicksalsanalyse) va oilaviy (nasliy) ongsizlik nazariyasi",
  },
  {
    id: 93,
    question: "L. Zondi testining rag'batlantiruvchi materiali nimalardan iborat?",
    options: [
      "8 ta toifadagi ruhiy kasalliklar bilan og'rigan bemorlarning 48 ta fotosurati (6 ta seriya)",
      "Rangli geometrik shakllar",
      "Turli xil hayvonlarning rasmlari",
      "Yozuvli matn lavhalari",
    ],
    correctAnswer: "8 ta toifadagi ruhiy kasalliklar bilan og'rigan bemorlarning 48 ta fotosurati (6 ta seriya)",
  },
  {
    id: 94,
    question: "Zondi testini o'tkazishda sinaluvchiga qanday vazifa yuklatiladi?",
    options: [
      "Barcha portretlarning kasallik tashxisini topish",
      "Har bir seriyadagi 8 ta portretdan o'ziga eng yoqqan 2 ta va eng yoqmagan 2 ta portretni tanlash",
      "Portretlarning yoshini aniqlash",
      "Rasmlarga qarab qahramonlarning ismini to'qish",
    ],
    correctAnswer: "Har bir seriyadagi 8 ta portretdan o'ziga eng yoqqan 2 ta va eng yoqmagan 2 ta portretni tanlash",
  },
  {
    id: 95,
    question: "L. Zondi nazariyasida inson mayllari (drive) tizimi nechta asosiy vektorga bo'linadi?",
    options: [
      "6 ta vektor: o'tmish, hozir, kelajak, iroda, aql, hissiyot",
      "2 ta vektor: yaxshi va yomon",
      "4 ta vektor: S (jinsiy), P (paroksizmal), Sch (shizoid), C (sirkulyar)",
      "10 ta vektor",
    ],
    correctAnswer: "4 ta vektor: S (jinsiy), P (paroksizmal), Sch (shizoid), C (sirkulyar)",
  },
  {
    id: 96,
    question: "Zondi testidagi 'S' vektori qaysi omillarni o'z ichiga oladi?",
    options: [
      "d (depressiya) va m (maniya)",
      "e (epilepsiya) va hy (isteriya)",
      "k (katatoniya) va p (paranoyya)",
      "h (gomoseksuallik/muloyimlik) va s (sadizm/faollik-tajovuzkorlik)",
    ],
    correctAnswer: "h (gomoseksuallik/muloyimlik) va s (sadizm/faollik-tajovuzkorlik)",
  },
  {
    id: 97,
    question: "Zondi testidagi 'P' (paroksizmal/axloqiy) vektori nimani nazorat qiladi?",
    options: [
      "e (epileptoid g'azab/adolat) va hy (isterik o'zini ko'rsatish/uyat)",
      "h va s omillarini",
      "k va p omillarini",
      "d va m omillarini",
    ],
    correctAnswer: "e (epileptoid g'azab/adolat) va hy (isterik o'zini ko'rsatish/uyat)",
  },
  {
    id: 98,
    question: "Zondi testidagi 'Sch' (shizoid/Men) vektori nimani ifodalaydi?",
    options: [
      "Faqat jinsiy mayllarni",
      "k (katatonik torayish/kapitalizatsiya) va p (paranoyal kengayish/inflyatsiya)",
      "Faqat jismoniy charchoqni",
      "Ijtimoiy munosabatlarni qidirishni",
    ],
    correctAnswer: "k (katatonik torayish/kapitalizatsiya) va p (paranoyal kengayish/inflyatsiya)",
  },
  {
    id: 99,
    question: "Zondi testidagi 'C' (kontakt/sirkulyar) vektori nimani aks ettiradi?",
    options: [
      "O'zini namoyon qilish va rashkni",
      "Tajovuzkorlik va qo'rquvni",
      "d (depressiv bog'lanish/yo'qotish) va m (maniakal yopishish/yangi aloqalar)",
      "Diniy e'tiqod va qat'iyatni",
    ],
    correctAnswer: "d (depressiv bog'lanish/yo'qotish) va m (maniakal yopishish/yangi aloqalar)",
  },
  {
    id: 100,
    question: "Zondi testida tanlangan portretlar orqali qanday professional yo'nalish aniqlanadi?",
    options: [
      "Rahbarlikka mutlaqo yaroqsizligi",
      "Faqat qaysi fanni yaxshi o'zlashtira olishi",
      "Qancha ish haqi olishga loyiqligi",
      "Inson o'zining yashirin mayllari va latent ehtiyojlarini qaysi kasbda sublimatsiya qila olishi",
    ],
    correctAnswer: "Inson o'zining yashirin mayllari va latent ehtiyojlarini qaysi kasbda sublimatsiya qila olishi",
  },
  {
    id: 101,
    question: "Zondi testida omilning 'nol' (0) reaktsiyasi nimani anglatadi?",
    options: [
      "Mazkur maylning to'liq qondirilganligi yoki ayni damda faol emasligini",
      "Ushbu maylning eng kuchli portlash arafasida ekanligini",
      "Sinovchining rasmlarni ko'rmaganligini",
      "Bemorning og'ir patologiyasini",
    ],
    correctAnswer: "Mazkur maylning to'liq qondirilganligi yoki ayni damda faol emasligini",
  },
  {
    id: 102,
    question: "Zondi testida omilning ikkala tomondan ham (+ va -) tanlanishi (ambivalentlik) nimani bildiradi?",
    options: [
      "Insonning mutlaq xotirjamligini",
      "Ushbu mayl bo'yicha kuchli ichki ziddiyat va ikkilanuvchanlik mavjudligini",
      "Sinov jarayonining xato o'tganligini",
      "Shaxsda hech qanday xohish yo'qligini",
    ],
    correctAnswer: "Ushbu mayl bo'yicha kuchli ichki ziddiyat va ikkilanuvchanlik mavjudligini",
  },
  {
    id: 103,
    question: "Saul Rozentsveyg metodikasi nimani o'rganishga qaratilgan?",
    options: [
      "Faqat intellektual salohiyatni",
      "Insonning mantiqiy tafakkurini",
      "Frustratsiya vaziyatlariga bo'lgan reaksiyalar va shaxslararo to'siqlarni yengish usullarini",
      "Ranglarni farqlash qobiliyatini",
    ],
    correctAnswer: "Frustratsiya vaziyatlariga bo'lgan reaksiyalar va shaxslararo to'siqlarni yengish usullarini",
  },
  {
    id: 104,
    question: "S. Rozentsveygning Frustratsiya testida nechta rasm-kartochka mavjud?",
    options: [
      "100 ta savol-javob",
      "10 ta siyoh dog'i",
      "48 ta portret",
      "24 ta komiks ko'rinishidagi vaziyatli rasmlar",
    ],
    correctAnswer: "24 ta komiks ko'rinishidagi vaziyatli rasmlar",
  },
  {
    id: 105,
    question: "Rozentsveyg metodikasidagi rasmlarda nimalar tasvirlangan?",
    options: [
      "Bir qahramon boshqasini ayblagan yoki to'siq yaratgan kundalik ziddiyatli vaziyatlar",
      "Faqat tabiat manzaralari",
      "Kosmik kemalar va mavhum chizmalar",
      "Tarixiy jang lavhalari",
    ],
    correctAnswer: "Bir qahramon boshqasini ayblagan yoki to'siq yaratgan kundalik ziddiyatli vaziyatlar",
  },
  {
    id: 106,
    question: "Rozentsveyg nazariyasiga ko'ra reaksiyalarning nechta asosiy yo'nalishi mavjud?",
    options: [
      "2 ta yo'nalish: faol va sust",
      "3 ta yo'nalish: Ekstrapunitiv (E), Intrapunitiv (I), Impunitiv (M)",
      "4 ta yo'nalish: Shimol, Janub, Sharq, G'arb",
      "5 ta yo'nalish: to'g'ri, noto'g'ri, neytral, ijobiy, salbiy",
    ],
    correctAnswer: "3 ta yo'nalish: Ekstrapunitiv (E), Intrapunitiv (I), Impunitiv (M)",
  },
  {
    id: 107,
    question: "Rozentsveyg testi bo'yicha Ekstrapunitiv (E) reaksiya qanday ifodalanadi?",
    options: [
      "Muammo oddiy deb hisoblanib, unga e'tibor berilmaydi",
      "Inson butun aybni o'z bo'yniga oladi",
      "Ayb tashqi tomonga, boshqa odamlarga yoki vaziyatga yuklanadi, agressiya tashqariga yo'naltiriladi",
      "Shaxs ziddiyatdan qochib sukut saqlaydi",
    ],
    correctAnswer: "Ayb tashqi tomonga, boshqa odamlarga yoki vaziyatga yuklanadi, agressiya tashqariga yo'naltiriladi",
  },
  {
    id: 108,
    question: "Intrapunitiv (I) reaksiyada inson o'zini qanday tutadi?",
    options: [
      "Atrofdagilarni jazolashni talab qiladi",
      "Boshqalarni qattiq haqorat qiladi",
      "Muammoning yechimini taqdirga tashlaydi",
      "Aybni o'ziga oladi, o'zini tanqid qiladi, o'zini aybdor his etadi va javobgarlikni o'z zimmasiga oladi",
    ],
    correctAnswer: "Aybni o'ziga oladi, o'zini tanqid qiladi, o'zini aybdor his etadi va javobgarlikni o'z zimmasiga oladi",
  },
  {
    id: 109,
    question: "Impunitiv (M) reaksiyaning mohiyati nimada?",
    options: [
      "Vaziyatdagi ayb hech kimga yuklanmaydi, to'siq muqarrar yoki arzimas deb qabul qilinadi",
      "O'zini o'zi jazolash kuchayadi",
      "Tashqi olamga nisbatan qasos rejalashtiriladi",
      "Barcha ishtirokchilar qamoqqa olinishi talab etiladi",
    ],
    correctAnswer: "Vaziyatdagi ayb hech kimga yuklanmaydi, to'siq muqarrar yoki arzimas deb qabul qilinadi",
  },
  {
    id: 110,
    question: "Rozentsveyg bo'yicha reaksiyalarning nechta asosiy turi mavjud?",
    options: [
      "Faqat 1 ta tur: Hujumkor",
      "3 ta tur: To'siqqa ustunlik beruvchi (O-D), Egoni himoya qiluvchi (E-D), Ehtiyojni qondirishga qaratilgan (N-P)",
      "2 ta tur: Yaxshi va yomon",
      "4 ta tur: Flegmatik, xolerik, sangvinik, melanxolik",
    ],
    correctAnswer: "3 ta tur: To'siqqa ustunlik beruvchi (O-D), Egoni himoya qiluvchi (E-D), Ehtiyojni qondirishga qaratilgan (N-P)",
  },
  {
    id: 111,
    question: "Rozentsveyg testidagi 'To'siqqa ustunlik beruvchi' (Obstacle-Dominance, O-D) reaksiya nima bilan tavsiflanadi?",
    options: [
      "Inson o'z aybini to'liq tan oladi",
      "Shaxs zudlik bilan muammoning yechimini topadi",
      "Javobda frustratsiyani keltirib chiqargan to'siq va qiyinchilik qayta-qayta ta'kidlanadi",
      "Suhbatdoshiga minnatdorchilik bildiradi",
    ],
    correctAnswer: "Javobda frustratsiyani keltirib chiqargan to'siq va qiyinchilik qayta-qayta ta'kidlanadi",
  },
  {
    id: 112,
    question: "Rozentsveyg testida 'Egoni himoya qiluvchi' (Ego-Defense, E-D) tur qanday namoyon bo'ladi?",
    options: [
      "To'siqqa hech qanday e'tibor qaratilmaydi",
      "O'z manfaatlari butunlay rad etiladi",
      "Barcha aybni jimgina qabul qilinadi",
      "Shaxs o'zining Menini, qadr-qimmatini himoya qilishga qaratilgan oqlanish yoki ayblovlarni ilgari suradi",
    ],
    correctAnswer: "Shaxs o'zining Menini, qadr-qimmatini himoya qilishga qaratilgan oqlanish yoki ayblovlarni ilgari suradi",
  },
  {
    id: 113,
    question: "Rozentsveyg metodikasida 'Ehtiyojni qondirishga qaratilgan' (Need-Persistence, N-P) reaksiya nimani anglatadi?",
    options: [
      "To'siqqa qaramasdan, muammoni hal qilish va maqsadga erishishning konstruktiv yo'lini izlash",
      "Vaziyatdan butunlay voz kechish",
      "Boshqalarga nisbatan dushmanlikni kuchaytirish",
      "O'zini kasalikka solish",
    ],
    correctAnswer: "To'siqqa qaramasdan, muammoni hal qilish va maqsadga erishishning konstruktiv yo'lini izlash",
  },
  {
    id: 114,
    question: "Rozentsveyg testidagi 'Ijtimoiy moslashuv indeksi' (GCR - Group Conformity Rating) nimani ko'rsatadi?",
    options: [
      "Insonning IQ intellekt koeffitsiyentini",
      "Sinovchining javoblari jamiyatdagi standart, me'yoriy javoblarga qanchalik mos kelishini (foizda)",
      "Ruhiy kasallikning og'irlik darajasini",
      "Xotiraning mustahkamligini",
    ],
    correctAnswer: "Sinovchining javoblari jamiyatdagi standart, me'yoriy javoblarga qanchalik mos kelishini (foizda)",
  },
  {
    id: 115,
    question: "GCR ko'rsatkichining me'yordan juda past bo'lishi nimadan dalolat beradi?",
    options: [
      "Jamiyat bilan to'liq hamjihatlik",
      "Haddan tashqari yuqori ijtimoiy qobiliyat",
      "Shaxsning ijtimoiy me'yorlarga moslashishining qiyinligi, noadekvatlik yoki individualistik qarshilik",
      "O'ta yuqori qobiliyatli rahbarlik",
    ],
    correctAnswer: "Shaxsning ijtimoiy me'yorlarga moslashishining qiyinligi, noadekvatlik yoki individualistik qarshilik",
  },
  {
    id: 116,
    question: "Rozentsveyg metodikasi bolalar uchun moslashtirilganmi?",
    options: [
      "Faqat og'ir ruhiy bemorlar uchun ishlab chiqilgan",
      "Yo'q, faqat kattalarda qo'llaniladi",
      "Faqat keksalar uchun mo'ljallangan",
      "Ha, bolalar uchun maxsus moslashtirilgan (bolalar hayotiga oid rasmlar to'plami mavjud)",
    ],
    correctAnswer: "Ha, bolalar uchun maxsus moslashtirilgan (bolalar hayotiga oid rasmlar to'plami mavjud)",
  },
  {
    id: 117,
    question: "Rozentsveyg testida ekstrapunitiv (E) reaksiyalarning haddan tashqari ko'p bo'lishi nimani bildiradi?",
    options: [
      "Tajovuzkorlik, agressivlik, atrofdagilarga nisbatan talabchanlik va o'z xatosini tan olmaslik",
      "O'ta kamtarlik va o'zini kamsitish",
      "Depressiv tushkunlikka moyillik",
      "Befarqlik va apatiya",
    ],
    correctAnswer: "Tajovuzkorlik, agressivlik, atrofdagilarga nisbatan talabchanlik va o'z xatosini tan olmaslik",
  },
  {
    id: 118,
    question: "Zondi testi natijalariga ko'ra insonning patologik xususiyatlarini aniqlashda nima hal qiluvchi hisoblanadi?",
    options: [
      "Faqat bitta rasmning yoqmaganligi",
      "Bir nechta profillarning takroriy tahlili va omillarning keskin taranglashuvi (+ va - 4 dan ortiq bo'lishi)",
      "Testni juda sekin bajarganligi",
      "Sinovchining jinsi va yoshi",
    ],
    correctAnswer: "Bir nechta profillarning takroriy tahlili va omillarning keskin taranglashuvi (+ va - 4 dan ortiq bo'lishi)",
  },
  {
    id: 119,
    question: "S. Rozentsveyg metodikasida frustratsiyaning qanday asosiy turlari farqlanadi?",
    options: [
      "Qishki, yozgi, bahorgi",
      "Kichik, o'rta, katta",
      "Privatsiya (yetishmovchilik), deprivatsiya (yo'qotish) va konflikt (to'qnashuv)",
      "O'quv, mehnat, oilaviy",
    ],
    correctAnswer: "Privatsiya (yetishmovchilik), deprivatsiya (yo'qotish) va konflikt (to'qnashuv)",
  },
  {
    id: 120,
    question: "Interpretativ proyektiv metodlarning diagnostik qimmati qaysi sohada ayniqsa yuqori?",
    options: [
      "Chet tillarini bilish darajasini aniqlashda",
      "Faqat jismoniy tarbiya me'yorlarini qabul qilishda",
      "Avtomobil haydash qoidalarini tekshirishda",
      "Shaxslararo munosabatlar ziddiyatlari, konfliktologiya va klinik korreksiyada",
    ],
    correctAnswer: "Shaxslararo munosabatlar ziddiyatlari, konfliktologiya va klinik korreksiyada",
  },
  {
    id: 121,
    question: "Tematik Apperseptiv Test (TAT) kim tomonidan va qachon yaratilgan?",
    options: [
      "Genri Myurrey va Kristina Morgan tomonidan 1935 yilda",
      "Z. Freyd tomonidan 1900 yilda",
      "G. Rorshax tomonidan 1921 yilda",
      "L. Zondi tomonidan 1947 yilda",
    ],
    correctAnswer: "Genri Myurrey va Kristina Morgan tomonidan 1935 yilda",
  },
  {
    id: 122,
    question: "G. Myurrey shaxs nazariyasida qaysi ikki asosiy tushunchaga tayanadi?",
    options: [
      "Id, Ego va Super-Ego",
      "Shaxsning ehtiyojlari (Needs) va atrof-muhitning bosimi (Press)",
      "Ongli va ongsiz intilishlar",
      "Ekstroversiya va introversiya",
    ],
    correctAnswer: "Shaxsning ehtiyojlari (Needs) va atrof-muhitning bosimi (Press)",
  },
  {
    id: 123,
    question: "TATning standart to'plami nechta rasmli kartochkadan iborat?",
    options: [
      "24 ta kartochka",
      "10 ta kartochka",
      "31 ta kartochka (30 ta rasmli va 1 ta mutlaqo oq kartochka)",
      "48 ta kartochka",
    ],
    correctAnswer: "31 ta kartochka (30 ta rasmli va 1 ta mutlaqo oq kartochka)",
  },
  {
    id: 124,
    question: "TAT kartochkalari sinovdan o'tuvchilarga qanday mezonlarga ko'ra taqsimlanadi?",
    options: [
      "Barcha toifadagi odamlarga barcha kartochkalar mutlaqo bir xil beriladi",
      "Faqat ma'lumoti va kasbiga qarab",
      "Faqat millati va tiliga qarab",
      "Jinsi va yoshiga qarab (Erkaklar - M, Ayollar - F, O'g'il bolalar - B, Qiz bolalar - G va Umumiy)",
    ],
    correctAnswer: "Jinsi va yoshiga qarab (Erkaklar - M, Ayollar - F, O'g'il bolalar - B, Qiz bolalar - G va Umumiy)",
  },
  {
    id: 125,
    question: "TAT testini o'tkazishda sinaluvchiga qanday vazifa beriladi?",
    options: [
      "Rasmga qarab hikoya to'qish: nima sodir bo'lgan, ayni paytda nima bo'lyapti, qahramonlar nimalarni his qilmoqda va yakun qanday bo'ladi",
      "Rasmdagi xatolarni topish",
      "Rasmning muallifini va chizilgan yilini aniqlash",
      "Rasmni aynan o'zidek qog'ozga qayta chizish",
    ],
    correctAnswer: "Rasmga qarab hikoya to'qish: nima sodir bo'lgan, ayni paytda nima bo'lyapti, qahramonlar nimalarni his qilmoqda va yakun qanday bo'ladi",
  },
  {
    id: 126,
    question: "TATdagi mutlaqo 'Oq kartochka'ning vazifasi nimadan iborat?",
    options: [
      "Sinovchining ko'zini dam oldirish",
      "Hech qanday vizual stimulsiz, to'liq o'z tasavvuri va ichki intilishlari asosida mustaqil hikoya yaratish",
      "Test tugaganligini bildirish",
      "Qog'ozga rasm chizib berishni talab qilish",
    ],
    correctAnswer: "Hech qanday vizual stimulsiz, to'liq o'z tasavvuri va ichki intilishlari asosida mustaqil hikoya yaratish",
  },
  {
    id: 127,
    question: "TAT hikoyalarini tahlil qilishda birinchi navbatda nima aniqlanadi?",
    options: [
      "Hikoyaning tinish belgilari to'g'riligi",
      "Hikoyada nechta so'z ishlatilganligi",
      "'Qahramon' (sinovchi o'zini aynan qaysi personaj bilan identifikatsiya qilayotganligi)",
      "Qahramonlarning kiyimidagi tugmalar soni",
    ],
    correctAnswer: "'Qahramon' (sinovchi o'zini aynan qaysi personaj bilan identifikatsiya qilayotganligi)",
  },
  {
    id: 128,
    question: "G. Myurrey bo'yicha TAT tahlilida 'Ehtiyojlar' (Needs) nimani ko'rsatadi?",
    options: [
      "Psixologning sinovchiga bo'lgan munosabatini",
      "Hikoyaning qanchalik tez aytilganini",
      "Sinovdan o'tuvchining jismoniy ehtiyojlarini (ochlik, chanqoqlik)",
      "Qahramonning intilishlari, maqsadlari, istaklari va ichki motivatsion turtkilarini",
    ],
    correctAnswer: "Qahramonning intilishlari, maqsadlari, istaklari va ichki motivatsion turtkilarini",
  },
  {
    id: 129,
    question: "TAT tahlilida 'Atrof-muhit bosimi' (Press) deganda nima tushuniladi?",
    options: [
      "Qahramonga tashqi olamdan (boshqa odamlar yoki sharoitdan) bo'layotgan tahdid, yordam yoki to'siqlar",
      "Xonadagi atmosfera bosimi",
      "Sinovchining partaga tirsagi bilan beradigan bosimi",
      "Hikoyani aytish vaqtidagi shovqinlar",
    ],
    correctAnswer: "Qahramonga tashqi olamdan (boshqa odamlar yoki sharoitdan) bo'layotgan tahdid, yordam yoki to'siqlar",
  },
  {
    id: 130,
    question: "TAT natijalarini qayta ishlashda 'Mavzu' (Thema) nima?",
    options: [
      "Hikoyaning kitobiy nomi",
      "Qahramonning ehtiyoji bilan tashqi muhit bosimining o'zaro to'qnashuvidan kelib chiqadigan dinamik syujet",
      "Sinovchining sevimli adabiy asari",
      "Faqat rasmdagi ob-havo holati",
    ],
    correctAnswer: "Qahramonning ehtiyoji bilan tashqi muhit bosimining o'zaro to'qnashuvidan kelib chiqadigan dinamik syujet",
  },
  {
    id: 131,
    question: "TAT natijalari shaxsni baholashda qaysi sohalarda ayniqsa samarali hisoblanadi?",
    options: [
      "Ko'rish o'tkirligini tekshirishda",
      "Xotira hajmini aniq baytda hisoblashda",
      "Yashirin motivatsiya, ichki konfliktlar, ota-ona munosabatlari va shaxsning himoya mexanizmlarini aniqlashda",
      "Mantiqiy-arifmetik hisob-kitobni o'lchashda",
    ],
    correctAnswer: "Yashirin motivatsiya, ichki konfliktlar, ota-ona munosabatlari va shaxsning himoya mexanizmlarini aniqlashda",
  },
  {
    id: 132,
    question: "L.N. Sobchik tomonidan TATning qanday moslashtirilgan (modifikatsiya) varianti ishlab chiqilgan?",
    options: [
      "Bolalar chizma testi",
      "Rangli portretlar testi",
      "Grafik proyektiv so'rovnoma",
      "Rasmli Apperseptiv Test (RAT)",
    ],
    correctAnswer: "Rasmli Apperseptiv Test (RAT)",
  },
  {
    id: 133,
    question: "L.N. Sobchikning Rasmli Apperseptiv Testi (RAT) qanday xususiyatga ega?",
    options: [
      "Rasmlar zamonaviy hayotga yaqinlashtirilgan, shaxslararo munosabatlar va ichki ziddiyatlarni aniqlashga yo'naltirilgan",
      "Faqat qadimgi ertaklar asosida tuzilgan",
      "Faqat harbiy xizmatchilar uchun mo'ljallangan",
      "Hikoya to'qishni emas, raqamlar qo'yishni talab qiladi",
    ],
    correctAnswer: "Rasmlar zamonaviy hayotga yaqinlashtirilgan, shaxslararo munosabatlar va ichki ziddiyatlarni aniqlashga yo'naltirilgan",
  },
  {
    id: 134,
    question: "Bolalar Apperseptiv Testi (CAT - Children's Apperception Test) kimlar tomonidan yaratilgan?",
    options: [
      "G. Myurrey va K. Morgan tomonidan",
      "Leopold Bellak va Sonya Bellak tomonidan",
      "Z. Freyd va A. Adler tomonidan",
      "M. Lyusher va L. Zondi tomonidan",
    ],
    correctAnswer: "Leopold Bellak va Sonya Bellak tomonidan",
  },
  {
    id: 135,
    question: "Klassik CAT (Bolalar Apperseptiv Testi) kartochkalarida kimlar tasvirlangan?",
    options: [
      "Haqiqiy kattalar va keksalar",
      "Faqat geometrik shakllar",
      "Insoniy vaziyatlarga tushib qolgan hayvonlar (antropomorfik obrazlar)",
      "Mavhum rangli dog'lar",
    ],
    correctAnswer: "Insoniy vaziyatlarga tushib qolgan hayvonlar (antropomorfik obrazlar)",
  },
  {
    id: 136,
    question: "Nima sababdan CAT testida odamlar emas, hayvonlar tasviri tanlangan?",
    options: [
      "Odamlarning rasmlarini bolalarga ko'rsatish taqiqlangani uchun",
      "Hayvonlarni chizish rassom uchun oson bo'lgani uchun",
      "Bolalar odamlardan qattiq qo'rqqanliklari sababli",
      "Kichik yoshdagi bolalar o'zlarini hayvonlar bilan osonroq identifikatsiya qiladilar va bu ongli himoyani kamaytiradi",
    ],
    correctAnswer: "Kichik yoshdagi bolalar o'zlarini hayvonlar bilan osonroq identifikatsiya qiladilar va bu ongli himoyani kamaytiradi",
  },
  {
    id: 137,
    question: "CAT metodikasi asosan necha yoshdagi bolalar uchun mo'ljallangan?",
    options: [
      "3 yoshdan 10 yoshgacha bo'lgan bolalar uchun",
      "10 yoshdan 18 yoshgacha",
      "Faqat 1 yoshgacha bo'lgan chaqaloqlar uchun",
      "Faqat talabalar uchun",
    ],
    correctAnswer: "3 yoshdan 10 yoshgacha bo'lgan bolalar uchun",
  },
  {
    id: 138,
    question: "CAT-H (Children's Apperception Test - Human) varianti qanday o'ziga xoslikka ega?",
    options: [
      "Faqat o'simliklar tasvirlangan",
      "Hayvonlar o'rniga bolalar va odamlar tasvirlangan (katta yoshdagi bolalar va o'smirlar uchun)",
      "Rasmlar butunlay rangsiz qilingan",
      "Savollarga faqat 'ha' yoki 'yo'q' deb javob beriladi",
    ],
    correctAnswer: "Hayvonlar o'rniga bolalar va odamlar tasvirlangan (katta yoshdagi bolalar va o'smirlar uchun)",
  },
  {
    id: 139,
    question: "CAT testi bolalardagi qaysi muammolarni ochishda yetakchi hisoblanadi?",
    options: [
      "Ko'rish va eshitish nuqsonlarini",
      "Matematik qobiliyatlarning yetishmasligini",
      "Ovqatlanish muammolari, aka-uka/opa-singillar rashki, ota-onaga munosabat, qo'rquvlar va agressiya",
      "Chet tilini o'rganishdagi qiyinchiliklarni",
    ],
    correctAnswer: "Ovqatlanish muammolari, aka-uka/opa-singillar rashki, ota-onaga munosabat, qo'rquvlar va agressiya",
  },
  {
    id: 140,
    question: "TATda hikoyaning 'Yakuni' (Outcome) qanday tahlil qilinadi?",
    options: [
      "Sinaluvchining tabassum qilgan-qilmaganiga qarab",
      "Faqat hikoyaning qaysi so'z bilan tugaganiga qarab",
      "Yakuniy gapning uzunligiga qarab",
      "Optimistik, pessimistik yoki noaniqligi orqali shaxsning hayotiy umidlari va muammolarni yechish strategiyasi baholanadi",
    ],
    correctAnswer: "Optimistik, pessimistik yoki noaniqligi orqali shaxsning hayotiy umidlari va muammolarni yechish strategiyasi baholanadi",
  },
  {
    id: 141,
    question: "TATda shaxsning 'Identifikatsiyasi' nimani anglatadi?",
    options: [
      "Sinaluvchi o'zining ichki 'Men'ini, xatti-harakat va tuyg'ularini qahramon obraziga ko'chirishi",
      "Rasm qahramonining pasport ma'lumotlarini aniqlash",
      "Qahramonning yuz tuzilishini o'zinikiga taqqoslash",
      "Rasmdagi xonani o'z uyiga o'xshatish",
    ],
    correctAnswer: "Sinaluvchi o'zining ichki 'Men'ini, xatti-harakat va tuyg'ularini qahramon obraziga ko'chirishi",
  },
  {
    id: 142,
    question: "TAT o'tkazishda psixologning hikoyaga aralashuvi qanday bo'lishi kerak?",
    options: [
      "Hikoyaning qiziqarli joylarini to'ldirib, o'z fikrini aytib turishi kerak",
      "Minimal darajada; faqat sinovchi biror bosqichni unutsa (masalan, yakunini), neytral savol berish mumkin",
      "Bemorning xato fikrlarini darhol tuzatishi lozim",
      "Qahramonga yangi nomlar taklif qilishi kerak",
    ],
    correctAnswer: "Minimal darajada; faqat sinovchi biror bosqichni unutsa (masalan, yakunini), neytral savol berish mumkin",
  },
  {
    id: 143,
    question: "TATda 'Birlamchi ehtiyojlar' (visserogen) va 'Ikkilamchi ehtiyojlar' (psixogen) farqi nima?",
    options: [
      "Birlamchi - kitob o'qish; ikkilamchi - kino ko'rish",
      "Birlamchi - maktabdagi ehtiyojlar; ikkilamchi - uydagi ehtiyojlar",
      "Birlamchi - jismoniy omon qolish ehtiyojlari; ikkilamchi - yutuqqa erishish, mehr-muhabbat, mustaqillik kabi ruhiy ehtiyojlar",
      "Hech qanday farqi yo'q",
    ],
    correctAnswer: "Birlamchi - jismoniy omon qolish ehtiyojlari; ikkilamchi - yutuqqa erishish, mehr-muhabbat, mustaqillik kabi ruhiy ehtiyojlar",
  },
  {
    id: 144,
    question: "TATda shaxsning 'Yutuqqa erishish motivatsiyasi' (Need Achievement)ni o'rgangan mashhur olim kim?",
    options: [
      "L. Zondi",
      "Z. Freyd",
      "G. Rorshax",
      "Devid Makklelland (D. McClelland)",
    ],
    correctAnswer: "Devid Makklelland (D. McClelland)",
  },
  {
    id: 145,
    question: "RAT (Sobchik) metodikasi TATdan qaysi jihati bilan afzalroq hisoblanadi?",
    options: [
      "Bizning ijtimoiy-madaniy muhitimizga ko'proq moslashtirilganligi va qisqaroqligi bilan",
      "Rasmlarning mutlaqo rangsiz emas, harakatlanuvchi ekanligi bilan",
      "Savollarga test shaklida javob berilishi bilan",
      "Faqat bolalarda qo'llanishi bilan",
    ],
    correctAnswer: "Bizning ijtimoiy-madaniy muhitimizga ko'proq moslashtirilganligi va qisqaroqligi bilan",
  },
  {
    id: 146,
    question: "CAT kartochkalaridagi sujetlarda 'Edip kompleksi' qanday o'rganiladi?",
    options: [
      "Faqat o'yinchoqlar tasviri orqali",
      "Ota-ona yotog'i, kattalar bilan o'zaro munosabatlar va raqobat sahnalari aks etgan rasmlar orqali",
      "O'rmondagi yovvoyi hayvonlar jangi orqali",
      "Maktab doskasi oldidagi holat orqali",
    ],
    correctAnswer: "Ota-ona yotog'i, kattalar bilan o'zaro munosabatlar va raqobat sahnalari aks etgan rasmlar orqali",
  },
  {
    id: 147,
    question: "TAT hikoyalarini tahlil qilishda 'Kechikish vaqti' (Latent period) nimani bildiradi?",
    options: [
      "Psixologning savol berish tezligini",
      "Butun testning qancha davom etganini",
      "Kartochka ko'rsatilgandan to birinchi gap boshlanguncha o'tgan vaqt (ichki qarshilik va himoyani ko'rsatadi)",
      "Sinovchining charchoq darajasini",
    ],
    correctAnswer: "Kartochka ko'rsatilgandan to birinchi gap boshlanguncha o'tgan vaqt (ichki qarshilik va himoyani ko'rsatadi)",
  },
  {
    id: 148,
    question: "TAT materiallarini ishlab chiqishda Kristina Morganning hissasi nimada edi?",
    options: [
      "Natijalarni fransuz tiliga tarjima qilishda",
      "Faqat moliyaviy homiylik qilishda",
      "Testni kompyuter dasturiga aylantirishda",
      "Kartochkalardagi dastlabki badiiy rasmlarni chizish va tajribalarni o'tkazishda",
    ],
    correctAnswer: "Kartochkalardagi dastlabki badiiy rasmlarni chizish va tajribalarni o'tkazishda",
  },
  {
    id: 149,
    question: "TAT, RAT va CAT kabi interpretativ metodlarning umumiy psixodiagnostik asosi nima?",
    options: [
      "Apperseptsiya hodisasi - insonning yangi tajribani o'zining o'tmish tajribasi va ehtiyojlari prizmasi orqali idrok etishi",
      "Faqat ko'rish refleksining tezligi",
      "Insonning adabiy va ijodiy qobiliyatini baholash",
      "Nutqdagi grammatik xatolarni aniqlash",
    ],
    correctAnswer: "Apperseptsiya hodisasi - insonning yangi tajribani o'zining o'tmish tajribasi va ehtiyojlari prizmasi orqali idrok etishi",
  },
  {
    id: 150,
    question: "Zamonaviy amaliyotda TAT natijalarini talqin qilishda qaysi yondashuv eng ishonchli sanaladi?",
    options: [
      "Faqat bitta alohida jumlaga tayanib xulosa chiqarish",
      "Miqdoriy (shkalalar bo'yicha baholash) va sifat (klinik-psixologik tahlil) ko'rsatkichlarini uyg'unlashtirish",
      "Sinaluvchining faqat tashqi ko'rinishiga qarab baholash",
      "Barcha hikoyalarni shunchaki umumiy mazmunini aytib berish",
    ],
    correctAnswer: "Miqdoriy (shkalalar bo'yicha baholash) va sifat (klinik-psixologik tahlil) ko'rsatkichlarini uyg'unlashtirish",
  },
];
