import type { Question } from "@/lib/types";

// Source: Profayling test.docx
// The correct answer can be listed in any position; options are shuffled in the test.
export const questions: Question[] = [
  {
    id: 1,
    question: "Profayling tushunchasi nimani anglatadi?",
    options: [
      "Faqat insonning tashqi ko‘rinishini baholash",
      "Shaxsning xulq-atvori va psixologik xususiyatlarini tahlil qilish",
      "Faqat jinoyatlarni tekshirish",
      "Tibbiy tashxis qo‘yish",
    ],
    correctAnswer: "Shaxsning xulq-atvori va psixologik xususiyatlarini tahlil qilish",
  },
  {
    id: 2,
    question: "Profaylingning asosiy maqsadi nima?",
    options: [
      "Shaxs haqida ehtimoliy psixologik xulosa chiqarish",
      "Insonni jazolash",
      "Insonning kasalligini aniqlash",
      "Shaxsning moliyaviy holatini aniqlash",
    ],
    correctAnswer: "Shaxs haqida ehtimoliy psixologik xulosa chiqarish",
  },
  {
    id: 3,
    question: "Profayling qaysi fanlar bilan chambarchas bog‘liq?",
    options: [
      "Psixologiya, kriminalistika va kommunikatsiya",
      "Faqat matematika",
      "Faqat geografiya",
      "Faqat biologiya",
    ],
    correctAnswer: "Psixologiya, kriminalistika va kommunikatsiya",
  },
  {
    id: 4,
    question: "Profaylingda “profil” tushunchasi nimani bildiradi?",
    options: [
      "Shaxsning ehtimoliy xususiyatlari majmui",
      "Shaxsning pasporti",
      "Shaxsning fotosurati",
      "Shaxsning ish joyi",
    ],
    correctAnswer: "Shaxsning ehtimoliy xususiyatlari majmui",
  },
  {
    id: 5,
    question: "Profaylingda kuzatuv nima uchun muhim?",
    options: [
      "Xulq-atvor belgilarini aniqlash uchun",
      "Faqat suhbatni tezlashtirish uchun",
      "Hujjatlarni tekshirish uchun",
      "Shaxsni jazolash uchun",
    ],
    correctAnswer: "Xulq-atvor belgilarini aniqlash uchun",
  },
  {
    id: 6,
    question: "Profaylingda gipoteza nima?",
    options: [
      "Tekshirilishi mumkin bo‘lgan taxmin",
      "Aniq hukm",
      "Qonuniy jazo",
      "Tibbiy tashxis",
    ],
    correctAnswer: "Tekshirilishi mumkin bo‘lgan taxmin",
  },
  {
    id: 7,
    question: "Profaylingda stereotiplardan foydalanish qanday oqibatga olib kelishi mumkin?",
    options: [
      "Tahlilning aniqligini oshiradi",
      "Noto‘g‘ri xulosalarga olib kelishi mumkin",
      "Har doim to‘g‘ri natija beradi",
      "Muloqotni yaxshilaydi",
    ],
    correctAnswer: "Noto‘g‘ri xulosalarga olib kelishi mumkin",
  },
  {
    id: 8,
    question: "Profaylingda “bazaviy holat” (baseline) nima?",
    options: [
      "Shaxsning odatiy xulq-atvor holati",
      "Jinoyat joyi",
      "Suhbatning yakuniy bosqichi",
      "Shaxsning kasbi",
    ],
    correctAnswer: "Shaxsning odatiy xulq-atvor holati",
  },
  {
    id: 9,
    question: "Profayling tahlilida kontekst nima uchun kerak?",
    options: [
      "Xatti-harakatni vaziyat bilan bog‘lab baholash uchun",
      "Faqat statistik ma’lumot olish uchun",
      "Suhbatni to‘xtatish uchun",
      "Shaxsni jazolash uchun",
    ],
    correctAnswer: "Xatti-harakatni vaziyat bilan bog‘lab baholash uchun",
  },
  {
    id: 10,
    question: "Profaylingdagi eng muhim tamoyillardan biri qaysi?",
    options: [
      "Birgina belgiga asoslanib xulosa qilish",
      "Bir nechta belgilarni kompleks tahlil qilish",
      "Faqat tashqi ko‘rinishga qarash",
      "Faqat taxmin qilish",
    ],
    correctAnswer: "Bir nechta belgilarni kompleks tahlil qilish",
  },
  {
    id: 11,
    question: "Profayling natijasi odatda qanday xarakterga ega?",
    options: [
      "Ehtimoliy",
      "Mutlaq",
      "O‘zgarmas",
      "Huquqiy hukm",
    ],
    correctAnswer: "Ehtimoliy",
  },
  {
    id: 12,
    question: "Shaxs xulq-atvorini baholashda eng to‘g‘ri yondashuv qaysi?",
    options: [
      "Bir martalik belgiga qarash",
      "Vaziyat, kontekst va bir nechta belgilarni hisobga olish",
      "Faqat kiyimiga qarash",
      "Faqat ovoziga qarash",
    ],
    correctAnswer: "Vaziyat, kontekst va bir nechta belgilarni hisobga olish",
  },
  {
    id: 13,
    question: "Profayling qaysi jarayonga ko‘proq asoslanadi?",
    options: [
      "Kuzatuv va tahlilga",
      "Tasodifga",
      "Taxminiy hukmga",
      "Faqat so‘rovnomaga",
    ],
    correctAnswer: "Kuzatuv va tahlilga",
  },
  {
    id: 14,
    question: "Psixologik profil nima?",
    options: [
      "Shaxsning psixologik va xulqiy xususiyatlari tavsifi",
      "Shaxsning kiyimlar ro‘yxati",
      "Tibbiy karta",
      "Pasport nusxasi",
    ],
    correctAnswer: "Shaxsning psixologik va xulqiy xususiyatlari tavsifi",
  },
  {
    id: 15,
    question: "Profaylingda obyektivlik nima?",
    options: [
      "Shaxsga nisbatan shaxsiy qarashlardan imkon qadar xoli baholash",
      "Faqat salbiy belgilarni ko‘rish",
      "Birinchi taassurotga ishonish",
      "Shaxsni oldindan ayblash",
    ],
    correctAnswer: "Shaxsga nisbatan shaxsiy qarashlardan imkon qadar xoli baholash",
  },
  {
    id: 16,
    question: "Birinchi taassurot profaylingda qanday baholanadi?",
    options: [
      "Yakuniy xulosa sifatida",
      "Qo‘shimcha signal sifatida",
      "Mutlaq haqiqat sifatida",
      "Umuman kerak emas",
    ],
    correctAnswer: "Qo‘shimcha signal sifatida",
  },
  {
    id: 17,
    question: "Profaylingda empatiya nima uchun kerak?",
    options: [
      "Shaxsning holatini yaxshiroq tushunish uchun",
      "Shaxsni aldash uchun",
      "Uni qo‘rqitish uchun",
      "Suhbatni tugatish uchun",
    ],
    correctAnswer: "Shaxsning holatini yaxshiroq tushunish uchun",
  },
  {
    id: 18,
    question: "Profaylingda xulq-atvor signali nimani anglatadi?",
    options: [
      "Shaxs xatti-harakatidagi kuzatiladigan belgi",
      "Faqat so‘z",
      "Faqat kiyim",
      "Faqat yuz ifodasi",
    ],
    correctAnswer: "Shaxs xatti-harakatidagi kuzatiladigan belgi",
  },
  {
    id: 19,
    question: "Profaylingning ilmiy yondashuvi nimani talab qiladi?",
    options: [
      "Dalil va kuzatuvlarga tayanishni",
      "Mish-mishlarga tayanishni",
      "Stereotiplardan foydalanishni",
      "Birinchi taassurotni mutlaq deb bilishni",
    ],
    correctAnswer: "Dalil va kuzatuvlarga tayanishni",
  },
  {
    id: 20,
    question: "Profaylingda noto‘g‘ri xulosa xavfini kamaytirish uchun nima qilish kerak?",
    options: [
      "Bir nechta manbadan ma’lumot yig‘ish",
      "Faqat bitta belgiga tayanish",
      "Taxminni fakt deb qabul qilish",
      "Shaxsni oldindan baholash",
    ],
    correctAnswer: "Bir nechta manbadan ma’lumot yig‘ish",
  },
  {
    id: 21,
    question: "Verbal kommunikatsiya nima?",
    options: [
      "So‘zlar orqali muloqot",
      "Faqat imo-ishoralar",
      "Faqat yuz ifodasi",
      "Tana holati",
    ],
    correctAnswer: "So‘zlar orqali muloqot",
  },
  {
    id: 22,
    question: "Noverbal kommunikatsiyaga qaysi biri kiradi?",
    options: [
      "Imo-ishora va mimika",
      "Matn mazmuni",
      "Yozma ariza",
      "Og‘zaki nutq",
    ],
    correctAnswer: "Imo-ishora va mimika",
  },
  {
    id: 23,
    question: "Mimika nima?",
    options: [
      "Yuz ifodalari orqali hissiyotlarni namoyon qilish",
      "Ovoz balandligi",
      "Yozma nutq",
      "Qo‘l yozuvi",
    ],
    correctAnswer: "Yuz ifodalari orqali hissiyotlarni namoyon qilish",
  },
  {
    id: 24,
    question: "Kinesika nimani o‘rganadi?",
    options: [
      "Tana harakatlari va imo-ishoralarni",
      "Ovoz tovushlarini",
      "Matn tuzilishini",
      "Nafas olishni",
    ],
    correctAnswer: "Tana harakatlari va imo-ishoralarni",
  },
  {
    id: 25,
    question: "Proksemika nima bilan bog‘liq?",
    options: [
      "Shaxslararo masofa va makondan foydalanish",
      "Yuz ifodasi",
      "Ovoz tembri",
      "So‘z boyligi",
    ],
    correctAnswer: "Shaxslararo masofa va makondan foydalanish",
  },
  {
    id: 26,
    question: "Paralingvistik belgiga qaysi biri misol bo‘ladi?",
    options: [
      "Ovoz tembri va tezligi",
      "Kiyim rangi",
      "Qo‘l harakati",
      "Ko‘z rangi",
    ],
    correctAnswer: "Ovoz tembri va tezligi",
  },
  {
    id: 27,
    question: "Ko‘z bilan aloqa qilish nimani ifodalashi mumkin?",
    options: [
      "E’tibor va muloqotga jalb qilinganlikni",
      "Har doim yolg‘onni",
      "Har doim qo‘rquvni",
      "Har doim tajovuzni",
    ],
    correctAnswer: "E’tibor va muloqotga jalb qilinganlikni",
  },
  {
    id: 28,
    question: "Qo‘llarni ko‘krakda chalishtirish nimani anglatadi?",
    options: [
      "Har doim yolg‘onni",
      "Har doim himoyalanishni",
      "Kontekstga qarab turlicha ma’no berishi mumkin",
      "Har doim xotirjamlikni",
    ],
    correctAnswer: "Kontekstga qarab turlicha ma’no berishi mumkin",
  },
  {
    id: 29,
    question: "Nutq tezligining keskin o‘zgarishi nimani ko‘rsatishi mumkin?",
    options: [
      "Hissiy zo‘riqish yoki vaziyat o‘zgarishini",
      "Har doim yolg‘onni",
      "Aql darajasini",
      "Kasbni",
    ],
    correctAnswer: "Hissiy zo‘riqish yoki vaziyat o‘zgarishini",
  },
  {
    id: 30,
    question: "Ovoz balandligi nimaga bog‘liq bo‘lishi mumkin?",
    options: [
      "Hissiy holat va vaziyatga",
      "Faqat yoshga",
      "Faqat jinsga",
      "Faqat kasbga",
    ],
    correctAnswer: "Hissiy holat va vaziyatga",
  },
  {
    id: 31,
    question: "Noverbal signalni baholashda eng muhim omil nima?",
    options: [
      "Kontekst",
      "Faqat bitta harakat",
      "Kiyim",
      "Soch turmagi",
    ],
    correctAnswer: "Kontekst",
  },
  {
    id: 32,
    question: "“Cluster” tamoyili nimani anglatadi?",
    options: [
      "Bir nechta belgilarni birgalikda tahlil qilish",
      "Bitta belgiga qarash",
      "Faqat nutqni tahlil qilish",
      "Faqat yuzni kuzatish",
    ],
    correctAnswer: "Bir nechta belgilarni birgalikda tahlil qilish",
  },
  {
    id: 33,
    question: "Noverbal signalning verbal mazmun bilan mos kelmasligi nima deyiladi?",
    options: [
      "Kongruentlik",
      "Nomuvofiqlik",
      "Simmetriya",
      "Rezonans",
    ],
    correctAnswer: "Nomuvofiqlik",
  },
  {
    id: 34,
    question: "Aktiv tinglashning belgisi qaysi?",
    options: [
      "Suhbatdoshning gapini bo‘lmaslik va aniqlashtiruvchi savollar berish",
      "Doimo gapirish",
      "Ko‘z kontaktidan qochish",
      "Suhbatni tez tugatish",
    ],
    correctAnswer: "Suhbatdoshning gapini bo‘lmaslik va aniqlashtiruvchi savollar berish",
  },
  {
    id: 35,
    question: "Paralingvistika nimani o‘rganadi?",
    options: [
      "Nutqning ovozga oid xususiyatlarini",
      "Tana tuzilishini",
      "Kiyimni",
      "Faqat so‘z ma’nosini",
    ],
    correctAnswer: "Nutqning ovozga oid xususiyatlarini",
  },
  {
    id: 36,
    question: "Pauza kommunikatsiyada nimani bildirishi mumkin?",
    options: [
      "O‘ylash, ikkilanish yoki hissiy holatni",
      "Har doim yolg‘onni",
      "Har doim ishonchni",
      "Hech qanday ma’noni",
    ],
    correctAnswer: "O‘ylash, ikkilanish yoki hissiy holatni",
  },
  {
    id: 37,
    question: "Yuzdagi mikroifodalar nima?",
    options: [
      "Juda qisqa davom etadigan yuz ifodalari",
      "Uzoq davom etuvchi harakatlar",
      "Qo‘l harakatlari",
      "Ovoz o‘zgarishlari",
    ],
    correctAnswer: "Juda qisqa davom etadigan yuz ifodalari",
  },
  {
    id: 38,
    question: "Suhbatdoshning gavda holati nimani tahlil qilishda yordam beradi?",
    options: [
      "Uning muloqotdagi holati va komfortini",
      "Uning aniq niyatini",
      "Uning kelajakdagi xatti-harakatini",
      "Uning kasalligini",
    ],
    correctAnswer: "Uning muloqotdagi holati va komfortini",
  },
  {
    id: 39,
    question: "Noverbal belgilarni noto‘g‘ri talqin qilishga nima sabab bo‘lishi mumkin?",
    options: [
      "Madaniy farqlar",
      "Faqat ob-havo",
      "Faqat yosh",
      "Faqat kasb",
    ],
    correctAnswer: "Madaniy farqlar",
  },
  {
    id: 40,
    question: "Verbal va noverbal kommunikatsiya tahlilida qaysi yondashuv to‘g‘ri?",
    options: [
      "Ikkalasini birgalikda baholash",
      "Faqat tana harakatlarini baholash",
      "Faqat so‘zlarni baholash",
      "Faqat ko‘z kontaktini baholash",
    ],
    correctAnswer: "Ikkalasini birgalikda baholash",
  },
  {
    id: 41,
    question: "Kuzatuvning asosiy vazifasi nima?",
    options: [
      "Xulq-atvorni tizimli qayd etish",
      "Shaxsni jazolash",
      "Shaxsni qo‘rqitish",
      "Suhbatni to‘xtatish",
    ],
    correctAnswer: "Xulq-atvorni tizimli qayd etish",
  },
  {
    id: 42,
    question: "Kuzatuvchi nimadan ehtiyot bo‘lishi kerak?",
    options: [
      "Subyektiv baholashdan",
      "Faktlardan",
      "Savollardan",
      "Tinglashdan",
    ],
    correctAnswer: "Subyektiv baholashdan",
  },
  {
    id: 43,
    question: "Suhbatning samarali usullaridan biri qaysi?",
    options: [
      "Ochiq savollar berish",
      "Faqat “ha/yo‘q” savollar berish",
      "Suhbatdoshni bo‘lish",
      "Bosim o‘tkazish",
    ],
    correctAnswer: "Ochiq savollar berish",
  },
  {
    id: 44,
    question: "Ochiq savol qanday savol?",
    options: [
      "Kengroq javob berishni talab qiladigan savol",
      "Faqat “ha” bilan javob beriladigan savol",
      "Faqat “yo‘q” bilan javob beriladigan savol",
      "Javobsiz savol",
    ],
    correctAnswer: "Kengroq javob berishni talab qiladigan savol",
  },
  {
    id: 45,
    question: "Emotsional holat nima?",
    options: [
      "Shaxsning muayyan vaqtdagi hissiy kechinmalari",
      "Faqat xarakter",
      "Faqat intellekt",
      "Faqat tashqi ko‘rinish",
    ],
    correctAnswer: "Shaxsning muayyan vaqtdagi hissiy kechinmalari",
  },
  {
    id: 46,
    question: "Stress holatining belgilaridan biri qaysi?",
    options: [
      "Bezovtalik va fiziologik qo‘zg‘alish",
      "Har doim kulish",
      "Har doim xotirjamlik",
      "Har doim uyquchanlik",
    ],
    correctAnswer: "Bezovtalik va fiziologik qo‘zg‘alish",
  },
  {
    id: 47,
    question: "Qo‘rquv qanday emotsiya?",
    options: [
      "Xavfga javoban yuzaga keladigan emotsiya",
      "Faqat ijobiy emotsiya",
      "Kognitiv jarayon emas",
      "Har doim yolg‘on belgisi",
    ],
    correctAnswer: "Xavfga javoban yuzaga keladigan emotsiya",
  },
  {
    id: 48,
    question: "G‘azabning namoyon bo‘lishiga qaysi biri misol?",
    options: [
      "Ovozning keskinlashishi",
      "Har doim kulish",
      "Uyqu",
      "Jim o‘tirish",
    ],
    correctAnswer: "Ovozning keskinlashishi",
  },
  {
    id: 49,
    question: "Suhbat davomida shaxsning xatti-harakati o‘zgarishi nimani ko‘rsatishi mumkin?",
    options: [
      "Muayyan mavzu unga hissiy ta’sir qilganini",
      "Har doim yolg‘on gapirganini",
      "Har doim jinoyatchi ekanini",
      "Uning kasbini",
    ],
    correctAnswer: "Muayyan mavzu unga hissiy ta’sir qilganini",
  },
  {
    id: 50,
    question: "“Baseline”ni aniqlashning foydasi nimada?",
    options: [
      "Odatdagi xulqni keyingi o‘zgarishlar bilan solishtirish imkonini beradi",
      "Shaxsni avtomatik aybdor qiladi",
      "Yolg‘onni aniq topadi",
      "Tashxis qo‘yadi",
    ],
    correctAnswer: "Odatdagi xulqni keyingi o‘zgarishlar bilan solishtirish imkonini beradi",
  },
  {
    id: 51,
    question: "Empatik tinglash nima?",
    options: [
      "Suhbatdoshning hislarini tushunishga intilib tinglash",
      "Suhbatdoshni tanqid qilish",
      "Uning gapini bo‘lish",
      "Faqat javob tayyorlash",
    ],
    correctAnswer: "Suhbatdoshning hislarini tushunishga intilib tinglash",
  },
  {
    id: 52,
    question: "Suhbatda neytral ohang nima uchun muhim?",
    options: [
      "Suhbatdoshning erkinroq javob berishiga yordam beradi",
      "Uni qo‘rqitadi",
      "Uni chalg‘itadi",
      "Suhbatni to‘xtatadi",
    ],
    correctAnswer: "Suhbatdoshning erkinroq javob berishiga yordam beradi",
  },
  {
    id: 53,
    question: "Emotsional holatni baholashda qaysi omillar hisobga olinadi?",
    options: [
      "Yuz ifodasi, ovoz, tana holati va nutq",
      "Faqat kiyim",
      "Faqat bo‘y",
      "Faqat yosh",
    ],
    correctAnswer: "Yuz ifodasi, ovoz, tana holati va nutq",
  },
  {
    id: 54,
    question: "Stress har doim nimani anglatadi?",
    options: [
      "Yolg‘onni",
      "Organizmning zo‘riqishga javobini",
      "Jinoyatni",
      "Aybdorlikni",
    ],
    correctAnswer: "Organizmning zo‘riqishga javobini",
  },
  {
    id: 55,
    question: "Kuzatuv natijalarini qayd etishda nima muhim?",
    options: [
      "Faktni talqindan ajratish",
      "Taxminni fakt deb yozish",
      "Shaxsiy fikrni asosiy qilish",
      "Stereotipdan foydalanish",
    ],
    correctAnswer: "Faktni talqindan ajratish",
  },
  {
    id: 56,
    question: "Suhbatda “faol tinglash”ning tarkibiy qismi qaysi?",
    options: [
      "Aniqlashtiruvchi savollar",
      "Doimiy tanqid",
      "Suhbatni bo‘lish",
      "Mavzuni o‘zgartirish",
    ],
    correctAnswer: "Aniqlashtiruvchi savollar",
  },
  {
    id: 57,
    question: "Emotsiyani aniqlashda eng to‘g‘ri usul qaysi?",
    options: [
      "Bir nechta belgilar va kontekstni hisobga olish",
      "Faqat yuz ifodasiga qarash",
      "Faqat ovozga qarash",
      "Faqat ko‘z kontaktiga qarash",
    ],
    correctAnswer: "Bir nechta belgilar va kontekstni hisobga olish",
  },
  {
    id: 58,
    question: "Suhbatdoshning uzoq pauza qilishi nimani anglatishi mumkin?",
    options: [
      "O‘ylash yoki hissiy zo‘riqishni",
      "Har doim yolg‘onni",
      "Har doim aybdorlikni",
      "Hech qachon hech narsani",
    ],
    correctAnswer: "O‘ylash yoki hissiy zo‘riqishni",
  },
  {
    id: 59,
    question: "Kuzatuvda “selektiv e’tibor” nima?",
    options: [
      "Ayrim belgilarni boshqalaridan ko‘ra ko‘proq ajratib kuzatish",
      "Hammasini teng ko‘rish",
      "Hech narsani kuzatmaslik",
      "Faqat suhbatni yozib olish",
    ],
    correctAnswer: "Ayrim belgilarni boshqalaridan ko‘ra ko‘proq ajratib kuzatish",
  },
  {
    id: 60,
    question: "Emotsional holatni tahlil qilishda madaniy omillarni hisobga olish kerakmi?",
    options: [
      "Ha",
      "Yo‘q",
      "Faqat bolalarda",
      "Faqat erkaklarda",
    ],
    correctAnswer: "Ha",
  },
  {
    id: 61,
    question: "Shaxs profili nima?",
    options: [
      "Shaxsning xulqiy va psixologik xususiyatlari haqidagi tizimli tavsif",
      "Faqat fotosurat",
      "Faqat pasport",
      "Faqat kasbiy ma’lumot",
    ],
    correctAnswer: "Shaxsning xulqiy va psixologik xususiyatlari haqidagi tizimli tavsif",
  },
  {
    id: 62,
    question: "Aldamchi kommunikatsiya nima?",
    options: [
      "Haqiqatga mos kelmaydigan ma’lumotni ataylab yetkazish",
      "Faqat jim turish",
      "Oddiy suhbat",
      "Tinglash jarayoni",
    ],
    correctAnswer: "Haqiqatga mos kelmaydigan ma’lumotni ataylab yetkazish",
  },
  {
    id: 63,
    question: "Yolg‘onni aniqlashda faqat bitta noverbal belgiga tayanish to‘g‘rimi?",
    options: [
      "Ha",
      "Yo‘q",
      "Faqat suhbatda",
      "Faqat intervyuda",
    ],
    correctAnswer: "Yo‘q",
  },
  {
    id: 64,
    question: "Aldamchi kommunikatsiyani tahlil qilishda “kognitiv yuklama” nima?",
    options: [
      "Javobni shakllantirish uchun sarflanadigan aqliy resurslarning ortishi",
      "Jismoniy charchoq",
      "Uyqu holati",
      "Tashqi bosim",
    ],
    correctAnswer: "Javobni shakllantirish uchun sarflanadigan aqliy resurslarning ortishi",
  },
  {
    id: 65,
    question: "Javob berish vaqtining o‘zgarishi nimani ko‘rsatishi mumkin?",
    options: [
      "Kognitiv yuklama yoki hissiy holat o‘zgarishini",
      "Har doim yolg‘onni",
      "Har doim aybdorlikni",
      "Kasbni",
    ],
    correctAnswer: "Kognitiv yuklama yoki hissiy holat o‘zgarishini",
  },
  {
    id: 66,
    question: "Aldamchi kommunikatsiyada nutqning haddan tashqari batafsil bo‘lishi nimani anglatadi?",
    options: [
      "Ba’zi holatlarda boshqaruv yoki o‘zini oqlashga urinish bo‘lishi mumkin",
      "Har doim yolg‘on",
      "Har doim haqiqat",
      "Hech qanday ma’no bermaydi",
    ],
    correctAnswer: "Ba’zi holatlarda boshqaruv yoki o‘zini oqlashga urinish bo‘lishi mumkin",
  },
  {
    id: 67,
    question: "“Leakage” tushunchasi nimani anglatadi?",
    options: [
      "Nazorat qilinmagan hissiy yoki xulqiy signalning chiqib ketishi",
      "Ma’lumotni o‘chirish",
      "Suhbatni tugatish",
      "Yozuvni yo‘qotish",
    ],
    correctAnswer: "Nazorat qilinmagan hissiy yoki xulqiy signalning chiqib ketishi",
  },
  {
    id: 68,
    question: "Aldamchi kommunikatsiyani tahlil qilishda savollar qanday bo‘lishi kerak?",
    options: [
      "Mantiqiy va aniqlashtiruvchi",
      "Qo‘rqituvchi",
      "Haqoratli",
      "Bosimga asoslangan",
    ],
    correctAnswer: "Mantiqiy va aniqlashtiruvchi",
  },
  {
    id: 69,
    question: "Shaxs profilini tuzishda qaysi ma’lumot muhim?",
    options: [
      "Xulq-atvor, kommunikatsiya va vaziyatga mos reaksiyalar",
      "Faqat tashqi ko‘rinish",
      "Faqat kiyim",
      "Faqat ism",
    ],
    correctAnswer: "Xulq-atvor, kommunikatsiya va vaziyatga mos reaksiyalar",
  },
  {
    id: 70,
    question: "Yolg‘onning universal noverbal belgisi mavjudmi?",
    options: [
      "Ha",
      "Yo‘q",
      "Faqat ko‘zda mavjud",
      "Faqat qo‘lda mavjud",
    ],
    correctAnswer: "Yo‘q",
  },
  {
    id: 71,
    question: "Ko‘z kontaktidan qochish har doim nimani anglatadi?",
    options: [
      "Yolg‘onni",
      "Hech qachon yolg‘onni",
      "Buni kontekstsiz aniqlab bo‘lmaydi",
      "Aybdorlikni",
    ],
    correctAnswer: "Buni kontekstsiz aniqlab bo‘lmaydi",
  },
  {
    id: 72,
    question: "Shaxsning oldingi xulqi nima uchun muhim?",
    options: [
      "Bazaviy holatni aniqlash uchun",
      "Uni ayblash uchun",
      "Uni qo‘rqitish uchun",
      "Uni jazolash uchun",
    ],
    correctAnswer: "Bazaviy holatni aniqlash uchun",
  },
  {
    id: 73,
    question: "Aldamchi kommunikatsiyada verbal va noverbal nomuvofiqlik nimani bildirishi mumkin?",
    options: [
      "Qo‘shimcha tekshiruv talab qiladigan signalni",
      "Aniq yolg‘onni",
      "Jinoyatni",
      "Aybdorlikni",
    ],
    correctAnswer: "Qo‘shimcha tekshiruv talab qiladigan signalni",
  },
  {
    id: 74,
    question: "Shaxs profilida “motiv” nimani anglatadi?",
    options: [
      "Xatti-harakatni yuzaga keltiruvchi ehtimoliy sabab",
      "Tashqi ko‘rinish",
      "Ovoz balandligi",
      "Tana holati",
    ],
    correctAnswer: "Xatti-harakatni yuzaga keltiruvchi ehtimoliy sabab",
  },
  {
    id: 75,
    question: "Aldamchi kommunikatsiyani aniqlashda kontekst nima uchun muhim?",
    options: [
      "Xatti-harakatning sababini to‘g‘riroq talqin qilish uchun",
      "Har doim yolg‘onni aniqlash uchun",
      "Faqat vaqtni aniqlash uchun",
      "Suhbatni to‘xtatish uchun",
    ],
    correctAnswer: "Xatti-harakatning sababini to‘g‘riroq talqin qilish uchun",
  },
  {
    id: 76,
    question: "Shaxsning hikoyasidagi ichki nomuvofiqlik nimani anglatishi mumkin?",
    options: [
      "Qo‘shimcha tekshirishga ehtiyoj borligini",
      "Aniq yolg‘onni",
      "Aybdorlikni",
      "Jinoyatni",
    ],
    correctAnswer: "Qo‘shimcha tekshirishga ehtiyoj borligini",
  },
  {
    id: 77,
    question: "Yolg‘onni aniqlashda fiziologik belgilar qanday baholanadi?",
    options: [
      "Ehtiyotkorlik bilan, chunki ular stressning boshqa sabablaridan ham kelib chiqishi mumkin",
      "Har doim yolg‘on deb",
      "Faqat bitta belgi asosida",
      "Umuman tekshirilmaydi",
    ],
    correctAnswer: "Ehtiyotkorlik bilan, chunki ular stressning boshqa sabablaridan ham kelib chiqishi mumkin",
  },
  {
    id: 78,
    question: "Aldamchi kommunikatsiyani tahlil qilishda “cluster” yondashuvi nima?",
    options: [
      "Bir nechta signalni birgalikda baholash",
      "Faqat ko‘zga qarash",
      "Faqat ovozni tinglash",
      "Faqat so‘zlarni tekshirish",
    ],
    correctAnswer: "Bir nechta signalni birgalikda baholash",
  },
  {
    id: 79,
    question: "Shaxsning javobni o‘zgartirishi nimani ko‘rsatishi mumkin?",
    options: [
      "Xotira, noaniqlik yoki strategik javob berish kabi turli sabablarni",
      "Har doim yolg‘onni",
      "Har doim aybdorlikni",
      "Hech qanday sababni",
    ],
    correctAnswer: "Xotira, noaniqlik yoki strategik javob berish kabi turli sabablarni",
  },
  {
    id: 80,
    question: "Profaylingda “shubha” qanday qo‘llanishi kerak?",
    options: [
      "Tekshiruv uchun gipoteza sifatida",
      "Yakuniy hukm sifatida",
      "Ayblov sifatida",
      "Jazolash vositasi sifatida",
    ],
    correctAnswer: "Tekshiruv uchun gipoteza sifatida",
  },
  {
    id: 81,
    question: "Profaylingning etik tamoyili nimani talab qiladi?",
    options: [
      "Inson huquqlari va qadr-qimmatini hurmat qilishni",
      "Shaxsni kamsitishni",
      "Maxfiy ma’lumotni tarqatishni",
      "Stereotipdan foydalanishni",
    ],
    correctAnswer: "Inson huquqlari va qadr-qimmatini hurmat qilishni",
  },
  {
    id: 82,
    question: "Profaylingda diskriminatsiya nima?",
    options: [
      "Shaxsni asossiz ravishda ma’lum guruhga mansubligi asosida turlicha baholash",
      "Kuzatuv",
      "Suhbat",
      "Psixologik tahlil",
    ],
    correctAnswer: "Shaxsni asossiz ravishda ma’lum guruhga mansubligi asosida turlicha baholash",
  },
  {
    id: 83,
    question: "Shaxsiy ma’lumotlar bilan ishlashda nima muhim?",
    options: [
      "Maxfiylikni ta’minlash",
      "Ma’lumotni hammaga tarqatish",
      "Internetga joylash",
      "Ruxsatsiz foydalanish",
    ],
    correctAnswer: "Maxfiylikni ta’minlash",
  },
  {
    id: 84,
    question: "Profayling natijasidan foydalanishda eng katta xavflardan biri nima?",
    options: [
      "Noto‘g‘ri stereotip va xulosalarga olib kelishi",
      "Suhbatni yaxshilashi",
      "Ma’lumotni ko‘paytirishi",
      "Tinglashni yaxshilashi",
    ],
    correctAnswer: "Noto‘g‘ri stereotip va xulosalarga olib kelishi",
  },
  {
    id: 85,
    question: "Zamonaviy profaylingda texnologiyalarning o‘rni qanday?",
    options: [
      "Ma’lumotlarni tahlil qilishni qo‘llab-quvvatlashi mumkin",
      "Inson tahlilini har doim to‘liq almashtiradi",
      "Hech qanday o‘rni yo‘q",
      "Faqat hujjat yozadi",
    ],
    correctAnswer: "Ma’lumotlarni tahlil qilishni qo‘llab-quvvatlashi mumkin",
  },
  {
    id: 86,
    question: "Sun’iy intellekt asosidagi profaylingning xavflaridan biri qaysi?",
    options: [
      "Algoritmik tarafkashlik",
      "Har doim 100% aniqlik",
      "Ma’lumotning avtomatik to‘g‘riligi",
      "Inson omilining butunlay yo‘qolishi",
    ],
    correctAnswer: "Algoritmik tarafkashlik",
  },
  {
    id: 87,
    question: "Algoritmik tarafkashlik nima?",
    options: [
      "Tizimning ma’lum guruhlarga nisbatan muntazam noxolis natija berishi",
      "Kompyuterning tez ishlashi",
      "Ma’lumotni saqlash",
      "Dastur yangilanishi",
    ],
    correctAnswer: "Tizimning ma’lum guruhlarga nisbatan muntazam noxolis natija berishi",
  },
  {
    id: 88,
    question: "Profaylerning kasbiy mas’uliyati nimani o‘z ichiga oladi?",
    options: [
      "Dalillarga asoslangan va ehtiyotkor xulosa chiqarishni",
      "Har bir odamni gumon qilishni",
      "Stereotiplarni kuchaytirishni",
      "Maxfiy ma’lumotni tarqatishni",
    ],
    correctAnswer: "Dalillarga asoslangan va ehtiyotkor xulosa chiqarishni",
  },
  {
    id: 89,
    question: "Etik profaylingda rozilik nima uchun muhim?",
    options: [
      "Shaxsning huquqlarini himoya qilish uchun",
      "Shaxsni qo‘rqitish uchun",
      "Ma’lumotni yashirish uchun",
      "Tahlilni murakkablashtirish uchun",
    ],
    correctAnswer: "Shaxsning huquqlarini himoya qilish uchun",
  },
  {
    id: 90,
    question: "Profaylingda maxfiy ma’lumotni himoya qilish qanday tamoyil?",
    options: [
      "Maxfiylik",
      "Diskriminatsiya",
      "Manipulyatsiya",
      "Stereotiplash",
    ],
    correctAnswer: "Maxfiylik",
  },
  {
    id: 91,
    question: "Zamonaviy profaylingda raqamli izlar nimani anglatadi?",
    options: [
      "Internet va raqamli faoliyat natijasida qoladigan ma’lumotlar",
      "Faqat barmoq izi",
      "Faqat oyoq izi",
      "Faqat fotosurat",
    ],
    correctAnswer: "Internet va raqamli faoliyat natijasida qoladigan ma’lumotlar",
  },
  {
    id: 92,
    question: "Ijtimoiy tarmoqlardagi ma’lumotlardan foydalanishda nima muhim?",
    options: [
      "Maxfiylik, qonuniylik va kontekstni hisobga olish",
      "Har qanday ma’lumotni tarqatish",
      "Shaxsni avtomatik ayblash",
      "Faqat suratlarni baholash",
    ],
    correctAnswer: "Maxfiylik, qonuniylik va kontekstni hisobga olish",
  },
  {
    id: 93,
    question: "Profaylingda “human-in-the-loop” yondashuvi nimani anglatadi?",
    options: [
      "Inson mutaxassisi avtomatlashtirilgan tizim natijalarini nazorat qiladi",
      "Faqat kompyuter qaror qiladi",
      "Inson umuman qatnashmaydi",
      "Faqat statistik ma’lumot ishlatiladi",
    ],
    correctAnswer: "Inson mutaxassisi avtomatlashtirilgan tizim natijalarini nazorat qiladi",
  },
  {
    id: 94,
    question: "Profaylingda dalillarni tahlil qilishning eng to‘g‘ri usuli qaysi?",
    options: [
      "Faqat bitta belgiga asoslanish",
      "Bir nechta mustaqil belgilarni taqqoslash",
      "Birinchi taassurotga ishonish",
      "Stereotiplardan foydalanish",
    ],
    correctAnswer: "Bir nechta mustaqil belgilarni taqqoslash",
  },
  {
    id: 95,
    question: "Profayling jarayonida noto‘g‘ri xulosani kamaytirish uchun nima qilish kerak?",
    options: [
      "Taxminni fakt sifatida qabul qilish",
      "Faqat noverbal belgilarni kuzatish",
      "Qarama-qarshi dalillarni ham hisobga olish",
      "Shaxsni oldindan baholash",
    ],
    correctAnswer: "Qarama-qarshi dalillarni ham hisobga olish",
  },
  {
    id: 96,
    question: "Profaylingda kasbiy etikaning asosiy talablaridan biri qaysi?",
    options: [
      "Shaxsiy ma’lumotlarni ruxsatsiz tarqatish",
      "Xolislik va maxfiylikka rioya qilish",
      "Shaxsni stereotip asosida baholash",
      "Har bir shaxsni gumon ostida ko‘rish",
    ],
    correctAnswer: "Xolislik va maxfiylikka rioya qilish",
  },
  {
    id: 97,
    question: "Profaylingning umumiy samaradorligi nimaga ko‘proq bog‘liq?",
    options: [
      "Faqat texnologiyaga",
      "Faqat profaylerning sezgisiga",
      "Dalillar, kontekst, kuzatuv va professional tahlilning uyg‘unligiga",
      "Faqat tashqi ko‘rinishga",
    ],
    correctAnswer: "Dalillar, kontekst, kuzatuv va professional tahlilning uyg‘unligiga",
  },
  {
    id: 98,
    question: "Profaylingda “kontekst” tushunchasi nimani anglatadi?",
    options: [
      "Faqat shaxsning tashqi ko‘rinishini",
      "Xulq-atvor sodir bo‘layotgan vaziyat va sharoitni",
      "Faqat nutq tezligini",
      "Faqat yuz ifodasini",
    ],
    correctAnswer: "Xulq-atvor sodir bo‘layotgan vaziyat va sharoitni",
  },
  {
    id: 99,
    question: "Profaylingda xolislikni ta’minlash uchun qaysi yondashuv to‘g‘ri?",
    options: [
      "Shaxs haqida oldindan shakllangan fikrga tayanish",
      "Faqat salbiy belgilarni hisobga olish",
      "Bir nechta manba va belgilarni solishtirib baholash",
      "Birinchi taassurot asosida xulosa chiqarish",
    ],
    correctAnswer: "Bir nechta manba va belgilarni solishtirib baholash",
  },
  {
    id: 100,
    question: "Zamonaviy profaylingda texnologiyalardan foydalanishda eng muhim talab qaysi?",
    options: [
      "Texnologiya natijasini har doim mutlaq haqiqat deb qabul qilish",
      "Inson nazorati, maxfiylik va etik me’yorlarga rioya qilish",
      "Shaxs roziligini hisobga olmaslik",
      "Algoritm qarorini tekshirmaslik",
    ],
    correctAnswer: "Inson nazorati, maxfiylik va etik me’yorlarga rioya qilish",
  },
];
