import type { Question } from "@/lib/types";

// Source: Test_oila_psix_5_kurs sirtqi PP.xlsx
// The correct answer can be listed in any position; options are shuffled in the test.
export const questions: Question[] = [
  {
    id: 1,
    question: "Monogam oila qaysi javobda to’g`ri berilgan?",
    options: [
      "bir erkak va bir ayol juftligi o’rtasidagi nikoh",
      "bir erkak va bir necha ayol o’rtasidagi nikoh",
      "turli qabila vakillari o’rtasidagi nikoh",
      "bir urug vakillari ichidagi nikoh",
    ],
    correctAnswer: "bir erkak va bir ayol juftligi o’rtasidagi nikoh",
  },
  {
    id: 2,
    question: "Muloqotning qanday kommunikativ pozitsiyalari farqanadi?",
    options: [
      "\"ota yoki ona\", \"katta\", \"bola\"",
      "\"ota\", \"ona\", \"bola\"",
      "\"katta\", \"kichik\", \"teng”",
      "\"ota\", \"ona\", \"katta\"",
    ],
    correctAnswer: "\"ota yoki ona\", \"katta\", \"bola\"",
  },
  {
    id: 3,
    question: "«Ota yoki ona» pozitsiyasida bo’lish - bu ... jumlani davom ettiring",
    options: [
      "o’zining boshqalardan ustunligini anglash, rag`batlantirish va jazolash huquqiga egalikni his qilish",
      "odamning atrofidagilar bilan teng darajada muloqotda bo’la olishi",
      "xafagarchilikka yuqori sezgirlikni, ko’ngli bo’shlik, oson ishonuvchanlik, boshqalardan mehr olishni istash, kuchliroq odam tomonidan panoh tutishni va h.k. namoyon qilish",
      "boshqalardan mehr olishni istash, jazolash usuliga egalikni his qilish",
    ],
    correctAnswer: "o’zining boshqalardan ustunligini anglash, rag`batlantirish va jazolash huquqiga egalikni his qilish",
  },
  {
    id: 4,
    question: "\"Katta\" pozitsiyasida bo’lish deganda nimani tushunasiz?",
    options: [
      "odamning atrofidagilar bilan teng darajada muloqotda bo’la olishi",
      "o’zining boshqalardan ustunligini anglash, rag`batlantirish",
      "xafagarchilikka yuqori sezgirlikni, boshqalardan mehr olishi",
      "oson ishonuvchanlik, o’zining boshqalardan ustunligi",
    ],
    correctAnswer: "odamning atrofidagilar bilan teng darajada muloqotda bo’la olishi",
  },
  {
    id: 5,
    question: "«Kichik» pozitsiyasida bo’lish deganda nimani tushunasiz?",
    options: [
      "xafagarchilikka yuqori sezgirlikni, ko’ngli bo’shlik, boshqalardan mehr olishni istash, sezishni, kuchliroq odam tomonidan panoh tutishni va shu kabilarni namoyon qilish",
      "oson ishonuvchanlik, o’zining boshqalardan ustunligi",
      "o’zining boshqalardan ustunligini anglash, rag`batlantirish va jazolash uuiga egalikni his qilish",
      "odamning atrofidagilar bilan teng darajada muloqotda bo’la olishi",
    ],
    correctAnswer: "xafagarchilikka yuqori sezgirlikni, ko’ngli bo’shlik, boshqalardan mehr olishni istash, sezishni, kuchliroq odam tomonidan panoh tutishni va shu kabilarni namoyon qilish",
  },
  {
    id: 6,
    question: "Xafagarchilikka yuqori sezgirlikni, ko’ngli bo’shlik, boshqalardan mehr olishni istash, sezishni, kuchliroq odam tomonidan panoh tutishni va shu kabilarni namoyon qilish - bu..",
    options: [
      "\"bola\" pozitsiyasi",
      "\"katta\" pozitsiyasi",
      "\"ota yoki ona\" pozitsiyasi",
      "\"o‘zaro hamkorlik\" pozitsiyasi",
    ],
    correctAnswer: "\"bola\" pozitsiyasi",
  },
  {
    id: 7,
    question: "Odamning atrofidagilar bilan teng darajada muloqotda bo’la olishi – bu muloqotning qaysi pozitsiyasi?",
    options: [
      "\"katta\" pozitsiyasi",
      "\"bola\" pozitsiyasi",
      "\"ota yoki ona\" pozitsiyasi",
      "\"o‘zaro hamkorlik\" pozitsiyasi",
    ],
    correctAnswer: "\"katta\" pozitsiyasi",
  },
  {
    id: 8,
    question: "O’zining boshqalardan ustunligini anglash, rag`batlantirish va jazolash huquqiga egalikni his qilish -bu muloqotning qaysi pozitsiyasi?",
    options: [
      "\"ota yoki ona\" pozitsiyasi",
      "\"bola\" pozitsiyasi",
      "\"katta\" pozitsiyasi",
      "«o‘zaro hamkorlik» pozitsiyasi",
    ],
    correctAnswer: "\"ota yoki ona\" pozitsiyasi",
  },
  {
    id: 9,
    question: "Qadimgi yunonlar sevgi-muhabbatni kechishiga ko’ra qanday turga bo’lgan?",
    options: [
      "eros va agapega",
      "eros va lyudusga",
      "eros va maniya",
      "alangalangan va maniya",
    ],
    correctAnswer: "eros va agapega",
  },
  {
    id: 10,
    question: "J. Li romantik munosabatlarning qanday turlarini ajratib ko‘rsatadi?",
    options: [
      "eros, lyudus, storge, maniya, pragma, agape",
      "eros, attraksiya, simpatiya, altruizm",
      "agape, yoqtirish, simpatiya, attraksiya",
      "eros, o‘ziga jalb etish, rom bo‘lish",
    ],
    correctAnswer: "eros, lyudus, storge, maniya, pragma, agape",
  },
  {
    id: 11,
    question: "Lyudis - bu....",
    options: [
      "sevgi hislari ob’ekti oson almashishish mumkin bo’lgan sevgi tiri",
      "sevgini inkor etish",
      "o’zaro manfaatlar asosida qurilgan sevgi",
      "hayotini sevgidan iborat deb tasavvur qilish",
    ],
    correctAnswer: "sevgi hislari ob’ekti oson almashishish mumkin bo’lgan sevgi tiri",
  },
  {
    id: 12,
    question: "Tashqi ko’rinishidan kuchli ifodalanmagan bo`lsa-da muhabbatning ishonchli turi?",
    options: [
      "storge",
      "lyudis",
      "pragma",
      "Maniya",
    ],
    correctAnswer: "storge",
  },
  {
    id: 13,
    question: "Oila psixologiyasi fan sifatida nimani o’rganadi?",
    options: [
      "oilaning ijtimoiy institut maqomidagi faoliyatining obektiv qonuniyatlarini",
      "erkaklarga nisbatan tanlab munosabatda bo’lish qonuniyatlarini",
      "marosimlarni, urf odatlarni",
      "muomala madaniyatini",
    ],
    correctAnswer: "oilaning ijtimoiy institut maqomidagi faoliyatining obektiv qonuniyatlarini",
  },
  {
    id: 14,
    question: "Oilaning daromadini rejali sarflash oilanig qaysi vazifasiga kiradi?",
    options: [
      "Iqtisodiy",
      "Reproduktiv",
      "Kommunikativ",
      "Relaksiya",
    ],
    correctAnswer: "Iqtisodiy",
  },
  {
    id: 15,
    question: "Oila pixologiyasi faninig predmeti qaysi javobda to’g’ri ko’rsatilgan?",
    options: [
      "oilaning ijtimoiy va etnopsixologik xususiyatlari",
      "yoshlarni hayotga ilmiy asosda tayyorlash",
      "yoshlarni oilaviy muloqotga tayyorlash",
      "yoshlarni oilani rejalatirishga o’rgatish",
    ],
    correctAnswer: "oilaning ijtimoiy va etnopsixologik xususiyatlari",
  },
  {
    id: 16,
    question: "Qanday oilalarni baynalminal oila deyiladi?",
    options: [
      "turli millat vakillari o’rtasida tuzilgan oila",
      "oliy ma’lumotlilar o’rtasida tuzilgan oilaga",
      "ishchilar o’rtasida tuzilgan oila",
      "bir millat vakillari o’rtasida tuzilgan oila",
    ],
    correctAnswer: "turli millat vakillari o’rtasida tuzilgan oila",
  },
  {
    id: 17,
    question: "Biarxat oila qanday oila?",
    options: [
      "Er va xotin etakchilikni birgalikda bajaradigan oila",
      "er etakchi bo’lgan oila",
      "xotin etakchi bo’lgan oila",
      "liberal oila",
    ],
    correctAnswer: "Er va xotin etakchilikni birgalikda bajaradigan oila",
  },
  {
    id: 18,
    question: "Tabu bu-",
    options: [
      "axloqiy me’yorlarga qaraganda ancha jiddiy va qattiq bo’lgan taqiq",
      "erkaklarga nisbatan tanlab munosabatda bo’lish",
      "bir uyda bo’lish taqiqlangan oida",
      "odamlar jamoasi xo’jalik faoliyatining jiddiy buzilishi",
    ],
    correctAnswer: "axloqiy me’yorlarga qaraganda ancha jiddiy va qattiq bo’lgan taqiq",
  },
  {
    id: 19,
    question: "Ajratuvchi nizolar deb qanday nizolarga aytiladi?",
    options: [
      "bunda muammoning hal etilishi bir tomon manfaatlariga, yoki erning, yoki xotinning manfaatlariga qaratilgan bo‘ladi",
      "nizoga uchinchi shaxs ham qo‘shiladi",
      "bunday nizolarda muammoning hal etilishi ham erning, ham xotinning, butun oilaning manfaatlariga qaratilgan bo’ladi",
      "bunday nizolar chegaralanmagan bo‘ladi",
    ],
    correctAnswer: "bunda muammoning hal etilishi bir tomon manfaatlariga, yoki erning, yoki xotinning manfaatlariga qaratilgan bo‘ladi",
  },
  {
    id: 20,
    question: "Qanday nizo oilaviy munosabatlarni mustahkamlanishi, muammoning ikkala tomon uchun ijobiy hal etilishiga olib keladi?",
    options: [
      "konstruktiv - biriktiruvchi nizo",
      "destruktiv - ajratuvchi nizo",
      "chegaralanmagan nizo",
      "er-xotin ortasidagi nizo",
    ],
    correctAnswer: "konstruktiv - biriktiruvchi nizo",
  },
  {
    id: 21,
    question: "Er - xotinnning urushi doka ro`molning qurishi qabilidagi nizolar nizolarning qaysi turiga kiradi?",
    options: [
      "konstruktiv - biriktiruvchi nizo",
      "destruktiv - ajratuvchi nizo",
      "chegaralanmagan nizo",
      "er-xotin ortasidagi nizo",
    ],
    correctAnswer: "konstruktiv - biriktiruvchi nizo",
  },
  {
    id: 22,
    question: "Qanday nizolarga chegaralanmagan nizolar deyiladi?",
    options: [
      "ajratuvchi nizo",
      "biriktiruvchi nizo",
      "qaynona - kelin o`rtasidagi nizo",
      "er-xotin o`rtasidagi nizo",
    ],
    correctAnswer: "ajratuvchi nizo",
  },
  {
    id: 23,
    question: "“Nikohning tugatilishi” haqida “Oila Kodeksi”ning nechanchi bob va moddasida ko’rsatilgan?",
    options: [
      "7-bob 37-38 modda",
      "8-bob 40-45 modda",
      "8-bob 45 modda",
      "20-bob 40-45 modda",
    ],
    correctAnswer: "7-bob 37-38 modda",
  },
  {
    id: 24,
    question: "Ajralishga sabab bo`luvchi omillar qaysi javobda to`liq keltirilgan?",
    options: [
      "bir-birini tushunmaslik, xarakterlarning mos kelmasligi, moddiy qiyinchilik, ichkilikbozlikka berilish, yashash sharoitining noqulayligi, ota-onalarning noo‘rin aralashuvi, xiyonat",
      "bosh ko’tarish, g`azablanishi, tushkunlikka tushish",
      "ota- onasining tashabbusi bilan ajralishga qaror qiladi",
      "yaxshi tinch-totuv yashayotgan oilada birdan shunday holat yuz beradiki, masalan, xiyonat, o‘lim, xastalik, rashk va shunga o‘xshash voqealar turki bo‘ldiyu, oila ustuni qulaydi",
    ],
    correctAnswer: "bir-birini tushunmaslik, xarakterlarning mos kelmasligi, moddiy qiyinchilik, ichkilikbozlikka berilish, yashash sharoitining noqulayligi, ota-onalarning noo‘rin aralashuvi, xiyonat",
  },
  {
    id: 25,
    question: "Ota-ona va bola o‘rtasidagi munosabatlarda boladagi tashabbusning ota-onalar tomonidan ta’qiqlanishi va ularning har bir nojo‘ya hatti-harakati albatta jazolanishi qaysi uslubga mos keladi?",
    options: [
      "avtoritar",
      "demokratik",
      "liberal",
      "befarq",
    ],
    correctAnswer: "avtoritar",
  },
  {
    id: 26,
    question: "Ota-ona va bola o‘rtasidagi munosabatlarda farzandiga mehr berib, uning qiziqishlari, imkoniyatlari bilan hisoblashish va bolaning erkin fikrlashiga imkon yaratib berilishi qaysi uslubga mos keladi?",
    options: [
      "demokratik",
      "avtoritar",
      "liberal",
      "befarq",
    ],
    correctAnswer: "demokratik",
  },
  {
    id: 27,
    question: "Reproduktiv xulq bu - …",
    options: [
      "oilada farzand tug’ilishi bilan bog’liq xulq",
      "oilada o’zaro bir birini qo’llab quvvatlash bilan bog’liq xulq",
      "oilada farzand tarbiyalash bilan bog’liq xulq",
      "o’zligini anglash bilan bog’liq xulq",
    ],
    correctAnswer: "oilada farzand tug’ilishi bilan bog’liq xulq",
  },
  {
    id: 28,
    question: "Giperproteksiya ta’rif qaysi qatorda to‘g‘ri ko‘rsatilgan?",
    options: [
      "ota-onalarning farzandlariga nisbatan haddan ziyod e’tibori bo‘lib, bu ularning bola tarbiyasi uchun kuch, vaqt va e’tiborni ayamasliklarida namoyon bo‘ladi",
      "erkalatishdan ko‘ra ota-ona tomonidan bolasining har bir yurgan qadami va xatti-harakatini nzoratga olish orqali unga e’tibor berish nazarda tutiladi",
      "ota-ona tomonidan bolaga nisbatan talablar darajasi yuqori bo‘ladi, lekin uning asl xohish-istaklari, ehtiyojlari unchalik e’tiborga olinmaydi",
      "to‘g‘ridan-to‘g‘ri bolani yoshligidan kaltaklash, haqorat qilish, kamsitish shaklida yoki bola ehtiyojlariga to‘la befarqlik, uning bor-yo‘qligini go‘yoki sezmaslik kabi ko‘rinishlarda bo‘lishi",
    ],
    correctAnswer: "ota-onalarning farzandlariga nisbatan haddan ziyod e’tibori bo‘lib, bu ularning bola tarbiyasi uchun kuch, vaqt va e’tiborni ayamasliklarida namoyon bo‘ladi",
  },
  {
    id: 29,
    question: "Ota-ona va bola munosabatlari demokratik tamoyillarda amalga oshadigan oilada bolada o‘zi va ota-onasi to‘g‘risida qanday tasavvur shakllanadi?",
    options: [
      "“Meni sevishadi va men kerakman, shuning uchun men ham ularni juda sevaman”",
      "“Meni yoqtirishmaydi, lekin men o‘zim harakat qilib, ularga yaqinlashishim kerak”",
      "“Meni sevishadi va men kerakman, ular meni deb yashashadi”",
      "“Sizlar meni xafa qilyapsizlar, men ham shunga munosib javob beraman”",
    ],
    correctAnswer: "“Meni sevishadi va men kerakman, shuning uchun men ham ularni juda sevaman”",
  },
  {
    id: 30,
    question: "Sherigini tushunmay qolish, maqul tushmay qolishdan qo’rqish xolatlari qanday muloqot to’siqlari xisoblanadi.?",
    options: [
      "Psixologik",
      "Vaziyatli",
      "Mazmuniy",
      "Xissiy",
    ],
    correctAnswer: "Psixologik",
  },
  {
    id: 31,
    question: "Bola ota-onaning hayotida ortiqcha yuk ekanligi, u bo’lmaganida ota-onaning hayoti boshqacha bo’lishi mumkinligi bolaga eslatib turilishi – bu...",
    options: [
      "emotsional raddiya",
      "proteksiya",
      "giperproteksiya",
      "gipoproteksiya",
    ],
    correctAnswer: "emotsional raddiya",
  },
  {
    id: 32,
    question: "\"Emotsional raddiya\" bu –",
    options: [
      "bola ota-onaning hayotida ortiqcha yuk ekanligi, u bo’lmaganida ota-onaning hayoti boshqacha bo’lishi mumkinligi bolaga eslatib turilishi",
      "ota-onalarning farzanlariga haddan ziyod e’tibori",
      "ota-onaning bolaga e’tiborsizligi",
      "homilador ayolning homilasidan havotir olishi",
    ],
    correctAnswer: "bola ota-onaning hayotida ortiqcha yuk ekanligi, u bo’lmaganida ota-onaning hayoti boshqacha bo’lishi mumkinligi bolaga eslatib turilishi",
  },
  {
    id: 33,
    question: "Qattiqqo‘llik ota-ona tomonidan qanday amalga oshiriladi?",
    options: [
      "to‘g‘ridan-to‘g‘ri bolani yoshligidan kaltaklash, haqorat qilish, kamsitish shaklida",
      "bola ehtiyojlariga to‘la befarqlik",
      "bolaning bor-yo‘qligini go‘yoki sezmaslik",
      "ota-onalarning farzandlariga nisbatan haddan ziyod e’tibori bo‘lib, bu ularning bola tarbiyasi uchun kuch, vaqt va e’tiborni ayamasliklarida namoyon bo‘ladi",
    ],
    correctAnswer: "to‘g‘ridan-to‘g‘ri bolani yoshligidan kaltaklash, haqorat qilish, kamsitish shaklida",
  },
  {
    id: 34,
    question: "Er va xotinning ikkalasi ham 30 yoshdan oshmagan hamda oilaviy turmush tajribasi 10 yildan oshmagan oilalar qanday oila deb ataladi?",
    options: [
      "yosh oila",
      "yangi oila",
      "o’rta yoshdagi oilalar",
      "etuk yoshdagi oilalar",
    ],
    correctAnswer: "yosh oila",
  },
  {
    id: 35,
    question: "Moddiy yoki o’zga manfaatdorlik asosida oila kurish deganda nimani tushunasiz?",
    options: [
      "biron narsani hisobga olgan holda",
      "o’zaro sevishib oila qurish",
      "hamma oila qurishi kerak bo’lgani uchun",
      "Ota-ona tavsiyasi bilan",
    ],
    correctAnswer: "biron narsani hisobga olgan holda",
  },
  {
    id: 36,
    question: "Muloqot jarayonida yuzaga kelishi mumkin bo’lgan to’siqlar qaysi javobda to’liq berilgan?",
    options: [
      "psixologik, vaziyatli, mazmuniy, motivatsion tusiqlar",
      "psixologik, vaziyatli, mazmuniy to`siqlar",
      "mazmuniy, iqtisodiy, motivatsion to’siqlar",
      "ijtimoiy, tarbiyaviy, motivatsion tusiqlar",
    ],
    correctAnswer: "psixologik, vaziyatli, mazmuniy, motivatsion tusiqlar",
  },
  {
    id: 37,
    question: "Bir erkak va bir ayol juftligi o’rtasidagi nikoh bu…?",
    options: [
      "Monogam oila",
      "Egzogam oila",
      "Guruhiy oila",
      "Poligam oila",
    ],
    correctAnswer: "Monogam oila",
  },
  {
    id: 38,
    question: "Qanday nikoh motivlari farqlanadi?",
    options: [
      "sevgi, moddiy yoki o‘zga manfaatdorlik, streotip asosida",
      "Sovchilik",
      "sevgi va moddiy manfaat izlash",
      "ma’naviy manfaatdorlik, ota ona istagini bajo keltirish",
    ],
    correctAnswer: "sevgi, moddiy yoki o‘zga manfaatdorlik, streotip asosida",
  },
  {
    id: 39,
    question: "Moddiy yoki o’zga manfaatdorlik asosida oila kurish deganda nimani tushunasiz?",
    options: [
      "biron narsani hisobga olgan holda",
      "o’zaro sevishib oila qurish",
      "hamma oila qurishi kerak bo’lgani uchun",
      "yolg‘izlikdan qutilish uchun",
    ],
    correctAnswer: "biron narsani hisobga olgan holda",
  },
  {
    id: 40,
    question: "Oila kodeksiga binoan yoshlar nikohdan o’tish uchun ariza berganlaridan so’ng qancha muxlat beriladi?",
    options: [
      "33 kun",
      "7 kun",
      "24 kun",
      "40 kun",
    ],
    correctAnswer: "33 kun",
  },
  {
    id: 41,
    question: "O’zbekistonda “Oila psixologiyasi” darsligi kimlar tomonidan yaratilgan?",
    options: [
      "G.Shoumarov, V.Karimova",
      "B.Qodirov, Z.Nishonova",
      "M. Davletshin, N. Safaev",
      "B. Umarov, SH.Baratov",
    ],
    correctAnswer: "G.Shoumarov, V.Karimova",
  },
  {
    id: 42,
    question: "Muhabbatning qanday bosqichlari mavjud?",
    options: [
      "boshlangich, alangalangan, o’zaro hurmat bosqichi",
      "boshlangich, alangalangan bosqichi",
      "boshlang‘ich va so‘nish bosqichi",
      "boshlang`ich, o’rta va pasayish bosqichi",
    ],
    correctAnswer: "boshlangich, alangalangan, o’zaro hurmat bosqichi",
  },
  {
    id: 43,
    question: "Oilaviy nizolarni asosiy turlari qaysi qatorda to’g’ri keltirilgan?",
    options: [
      "er-xotin, qaynona-kelin, ota-ona va farzand o’rtasidagi nizo",
      "qaynona-kelin, qaynona-kuyov, o’qituvchi va o’quvchi nizo",
      "er-xotin, qaynona-kelin, ota-ona va o’qituvchi o’rtasidagi nizo",
      "er-xotin, o’quvchi - o’qituvchi, qaynona-kelin, ota-ona va farzand o’rtasidagi nizo",
    ],
    correctAnswer: "er-xotin, qaynona-kelin, ota-ona va farzand o’rtasidagi nizo",
  },
  {
    id: 44,
    question: "Psixologik adabiyotlarda nizolar shartli ravishda qanday turlarga bolinadi?",
    options: [
      "konstruktiv va destruktiv nizolar",
      "kuchaytiruvchi va ajratuvchi nizolar",
      "muvaffaqiyatli va muvaffaqiyatsiz nizolar",
      "shartli va shartsiz nizolar",
    ],
    correctAnswer: "konstruktiv va destruktiv nizolar",
  },
  {
    id: 45,
    question: "Nikoh nima?",
    options: [
      "Erkak va ayol o’rtasidagi muayyan ittifoqni jamiyat, davlat tomonidan tan olinishi",
      "Ikki kishi orasidagi kelishuv, shartnoma",
      "Yigit va qiz o’rtasidagi munosabat",
      "Ikki qarama-qarshi jins orasidagi munosabat",
    ],
    correctAnswer: "Erkak va ayol o’rtasidagi muayyan ittifoqni jamiyat, davlat tomonidan tan olinishi",
  },
  {
    id: 46,
    question: "O’zbekiston Respublikasining “Oila kodeksi” qachon tasdiqlangan?",
    options: [
      "1998 yil 30 aprel",
      "1995 yil 30 may",
      "1989 yil 9 aprel",
      "1990 yil 29 may",
    ],
    correctAnswer: "1998 yil 30 aprel",
  },
  {
    id: 47,
    question: "“Tabu” – deb nimaga aytiladi?",
    options: [
      "Qattiq ta’qiq",
      "Qovushish",
      "Suhbatlashish",
      "O’zaro munosabatga kirishish",
    ],
    correctAnswer: "Qattiq ta’qiq",
  },
  {
    id: 48,
    question: "Oilaning rekreativ funksiyasi nima.",
    options: [
      "Jismoniy, moddiy va ma’naviy,psixologik yordam berish",
      "Ruxiy-jismoniy quvvatini oshirish",
      "O’zaro munosabatlarni boshqarish",
      "Biologik uzluksizligini ta’minlash",
    ],
    correctAnswer: "Jismoniy, moddiy va ma’naviy,psixologik yordam berish",
  },
  {
    id: 49,
    question: "Birga yashovchi lekin nikoxi rasmiylashtirilmagan, oila qanday oila xisoblanadi.?",
    options: [
      "Sinovdagi oila",
      "Nikoxdan tashqari",
      "Nikox arafasidagi oila",
      "Rasmiy oila",
    ],
    correctAnswer: "Sinovdagi oila",
  },
  {
    id: 50,
    question: "Zamonaviy oila turlarini aniqlang.",
    options: [
      "Barcha javob to’g’ri",
      "Bo’g’inlariga ko’ra",
      "bolalar soniga ko’ra",
      "oilaning yoshiga ko’ra",
    ],
    correctAnswer: "Barcha javob to’g’ri",
  },
  {
    id: 51,
    question: "Konstruktiv nizo nima?",
    options: [
      "Biriktiruvchi,",
      "Ajratuvchi,",
      "Muvofiqlashtiruvchi",
      "Muvaqqiyatsiz",
    ],
    correctAnswer: "Biriktiruvchi,",
  },
  {
    id: 52,
    question: "Muhit insonga o’zining ta’sir kuchini qachondan boshlaydi?",
    options: [
      "Individ tug’ilmasidan oldin",
      "Chaqaloqlikdan",
      "o’smirlikdan",
      "o’spirinlik",
    ],
    correctAnswer: "Individ tug’ilmasidan oldin",
  },
  {
    id: 53,
    question: "Nikohga etuklik xususiyatlarini ko’rsating.",
    options: [
      "Barcha javob to’g’ri",
      "Fuqorolik, xuquqiy etuklik",
      "Kasb xunar etukligi,",
      "Axloqiy, psixologik etuklik,",
    ],
    correctAnswer: "Barcha javob to’g’ri",
  },
  {
    id: 54,
    question: "Nikoh yoshi to’g’ri berilgan javobni ko’rsating?",
    options: [
      "erkaklar uchun 18 yosh, ayollar uchun 17 yosh",
      "erkaklar uchun 18 yosh, ayollar uchun 18 yosh",
      "erkaklar uchun 17 yosh, ayollar uchun 17 yosh",
    ],
    correctAnswer: "erkaklar uchun 18 yosh, ayollar uchun 17 yosh",
  },
  {
    id: 55,
    question: "Nuklear oila –bu?",
    options: [
      "Ota-ona va bolalardan iborat",
      "Ko’p bo’ginli oila",
      "Noto’liq oila",
      "To’liq oila",
    ],
    correctAnswer: "Ota-ona va bolalardan iborat",
  },
  {
    id: 56,
    question: "Oila funksiyalarini ko’rsating",
    options: [
      "barcha javob to’g’ri",
      "Tarbiyaviy, rekreativ",
      "Iqtisodiy, felitsitologik, reproduktiv",
      "Regulyativ, kommunikativ",
    ],
    correctAnswer: "barcha javob to’g’ri",
  },
  {
    id: 57,
    question: "Oilaviy nizolar necha xil bo’ladi?",
    options: [
      "2 xil",
      "3 xil",
      "4 xil",
      "5 xil",
    ],
    correctAnswer: "2 xil",
  },
  {
    id: 58,
    question: "Oilaviy muloqot jarayonida qanday to’siqlar bor",
    options: [
      "Psixologik, vaziyatli, motivasion, mazmuniy",
      "Motivasion, vaqtli, fiziologik",
      "Mazmuniy, vaziyatli, jismoniy",
      "Vaqtli, fazoviy",
    ],
    correctAnswer: "Psixologik, vaziyatli, motivasion, mazmuniy",
  },
  {
    id: 59,
    question: "Oilaviy nizolarning turlarini ko’rsating",
    options: [
      "Barcha javob to’g’ri",
      "Er-xotin, ota-ona va farzand",
      "qaynona-kuyov",
      "qaynona- kelin",
    ],
    correctAnswer: "Barcha javob to’g’ri",
  },
  {
    id: 60,
    question: "Oilada bir-birini tushunmaslik qanday to’siqning vujudga kelishiga sabab bo’ladi ?",
    options: [
      "Psixologik",
      "Mazmuniy",
      "Motivasion",
      "Emosional",
    ],
    correctAnswer: "Psixologik",
  },
  {
    id: 61,
    question: "Oilada er yoki xotin boshqaruvchi bo’lsa, qanday oila turkumiga kiradi?",
    options: [
      "Yetakchiligiga ko’ra",
      "Ma’lumotiga ko’ra",
      "Ijtimoiy kelib chiqishiga ko’ra",
      "Er-xotin o’rtasidagi munosabatlarga ko’ra",
    ],
    correctAnswer: "Yetakchiligiga ko’ra",
  },
  {
    id: 62,
    question: "Oilaning reproduktiv funksiyasi…..",
    options: [
      "Biologik uzluksizlikni ta’minlash",
      "Ruxiy-jismoniy quvvatini oshirish",
      "O’zaro munosabatlarni boshqarish",
      "Jismoniy, moddiy va ma’naviy, psixologik yordam ko’rsatish",
    ],
    correctAnswer: "Biologik uzluksizlikni ta’minlash",
  },
  {
    id: 63,
    question: "Oila yoshiga ko’ra qanday turlarga bo’linadi?",
    options: [
      "Yetuk oila, yosh oila, o’rta yoshdagi oila",
      "3-4 bolali oila, farzandsiz, bir bolali, 5 va undan ortiq bolali",
      "Nuklear oila, ko’p bo’g’inli oila",
      "Barcha javob to’g’ri",
    ],
    correctAnswer: "Yetuk oila, yosh oila, o’rta yoshdagi oila",
  },
  {
    id: 64,
    question: "Oilaning iqtisodiy funksiyasi bu.................",
    options: [
      "Oilada xo’jalik ishlarini yuritish, moddiy ne’matlar ishlab chiqarish,",
      "Bolalarning aqliy, jismoniy, axloqiy, estetik tarbiyalash",
      "O’zaro muloqot va o’zaro tushunishga bo’lgan ehtiyojini qondirish",
      "Shaxsiy baxtga erishishga intilish",
    ],
    correctAnswer: "Oilada xo’jalik ishlarini yuritish, moddiy ne’matlar ishlab chiqarish,",
  },
  {
    id: 65,
    question: "Oilaning kommunikativ funksiyasi bu.............",
    options: [
      "Oila a’zolarining o’zaro muloqot va o’zaro tushunishga bo’lgan ehtiyojini qondirish",
      "Bolalarning aqliy, jismoniy, axloqiy, estetik tarbiyalash",
      "O’zaro muloqot va o’zaro tushunishga bo’lgan ehtiyojini qondirishga xizmat",
      "Oilada xo’jalik ishlarini yuritish, moddiy ne’matlar ishlab chiqarish",
    ],
    correctAnswer: "Oila a’zolarining o’zaro muloqot va o’zaro tushunishga bo’lgan ehtiyojini qondirish",
  },
  {
    id: 66,
    question: "Oilaning regulyativ funksiyasi nima?",
    options: [
      "O’zaro munosabatlarni boshqarish va nazorat",
      "Ruxiy-jismoniy quvvatini oshirish",
      "Jismoniy, moddiy va ma’naviy, psixologik yordam ko’rsatish",
      "Biologik uzluksizligini ta’minlash",
    ],
    correctAnswer: "O’zaro munosabatlarni boshqarish va nazorat",
  },
  {
    id: 67,
    question: "Oilaning tarbiyaviy funksiyasi nima?",
    options: [
      "Axloqiy, ma’naviy, diniy, estetik tarbiya",
      "O’zaro munosabatlarni boshqarish",
      "Jismoniy, moddiy va ma’naviy,psixologik qo’llab quvvatlash",
      "Baxtli bo’lishlik",
    ],
    correctAnswer: "Axloqiy, ma’naviy, diniy, estetik tarbiya",
  },
  {
    id: 68,
    question: "Oilaning relaksatsiya funksiyasi nima?",
    options: [
      "Ruxiy-jismoniy quvvatni va mehnat qobiliyatini qayta tiklash",
      "O’zaro munosabatlarni boshqarish",
      "Jismoniy, moddiy va ma’naviy,psixologik",
      "Biologik uzluksizligini ta’minlash",
    ],
    correctAnswer: "Ruxiy-jismoniy quvvatni va mehnat qobiliyatini qayta tiklash",
  },
  {
    id: 69,
    question: "Psixologlar muloqotning o’ziga xos uch xil kommunikativ pozitsiyasini farqlaydilar. Ularni aniqlang.",
    options: [
      "Barcha javob to’g’ri",
      "«ota yoki ona»",
      "«katta»",
      "«bola»",
    ],
    correctAnswer: "Barcha javob to’g’ri",
  },
  {
    id: 70,
    question: "Tarbiyaviy funksiya bu....................",
    options: [
      "Bolalarning aqliy, jismoniy, axloqiy, estetik tarbiyalash",
      "O’zaro muloqot va o’zaro tushunishga bo’lgan ehtiyojni qondirish",
      "Shaxsiy baxtga erishishga intilish",
      "Oilada xo’jalik ishlarini yuritish, moddiy ne’matlar ishlab chiqarish",
    ],
    correctAnswer: "Bolalarning aqliy, jismoniy, axloqiy, estetik tarbiyalash",
  },
  {
    id: 71,
    question: "O’zaro qovushishlarni shartli ravishda uchta tarkibiy qismga ajratish mumkin, ular:",
    options: [
      "Biologik , Psixologik , Sotsial",
      "Ijtimoiy, fiziologik, psixologik",
      "Psixologik, shartli, shartsiz",
      "Ijtimoiy, biologik, shartli",
    ],
    correctAnswer: "Biologik , Psixologik , Sotsial",
  },
  {
    id: 72,
    question: "Felisitalogik funksiya bu..................",
    options: [
      "Baxtli bo’lishlik",
      "Ruxiy-jismoniy quvvatini oshirish",
      "O’zaro munosabatlarni boshqarish",
      "Jismoniy, moddiy va ma’naviy,psixologik",
    ],
    correctAnswer: "Baxtli bo’lishlik",
  },
  {
    id: 73,
    question: "Oila uchun eng xavfli payt nikohning dastlabki nechanchi yili xisoblanadi?",
    options: [
      "5",
      "3",
      "7",
      "10",
    ],
    correctAnswer: "5",
  },
  {
    id: 74,
    question: "Yolg’iz onaxon yoki otaxonlar, er yoki xotinning o’limi tufayli noto’liq bo’lgan oilalar, yoki ajrim tufayli paydo bo’ladigan oila tiplari nima deyiladi?",
    options: [
      "Noto’liq oila",
      "To’liq oila",
      "Oila tipiga kirmaydi",
      "Oddiy oila",
    ],
    correctAnswer: "Noto’liq oila",
  },
  {
    id: 75,
    question: "“Qobusnoma” asarini kim yozgan?",
    options: [
      "Kaykovus",
      "Alisher Navoiy",
      "Ibn Sino",
      "Yusuf Xos Hojib",
    ],
    correctAnswer: "Kaykovus",
  },
  {
    id: 76,
    question: "“Qutadg’u bilig” asarini kim yozgan?",
    options: [
      "Yusuf Xos Hojib",
      "Alisher Navoiy",
      "Ibn Sino",
      "Kaykovus",
    ],
    correctAnswer: "Yusuf Xos Hojib",
  },
  {
    id: 77,
    question: "“Uy xo’jaligi” asarini kim yozgan?",
    options: [
      "Ibn Sino",
      "Alisher Navoiy",
      "Yusuf Xos Hojib",
      "Kaykovus",
    ],
    correctAnswer: "Ibn Sino",
  },
  {
    id: 78,
    question: "“Hikmatlar xazinasi” asarini kim yozgan?",
    options: [
      "Yusuf Tovasliy",
      "Alisher Navoiy",
      "Yusuf Xos Hojib",
      "Kaykovus",
    ],
    correctAnswer: "Yusuf Tovasliy",
  },
  {
    id: 79,
    question: "Oilaning to’liqliligiga ko’ra turlarini ko’rsating?",
    options: [
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
      "Nuklear va ko’p bo’g’inli oila",
      "Farzandsiz, bir bolali, ikki bolali, 3-4 bolali, 5 va undan ortiq bolali oila",
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
    ],
    correctAnswer: "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
  },
  {
    id: 80,
    question: "Oilaning bo’g’inlar soniga ko’ra turlarini ko’rsating?",
    options: [
      "Nuklear va ko’p bo’g’inli oila",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
      "Farzandsiz, bir bolali, ikki bolali, 3-4 bolali, 5 va undan ortiq bolali oila",
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
    ],
    correctAnswer: "Nuklear va ko’p bo’g’inli oila",
  },
  {
    id: 81,
    question: "Oilaning bolalar soniga ko’ra turlarini ko’rsating?",
    options: [
      "Farzandsiz, bir bolali, ikki bolali, 3-4 bolali, 5 va undan ortiq bolali oila",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
      "Nuklear va ko’p bo’g’inli oila",
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
    ],
    correctAnswer: "Farzandsiz, bir bolali, ikki bolali, 3-4 bolali, 5 va undan ortiq bolali oila",
  },
  {
    id: 82,
    question: "Oilaning er-xotinning ijtimoiy kelib chiqishiga ko’ra turlarini ko’rsating",
    options: [
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
      "Nuklear va ko’p bo’g’inli oila",
      "Farzandsiz, bir bolali, ikki bolali, 3-4 bolali, 5 va undan ortiq bolali oila",
    ],
    correctAnswer: "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
  },
  {
    id: 83,
    question: "Oilaning ma’lumot saviyasiga ko’ra turlarini ko’rsating?",
    options: [
      "oliy ma’lumotlilar, o’rta maxsus, o’rta, tugatilmagan o‘rta",
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
      "Nuklear va ko’p bo’g’inli oila",
    ],
    correctAnswer: "oliy ma’lumotlilar, o’rta maxsus, o’rta, tugatilmagan o‘rta",
  },
  {
    id: 84,
    question: "Oilaning yoshiga ko’ra turlarini ko’rsating?",
    options: [
      "yosh oila, orta yoshdagi oila, yetuk yoshdagi oila",
      "oliy ma’lumotlilar, o’rta maxsus, o’rta, tugatilmagan o‘rta",
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
    ],
    correctAnswer: "yosh oila, orta yoshdagi oila, yetuk yoshdagi oila",
  },
  {
    id: 85,
    question: "Oilaning regional jihtlariga ko’ra turlarini ko’rsating?",
    options: [
      "Shahar, qishloq, aralash tipdagi oila",
      "oliy ma’lumotlilar, o’rta maxsus, o’rta, tugatilmagan o‘rta",
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
    ],
    correctAnswer: "Shahar, qishloq, aralash tipdagi oila",
  },
  {
    id: 86,
    question: "Oilada er-xotin munosabatlariga ko’ra turlarini ko’rsating?",
    options: [
      "avtoritar, demokratik, liberal, aralash tipdagi oilalar",
      "oliy ma’lumotlilar, o’rta maxsus, o’rta, tugatilmagan o‘rta",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
      "Nuklear va ko’p bo’g’inli oila",
    ],
    correctAnswer: "avtoritar, demokratik, liberal, aralash tipdagi oilalar",
  },
  {
    id: 87,
    question: "Oilaning nikohdan qoniqqanlik saviyasiga ko’ra turlarini ko’rsating?",
    options: [
      "ajralish arafasida, o’rta, nikohdan qoniqqanlik darajasi yuqori",
      "avtoritar, demokratik, liberal, aralash tipdagi oilalar",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
      "Nuklear va ko’p bo’g’inli oila",
    ],
    correctAnswer: "ajralish arafasida, o’rta, nikohdan qoniqqanlik darajasi yuqori",
  },
  {
    id: 88,
    question: "Oilaning yurudik rasmiylashtirilganligiga ko’ra turlarini ko’rsating?",
    options: [
      "sinovdagi oila, rasmiylashtirish arafasidagi oila, nikohdagi oila, nikohdan tashqari oila",
      "ajralish arafasida, o’rta, nikohdan qoniqqanlik darajasi yuqori",
      "avtoritar, demokratik, liberal, aralash tipdagi oilalar",
      "to’liq, noto’liq, qayta tuzilgan(ikkinchi nikoh) oila",
    ],
    correctAnswer: "sinovdagi oila, rasmiylashtirish arafasidagi oila, nikohdagi oila, nikohdan tashqari oila",
  },
  {
    id: 89,
    question: "Oilaning er-xotining millatiga ko’ra turlarini ko’rsating?",
    options: [
      "bir millatli, baynalmilal oila",
      "Shahar, qishloq, aralash tipdagi oila",
      "oliy ma’lumotlilar, o’rta maxsus, o’rta, tugatilmagan o‘rta",
      "Ishchilar, dehqonlar, xizmatchilar, ziyolilar, aralash tipdagi oila",
    ],
    correctAnswer: "bir millatli, baynalmilal oila",
  },
  {
    id: 90,
    question: "Ko‘p bo‘g‘inli oila qanday oila xisoblanadi?",
    options: [
      "Ikki va undav ortiq avloddan iborat birga yashovchi oila",
      "Ota-onalar va bolalardan iborat bo‘lgan oila",
      "Qayta tuzilgan oila",
      "5 va undan ortiq bolali oilalar",
    ],
    correctAnswer: "Ikki va undav ortiq avloddan iborat birga yashovchi oila",
  },
  {
    id: 91,
    question: "Nikoh oldi omillarini ko‘rsating?",
    options: [
      "barcha javob to‘gri",
      "Oilaviy hayotga yetuklik, nikoh qurish yoshi",
      "nikoh qurish motivlari, nikoh qurish shartlari",
      "Oilaviy hayot haqidagi tasavvurlari, nikohgacha tanishish muddati",
    ],
    correctAnswer: "barcha javob to‘gri",
  },
  {
    id: 92,
    question: "Suhbatdoshlarning bir xil vaziyatni turlicha tushunishlari muloqot jarayonida yuzaga keladigan to ‘siqlarning qay biriga misol bo ‘ladi?",
    options: [
      "Vaziyatli to‘siq",
      "Psixologik to‘siq",
      "Mazmuniy to‘siq",
      "Motivatsion to‘siq",
    ],
    correctAnswer: "Vaziyatli to‘siq",
  },
  {
    id: 93,
    question: "Muhabbatning qanday bosqichlari mavjud?",
    options: [
      "boshlangich, alangalangan, o’zaro hurmat bosqichi",
      "boshlangich, alangalangan bosqichi",
      "boshlang‘ich va so‘nish bosqichi",
      "boshlang`ich, o’rta va pasayish bosqichi",
    ],
    correctAnswer: "boshlangich, alangalangan, o’zaro hurmat bosqichi",
  },
  {
    id: 94,
    question: "Oilaviy nizolarni asosiy turlari qaysi qatorda to’g’ri keltirilgan?",
    options: [
      "er-xotin, qaynona-kelin, ota-ona va farzand o’rtasidagi nizo",
      "qaynona-kelin, qaynona-kuyov, o’qituvchi va o’quvchi nizo",
      "er-xotin, qaynona-kelin, ota-ona va o’qituvchi o’rtasidagi nizo",
      "er-xotin, o’quvchi - o’qituvchi, qaynona-kelin, ota-ona va farzand o’rtasidagi nizo",
    ],
    correctAnswer: "er-xotin, qaynona-kelin, ota-ona va farzand o’rtasidagi nizo",
  },
  {
    id: 95,
    question: "Psixologik adabiyotlarda nizolar shartli ravishda qanday turlarga bolinadi?",
    options: [
      "konstruktiv va destruktiv nizolar",
      "kuchaytiruvchi va ajratuvchi nizolar",
      "muvaffaqiyatli va muvaffaqiyatsiz nizolar",
      "shartli va shartsiz nizolar",
    ],
    correctAnswer: "konstruktiv va destruktiv nizolar",
  },
  {
    id: 96,
    question: "Nikoh nima?",
    options: [
      "Erkak va ayol o’rtasidagi muayyan ittifoqni jamiyat, davlat tomonidan tan olinishi",
      "Ikki kishi orasidagi kelishuv, shartnoma",
      "Yigit va qiz o’rtasidagi munosabat",
      "Ikki qarama-qarshi jins orasidagi munosabat",
    ],
    correctAnswer: "Erkak va ayol o’rtasidagi muayyan ittifoqni jamiyat, davlat tomonidan tan olinishi",
  },
  {
    id: 97,
    question: "O’zbekiston Respublikasining “Oila kodeksi” qachon tasdiqlangan?",
    options: [
      "1998 yil 30 aprel",
      "1995 yil 30 may",
      "1989 yil 9 aprel",
      "1990 yil 29 may",
    ],
    correctAnswer: "1998 yil 30 aprel",
  },
  {
    id: 98,
    question: "“Tabu” – deb nimaga aytiladi?",
    options: [
      "Qattiq ta’qiq",
      "Qovushish",
      "Suhbatlashish",
      "O’zaro munosabatga kirishish",
    ],
    correctAnswer: "Qattiq ta’qiq",
  },
  {
    id: 99,
    question: "Oilani kafolatlovchi manbalar.",
    options: [
      "barcha javob to‘gri",
      "Oila ko‘deksi, hukumatning me’yoriy huquqiy hujjatlari",
      "Konstititsiya, prezidentning farmon va farmoyishlari",
      "Fuqarolik ko‘deksi, Xalqaro huquq normalari",
    ],
    correctAnswer: "barcha javob to‘gri",
  },
  {
    id: 100,
    question: "Oila pixologiyasi faninig predmeti qaysi javobda to’g’ri ko’rsatilgan?",
    options: [
      "oilaning ijtimoiy va etnopsixologik xususiyatlari",
      "yoshlarni hayotga ilmiy asosda tayyorlash",
      "yoshlarni oilaviy muloqotga tayyorlash",
      "yoshlarni oilani rejalatirishga o’rgatish",
    ],
    correctAnswer: "oilaning ijtimoiy va etnopsixologik xususiyatlari",
  },
];
